src/main/scala/scalaz/stream/nondeterminism/nondeterminism.scala
src/test/scala/scalaz/stream/MergeNSpec.scala

This resolves issue #297.
The deadlock occurs when the process is 'stuck' waiting for queue.enqueue to complete. Since `to` evaluates actions serially, the only way to allow the process to proceed and react to the completion signal is to interrupt the enqueue action.
The fix here is to make enqueue interruptible.

Fix deadlock when terminating bounded njoin/mergeN

---

src/main/scala/scalaz/stream/Exchange.scala
src/main/scala/scalaz/stream/Process.scala
src/main/scala/scalaz/stream/async/mutable/Signal.scala
src/main/scala/scalaz/stream/compress.scala
src/main/scala/scalaz/stream/nondeterminism/nondeterminism.scala
src/main/scala/scalaz/stream/process1.scala
src/main/scala/scalaz/stream/tee.scala
src/main/scala/scalaz/stream/wye.scala
src/test/scala/scalaz/stream/AsyncSignalSpec.scala
src/test/scala/scalaz/stream/AsyncTopicSpec.scala
src/test/scala/scalaz/stream/ExchangeSpec.scala
src/test/scala/scalaz/stream/MergeNSpec.scala
src/test/scala/scalaz/stream/NioSpec.scala
src/test/scala/scalaz/stream/ProcessSpec.scala
src/test/scala/scalaz/stream/WyeSpec.scala

This is an attempt to make the library a tiny little bit easier internally by sticking to only one alias for `append` in its own sources. Currently `++` and `fby` are used equally frequent. Note that this PR does not touch the definition of `fby`.

Replace usages of 'fby' with '++'.

---

src/main/scala/scalaz/stream/Process.scala

`bufferAll` in `Process1Syntax.apply` seems unnecessary to me. What is its purpose? Can we add a test that fails without it?

Remove bufferAll from Process1Syntax.apply

---

src/main/scala/scalaz/stream/Process.scala
src/test/scala/scalaz/stream/ProcessSpec.scala

`Process.duration` does not wrap the first call to `System.nanoTime` in `Task.delay` so that this time is fixed as soon as one of the `run*` methods is called on this process. This means that running the resulting `Task` multiple times will always yield durations which use the same reference time:
```scala
scala> val t = Process.duration.once.runLog; println(t.run); Thread.sleep(1000); println(t.run)
Vector(62569 nanoseconds)
Vector(1000755454 nanoseconds)
```
This seems odd to me. I would have expected that the reference time is newly obtained on every `Task.run`.
This PR changes the behavior of `duration` to what I would have expected and adds a corresponding test that currently fails on master.

Semantics of Process.duration

---

src/main/scala/scalaz/stream/Process.scala

`Process.duration` uses a [`Duration.apply` function](https://github.com/scala/scala/blob/v2.11.5/src/library/scala/concurrent/duration/Duration.scala#L33) that always returns a `FiniteDuration` so that we can change the output type of `duration` to the more precise `FiniteDuration`. Using `Duration` as type here is just an unnecessary loss of information.

Refine the output type of Process.duration to FiniteDuration

---

src/main/scala/scalaz/stream/Process.scala
src/main/scala/scalaz/stream/ProcessInstances.scala
src/test/scala/scalaz/stream/Process1Spec.scala
src/test/scala/scalaz/stream/TestInstances.scala

This adds the `Category` instance for `Process1`. It builds upon the changes in #276 and should be merged after that PR.

Add Category[Process1] instance

---

src/main/scala/scalaz/stream/compress.scala

Inflater and Deflater uses native code and maintain some state outside the reach of the GC. This is normally cleaned up by the finalize methods, but if many are created and discarded rather rapidly, the GC may not have cause for concern and unchecked memory consumption ensues.

Call `end` methods on Inflater and Deflater

---

src/main/scala/scalaz/stream/Exchange.scala

I've added implicit Strategy to Exchange.run because in it's implementation it calls `read.wye` which takes one. It made this call with `DefaultStrategy` before.

Add implicit Strategy to Exchange.run

---

src/main/scala/scalaz/stream/Process.scala
src/main/scala/scalaz/stream/time.scala
src/test/scala/scalaz/stream/AsyncSignalSpec.scala
src/test/scala/scalaz/stream/ExchangeSpec.scala
src/test/scala/scalaz/stream/MergeNSpec.scala
src/test/scala/scalaz/stream/ProcessSpec.scala
src/test/scala/scalaz/stream/QueueSpec.scala
src/test/scala/scalaz/stream/TimeSpec.scala
src/test/scala/scalaz/stream/WyeSpec.scala

This PR moves every time related `Process` from the `Process` companion into a separate `time` module (as proposed in https://github.com/scalaz/scalaz-stream/pull/253#issuecomment-59678852).

Move time related processes into a separate module

---

src/main/scala/scalaz/stream/Process.scala

`Process.toTask` isn't referentially transparent (see #315).  This deprecates `toTask` and introduces `stepTask`, which satisfies the same use-case while being easier to reason about.  Note that `stepTask` still shares the major foible of `toTask`, which is that premature abortion of the step process will result in resource leaks, but at least the type signature now provides sufficient power to reason about restart semantics.  If nothing else, maybe the documentation will help a bit.

Implemented (and documented) a safe(r) toTask-like function

---

src/main/scala/scalaz/stream/wye.scala
src/test/scala/scalaz/stream/WyeSpec.scala

Fixes #316.
In addition to ensuring multiple terminate requests complete, this will also complete the pending `Get`, if there is one, before attempting to kill.

Wye clobbered halt fix

---

src/test/scala/scalaz/stream/WyeSpec.scala

I added this test, and sometimes it fails (i.e. times out). When I commented out all but the last two tests in the suite in failed consistently. When I ran `sbt test-only *WyeSpec*` the added test failed once and passed once.

Adds pipe + merge test in WyeSpec. Test nondeterministically fails.

---

.travis.yml

Under the [Testing Against Multiple JDKs](http://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs) section, one can see that `openjdk8` is not supported. Hence why the PR just includes `oraclejdk8`.

Adds oraclejdk8 to travis build.

---

src/main/scala/scalaz/stream/process1.scala
src/test/scala/scalaz/stream/Process1Spec.scala

Adds `Tuple2` equivalents of `process1.lift{L,R}`. These require an additional function, `B => Option[C]`, that lets any final values emitted from cleanup to be optionally converted to a pair.

Add process1.lift{First,Second}

---

build.sbt
src/main/scala/scalaz/stream/io.scala

Also modifies `io.toInputStream` to use the newly-exposed 4-arg `copyToArray` function, which improves efficiency quite nicely!  Special thanks to @mpilquist.

Updated to scodec-bits 1.0.6

---

src/main/scala/scalaz/stream/Process.scala
src/main/scala/scalaz/stream/tcp.scala
src/test/scala/scalaz/stream/MergeNSpec.scala
src/test/scala/scalaz/stream/ProcessSpec.scala
src/test/scala/scalaz/stream/TcpSpec.scala
src/test/scala/scalaz/stream/WyeSpec.scala

There's really no reason (that I can think of) for `runAsync` to be implemented using raw `Actor`.  This reimplements it using `Task`, also fixing a bug regarding duplicated `onComplete` evaluation, cleaning up the signaling, making the interrupt mechanism more responsive, and also opens the door to a more reasonable type signature down the road (propagating the `Task` context into `njoin` and `wye`).
The first of the two really notable changes here are that we are now using `Task`'s `runAsyncInterruptibly`, which gives us the ability to kill a `Task` (within limits).  This is a strict improvement over the old `Process#runAsync`, which would literally leak threads whenever a `Task` continued running for a long time after the interrupt.  This happens, for example, if we do a …

Cleaner runAsync without redundant cleanups

---

src/main/scala/scalaz/stream/Cause.scala
src/main/scala/scalaz/stream/Process.scala
src/main/scala/scalaz/stream/async/mutable/WriterTopic.scala
src/main/scala/scalaz/stream/io.scala
src/main/scala/scalaz/stream/nondeterminism/nondeterminism.scala
src/main/scala/scalaz/stream/tcp.scala
src/main/scala/scalaz/stream/wye.scala
src/test/scala/scalaz/stream/MergeNSpec.scala
src/test/scala/scalaz/stream/ProcessSpec.scala
src/test/scala/scalaz/stream/ResourceSafetySpec.scala
src/test/scala/scalaz/stream/TcpSpec.scala
src/test/scala/scalaz/stream/WyeSpec.scala

This is a straight extension of #326, I just wanted to create a separate PR in order to keep the review clean.  I basically just cherry picked some commits from #318 and fixed the merge conflicts.  The result is a) more tests in `WyeSpec`, and b) a working `step` function!
BTW, I'd also like to petition we rename `runAsync` to `stepAsync`.  Its name implies that it runs the process all the way to the end, which is not at all what actually happens.

Cherry-picks `step` fixes from Pavel's PR

---

src/main/scala/scalaz/stream/wye.scala

See ticket #260. These methods are being removed rather than
deprecated because they do not work at all and should not be used.

Removes wye.drainL and wye.drainR.

---

src/main/scala/scalaz/stream/Exchange.scala
src/main/scala/scalaz/stream/async/mutable/Queue.scala
src/main/scala/scalaz/stream/async/package.scala
src/main/scala/scalaz/stream/nondeterminism/nondeterminism.scala
src/test/scala/scalaz/stream/MergeNSpec.scala
src/test/scala/scalaz/stream/ProcessSpec.scala
src/test/scala/scalaz/stream/QueueSpec.scala

Satisfies #338.  Actually wasn't all that difficult.  The only downside I see is a *very* small constant-factor increase to the cost of dequeuing a single element (previously, the only supported use-case).  This factor comes from the boxing of that element inside a single-element list.  I'm not too concerned about it though, since all the other boxing utterly dwarfs this one addition.

Implemented batch dequeuing for async.Queue

---

src/main/scala/scalaz/stream/Process.scala

I forgot to fix this before PRing bug/step.  Relying on `Terminated` is a pretty brittle hack.  The private exception type given here is unambiguous and cannot be thrown from the outside.  It's interesting to note that this is the second item to come out of the `stepAsync` code review with @viktorklang.  I just got so excited about the first item (the last race condition fix) that I forgot about the other one!

Added special exception type for pre-step interrupt check

---

src/main/scala/scalaz/stream/Process.scala
src/main/scala/scalaz/stream/channel.scala
src/main/scala/scalaz/stream/process1.scala
src/main/scala/scalaz/stream/sink.scala
src/main/scala/scalaz/stream/tee.scala
src/main/scala/scalaz/stream/writer.scala
src/main/scala/scalaz/stream/wye.scala

With the addition of `channel.scala`, `sink.scala`, and `writer.scala` there is the possibility to move the syntax classes for `Channel`, `Process1`, `Sink`, `Tee`, `Writer`, and `Wye` out of `Process.scala`.

Move most syntax classes out of Process.scala

---

src/main/scala/scalaz/stream/async/mutable/Queue.scala
src/main/scala/scalaz/stream/async/package.scala
src/main/scala/scalaz/stream/sink.scala
src/test/scala/scalaz/stream/QueueSpec.scala

Adds circular buffers.
I believe this also fixes an off-by-one error in async.Queue, where the queue will begin blocking producers at size `bound - 1` rather than `bound`. And if the queue size was at `bound`, it would have to be dequeued twice to see any results.
Review by @pchlupacek appreciated.

Circular buffers

---

src/test/scala/scalaz/stream/AsyncSignalSpec.scala
src/test/scala/scalaz/stream/MergeNSpec.scala

`async.signal` is [deprecated](https://github.com/scalaz/scalaz-stream/blob/2ba023db717fdaa03a50977ef3718ed67661bbd2/src/main/scala/scalaz/stream/async/package.scala#L40) and already just calling `async.signalUnset`
this just removes compiler warnings and should close #310

Use async.signalUnset instead of deprecated async.signal.

---

src/main/scala/scalaz/stream/package.scala
src/main/scala/scalaz/stream/writer.scala
src/test/scala/scalaz/stream/ProcessSpec.scala
src/test/scala/scalaz/stream/TestInstances.scala
src/test/scala/scalaz/stream/WriterSpec.scala
src/test/scala/scalaz/stream/examples/WritingAndLogging.scala

This PR fixes #344. In its current form it just changes `drainO` and `drainW` to be consistent with `Process.drain`.

Make drain{O,W} consistent with Process.drain

---

build.sbt
project/plugins.sbt

Remember that, in SBT, `version` is a `SettingKey` and not a `TaskKey`, meaning that the value is computed *once* and not recomputed until reload!  Thus, if you make a new commit, tag or otherwise do something that *should* modify the value of `version`, you need to `reload` to see it take effect.
When in doubt, `show version`.

Implemented sbt-git

---

src/main/scala/scalaz/stream/tcp.scala
src/main/scala/scalaz/stream/udp.scala

Motivation is binding to port 0 and accessing the bound port number.

Add `localAddress` method to `tcp` and `udp` modules

---

src/main/scala/scalaz/stream/hash.scala

uses ByteBuffer to supply the bytes to the MessageDigest for performance improvement, tags the returned ByteVectors as being of a specific output type matching the selected hash algorithm, and provides a typeclass like provider for the MessageDigest selection

hash improvements, performance and type-safety

---

src/main/scala/scalaz/stream/process1.scala
src/test/scala/scalaz/stream/Process1Spec.scala

Adds a process1 with the following type signature:
```scala
def stateScan[S, A, B](init: S)(f: A => State[S, B]): Process1[A, B]
```
I've wanted this for a while, and it is in general much more usable than `scan` despite serving essentially the same purpose.  Decided to relax by scratching my own itch.

Implemented scan through State process1

---

src/main/scala/scalaz/stream/process1.scala
src/test/scala/scalaz/stream/Process1Spec.scala

This adds
```scala
def mapAccumulate[S, A, B](init: S)(f: (S, A) => (S, B)): Process1[A, (S, B)]
```
to `process1` as discussed in #309.

Add process1.mapAccumulate as discussed in #309

---

src/main/scala/scalaz/stream/async/mutable/Queue.scala
src/main/scala/scalaz/stream/async/package.scala
src/test/scala/scalaz/stream/QueueSpec.scala

This fixes data lost by premature closure of the `dequeue` process, giving users a chance to run a fresh `dequeue` that recovers from the failure.  There *is* a tradeoff here though, and that tradeoff is that we may see data multiple times.  We can't really be absolutely sure that a premature closure of `dequeue` is an error, and so we over-approximate by just pushing the data back in regardless (we may be able to do better here once we address #288).  Given the way in which queues are generally used (i.e. often connected to external data sources, such as network sockets), I don't think this limitation is too much of a problem.  If you *really* need to ensure that you don't see repeated data from fresh dequeues, you should run an LRU deduplicating cache.
Note that this *also* slightly …

Recover lost data in Queue

---

src/main/scala/scalaz/stream/Process.scala
src/main/scala/scalaz/stream/async/mutable/Queue.scala
src/main/scala/scalaz/stream/async/mutable/WriterTopic.scala
src/main/scala/scalaz/stream/io.scala
src/main/scala/scalaz/stream/nio/package.scala
src/main/scala/scalaz/stream/wye.scala
src/test/scala/scalaz/stream/NioSpec.scala
src/test/scala/scalaz/stream/ProcessSpec.scala

This is the compromise solution to #369.  `Terminated` is still here, and so is `asHalt`, but `eval` no longer magically swallows `Terminated` without warning anyone.  As a general rule, if you need `Terminated` (as some things do, due to the half-crippled nature of `Channel`), you need to add the `onHalt { _.asHalt }` bit explicitly.
The giant hanging chad in all of this is the fact that I had to change some code to explicitly contain this `onHalt` behavior even within scalaz-stream.  In general, this was confined to fairly low-level stuff (like the implementation of `wye`), but not always.  In particular, the `through` combinator got the `asHalt` treatment, since it is very common to implement effectful `Channel` termination via `Terminated`, and in fact under many circumstances there …

Removed auto-magical Terminated coercion in eval/repeatEval

---

src/main/scala/scalaz/stream/async/mutable/Signal.scala
src/test/scala/scalaz/stream/AsyncSignalSpec.scala

This addresses #389.  The problem was that the `Writer1` inside of `Signal` would never set up its state machine with the initial value.  This PR fixes that by setting up the initial value via `feed1` rather than by emitting it over to `WriterTopic`.

Maintain internal writer state machine upon initial signal value

---

src/main/scala/scalaz/stream/Process.scala
src/main/scala/scalaz/stream/io.scala
src/test/scala/scalaz/stream/ProcessSpec.scala

@runarorama and I worked on this for a use case within [Remotely](https://github.com/oncue/remotely). I have now found a use for it within another project, so I felt it was time to polish it up and submit a PR so that everyone could benefit from this function.
I also created a method on `Await` that encapsulates a common pattern within the implementation to "evaluate" an Await into an `F` of a new `Process` that is not awaiting anymore (has some elements to `Emit`). As you can imagine, many methods need to "await" some elements.

Add uncons function to Process

---

src/main/scala/scalaz/stream/Process.scala
src/test/scala/scalaz/stream/ProcessSpec.scala

Basically addressing #402.  Interestingly enough, this fix doesn't really apply on series/0.7 unless I do something slightly crazy.  I could make it work, but it would alter semantics.  `Terminated` basically doesn't fully work in 0.7 and hasn't worked for a while, likely since 0.5 (when it was introduced).

Fixes Terminated behavior inside to and observe

---

src/main/scala/scalaz/stream/io.scala
src/test/scala/scalaz/stream/ToInputStreamSpec.scala

- toInputStream: do not wrap IOException into another IOException

- toInputStream: do not fail on Emit steps encountered after a process is killed

---

build.sbt

As a result of this PR, the ScalaDoc for `Process` includes methods from `SourceSyntax`, `toProcess1Syntax`, `toWyeSyntax`, etc.

Modify ScalaDoc generation so that extension methods added via constrained implicits are documented

---

build.sbt
src/test/scala/scalaz/stream/AsyncSignalSpec.scala
src/test/scala/scalaz/stream/AsyncTopicSpec.scala
src/test/scala/scalaz/stream/CauseSpec.scala
src/test/scala/scalaz/stream/CompressSpec.scala
src/test/scala/scalaz/stream/ExchangeSpec.scala
src/test/scala/scalaz/stream/HashSpec.scala
src/test/scala/scalaz/stream/LinesSpec.scala
src/test/scala/scalaz/stream/MergeNSpec.scala
src/test/scala/scalaz/stream/NioFilesSpec.scala
src/test/scala/scalaz/stream/NioSpec.scala
src/test/scala/scalaz/stream/PrintSpec.scala
src/test/scala/scalaz/stream/Process1Spec.scala
src/test/scala/scalaz/stream/ProcessPerformanceSpec.scala
src/test/scala/scalaz/stream/ProcessSpec.scala
src/test/scala/scalaz/stream/QueueSpec.scala
src/test/scala/scalaz/stream/ResourceSafetySpec.scala
src/test/scala/scalaz/stream/TeeSpec.scala
src/test/scala/scalaz/stream/TimeSpec.scala
src/test/scala/scalaz/stream/ToInputStreamSpec.scala
src/test/scala/scalaz/stream/UnsafeChunkRSpec.scala
src/test/scala/scalaz/stream/Utf8DecodeSpec.scala
src/test/scala/scalaz/stream/WyeSpec.scala

Scalacheck 1.12.4 instantiates an instance of test classes for
each property to be evaluated. Using `protect` instead of `secure`
makes the property evaluation lazy, to avoid doing a lot of extra
work here.

Update scalacheck to 1.12.4, evalulate properties lazily.

---

.travis.yml
build.sbt

Step one of a three step process.  Step two is rebasing this back to `series/0.7` and `series/0.7a`, and step three is actually pushing the release to Sonatype.

Updated to Scala 2.11.7 and 2.12.0-M1

---

.gitignore
build.sbt
src/it/scala/ProcessRegressionTest.scala

- adresses #399
- uses [scalameter regression testing][1]
- runs in sbt integration test target, i.e. `it:test`
- generates an offline html report in the tmp subdir of the main project
dir, there is an index.html you can open to inspect the results, the
regression history is also saved in that tmp subdir
- might need a few tweaks in terms of stability, confidence intervals, etc.
- I included just a simple dummy example to give you an idea of how it
looks like, but adding new stuff to test should be straightforward
- I am not sure whether `Process.constant(1).take(n)` is the fastest way
to create a reasonably sized Process
[1]: http://scalameter.github.io/home/gettingstarted/0.7/regressions/index.html

skeleton for regression testing

---

src/main/scala/scalaz/stream/wye.scala
src/test/scala/scalaz/stream/ResourceSafetySpec.scala

This pull request fixes #424. @djspiewak could you please take a look?
The original issue has been solved. I've added a spec covering it.
But... sometimes this spec fails. It doesn't fail if we add `Thread.sleep(100)` after `.run.run` and constantly fails if we add `Thread.sleep(1000)` to `release` task. It looks like `.run.run` doesn't wait for termination of `release` task. I feel it is another issue.
I don't know how to fix this. Probably if changes to `wye` are good, we can merge it without a spec and fix it later. Any suggestions?

Fix resource safety for `wye`, fixes #424

---

src/main/scala/scalaz/stream/io.scala
src/test/scala/scalaz/stream/IteratorSpec.scala

I find myself using my own IteratorToProcess method quite often, so I think probably an Process constructor from iterators belongs in scalaz-stream. It can be dangerous since iterators aren't re-usable, but I hope the warning I added in the documentation is enough to put people on the right path.

Add a constructor to Process for using iterators

---

build.sbt
project/MiMa.scala
project/plugins.sbt

I don't think there's a nice way of checking which branch we're on, and selecting the appropriate version on that basis (for example, we only want to check against 0.7.2a on the `series/0.7a` branch).
Instead, it should be easy to override behaviour per-branch.
Set `checkABICompatibilityVersion` to define which version to check.
Set `ignoredABIProblems` to define what ABI issues to ignore.
Check with `sbt mimaReportBinaryIssues`
This cherry-picks cleanly to `series/0.7a`.

Add MiMa compability plugin to build

---

build.sbt
src/main/scala/fs2/StreamDerived.scala
src/test/scala/fs2/Process1Spec.scala
src/test/scala/fs2/StreamsSpec.scala
src/test/scala/fs2/TestUtil.scala

This adds basic tests for `process1.{lift, last, take}`. One interesting question here: how can I test if `take` preserves the chunkiness of the input? I've also added `emitAll` which is nicer to use than `Stream(v: _*)`.

FS2: Add Process1Spec that tests the current transducers

---

.travis.yml
build.sbt
src/main/scala/fs2/Process1.scala
src/test/scala/fs2/Process1Spec.scala
src/test/scala/fs2/TestUtil.scala

This adds `process1.chunks` which is used to test that `take` preserves the chunkiness of its input.
What I observed here:
* The actual `Process1` definition feels like 100% boilerplate:
```scala
def chunks[I]: Process1[I,Chunk[I]] =
new Process1[I,Chunk[I]] { def run[F[_]] = _.pull[F,Chunk[I]](pull.chunks) }
```
* If you leave out the type parameter in `_.pull[F,Chunk[I]](...)`, you get weird compiler errors.
* I had to repeat `Chunk[I]` there three times
* `Chunk` has no sensible `equals`:
```scala
scala> val x = Chunk.singleton(1) == Chunk.singleton(1)
x: Boolean = false
```

FS2: Test that take preserves the chunkiness of the input

---

src/main/scala/fs2/Process1.scala
src/main/scala/fs2/pull1.scala

This is a question. In scalaz-stream we have `receive1` which is the same as `await1.flatMap`. Do we want something similar here? `h => h.await flatMap ` is already a recurring pattern.

Add shortcut for h => h.await.flatMap?

---

.travis.yml
build.sbt

The build will fail because ScalaCheck is not yet available for 2.12.0-M3:
```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalacheck#scalacheck_2.12.0-M3;1.12.5: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```
But a local build without ScalaCheck went just fine.
/cc @SethTisue

Build with Scala 2.12.0-M3

---

src/main/scala/fs2/Chunk.scala
src/main/scala/fs2/Process1.scala
src/main/scala/fs2/Process1Ops.scala
src/test/scala/fs2/Process1Spec.scala

process1.fold:
Folds all inputs using an initial value `z` and supplied binary operator,
and writes the final result to the output of the supplied `Pull` when the
stream has no more values.
process1.fold1:
Folds all inputs using the supplied binary operator, and writes the final
result to the output of the supplied `Pull` when the stream has no more values.
process1.scan:
Writes `z` to the output, followed by the result of repeated applications
of `f` to each input in turn. Works in a chunky fashion, and creates a
`Chunk.indexedSeq` for each converted chunk.
process1.scan1:
Writes the result of repeated applications of `f` to each input in turn.
Works in a chunky fashion, and creates a `Chunk.indexedSeq` for each
converted chunk.

FS2: Implement process1.scan, process1.scan1, process1.fold, process1.fold1

---

src/main/scala/fs2/Stream.scala
src/main/scala/fs2/StreamDerived.scala
src/main/scala/fs2/StreamOps.scala
src/main/scala/fs2/Streams.scala
src/main/scala/fs2/Wye.scala
src/main/scala/fs2/concurrent.scala
src/test/scala/fs2/ConcurrentSpec.scala
src/test/scala/fs2/ResourceSafetySpec.scala

Okay, I feel like the resource safety tests are in a pretty good place, and AFAICT all the ones that are still relevant from the old codebase have been ported over or are covered by more general scalacheck scenarios.
This PR also includes tests for `merge` and `concurrent.join` operators, which are used in the resource safety tests (so this tests for asynchronous resource allocation). Scalacheck found a couple bugs with the implementations of these.
When this is merged I'm planning on closing #442. Of course, if anyone comes up with new things to test for later, we can still add them. :)

Resource safety test suite

---

src/main/scala/fs2/Process1.scala
src/main/scala/fs2/Process1Ops.scala
src/main/scala/fs2/PullOps.scala
src/main/scala/fs2/Strategy.scala
src/main/scala/fs2/StreamDerived.scala
src/main/scala/fs2/StreamOps.scala
src/main/scala/fs2/Tee.scala
src/main/scala/fs2/Wye.scala
src/main/scala/fs2/concurrent.scala
src/main/scala/fs2/fs2.scala
src/main/scala/fs2/pull1.scala
src/test/scala/fs2/CompilationTest.scala
src/test/scala/fs2/ConcurrentSpec.scala
src/test/scala/fs2/Process1Spec.scala
src/test/scala/fs2/ResourceSafetySpec.scala
src/test/scala/fs2/TestUtil.scala

This PR is built on #475 
Sort of a subtle issue, but with the current representation, you can't invoke a `Stream[F,A] => Stream[F,B]` from within a `Process1`. That's not good for composition. And making `Handle[F,A] => Pull[F,O,R]` the basis for composition doesn't work out well because you can't adjust the output type `O` after the fact. (And changing this would complicate the API and the implementation.)
With the new representation, a `Process1[A,B]` is just a regular function from `Stream[Pure,A] => Stream[Pure,B]`, which can be promoted to a `Stream[F,A] => Stream[F,B]` via `Process1.covary`, or the `pipe` and `pipe2` combinators will automatically do the right thing.
I originally thought this representation would lead to boilerplate, but with the `pull` and `repeatPull` …

Switch to new and improved representation of `Process1`, `Tee`, and `Wye`

---

src/main/scala/fs2/Chunk.scala
src/main/scala/fs2/Process1.scala
src/main/scala/fs2/Process1Ops.scala
src/test/scala/fs2/Process1Spec.scala

@pchiusano This isn't ready to be committed (needs a bit more review, tests, and comments), but I wanted to check that you'd be happy with the general approach.
I think it can probably be used by a lot of other combinators, e.g. a sample implementation of sliding:
```scala
def sliding[F[_],I](n: Int)(implicit F: NotNothing[F]): Handle[F,I] => Pull[F,IndexedSeq[I],Handle[F,I]] =
collectAccumulate(new collection.mutable.ArrayBuffer[I](n))((arr, i: I) => {
arr += i
if (arr.size >= n) {
val newArr = new collection.mutable.ArrayBuffer[I](n)
arr.tail.copyToBuffer(newArr)
(newArr, Some(arr))
} else (arr, None)
})(s => None)
```
Also I'm not sure about the name :smile:

FS2: Add process1.mapAccumulate

---

src/main/scala/fs2/Chunk.scala
src/main/scala/fs2/Process1.scala

Implement `process1.zipWithNext` in terms of `process1.mapAccumulate`, so we don't need `Chunk#zipWithNext`.

FS2: Simplify process1.zipWithIndex

---

src/main/scala/fs2/Process1.scala
src/main/scala/fs2/Process1Ops.scala
src/main/scala/fs2/pull1.scala
src/test/scala/fs2/Process1Spec.scala

Implements `process1.zipWithNext`. It zips the elements of the input with its next element wrapped into `Some`. The last element is zipped with `None`.

FS2: Add process1.zipWithNext, process1.zipWithPrevious, process1.zipWithPreviousAndNext

---

src/main/scala/fs2/Process1.scala
src/main/scala/fs2/Process1Ops.scala
src/main/scala/fs2/pull1.scala
src/test/scala/fs2/Process1Spec.scala

Implements:
- chunkLimit - Repeatedly output chunks with a maximum size.
- chunkN - Group chunks so each group has a specified maximum size.
- vectorChunkN - Flatten grouped chunks into a Vector (like old chunk combinator).
Updates pull1.awaitN to allow chunk sequences sized less than specified.

Add chunkLimit/chunkN/vectorChunkN combinators

---

src/main/scala/fs2/Stream.scala
src/main/scala/fs2/StreamDerived.scala
src/main/scala/fs2/Streams.scala
src/main/scala/fs2/util/Free.scala
src/main/scala/fs2/util/UF1.scala
src/main/scala/fs2/util/util.scala

…and moved type alias for UF1 to util package object.
Not a huge fan of some of the names but I used 2 rules when choosing them:
- must end in `Ops`
- must start with the name of the class that's being decorated
These rules are designed to simplify source navigation in symbol aware text editors.

Renamed implicit classes defining operators to match pattern ...Ops

---

src/main/scala/fs2/pull1.scala
src/test/scala/fs2/Process1Spec.scala

Simplifies pull1.awaitN by replacing flatMap with map.
Fixes/improves test coverage of process1.chunkN.

Simplify pull1.awaitN, improve tests for process1.chunkN

---

src/main/scala/fs2/StreamDerived.scala
src/main/scala/fs2/pull1.scala

Implemented `Pull.awaitNonempty` (obtains the next nonempty `Chunk`), `Pull.echo1` and `Pull.echoChunk`. Also some convenient aliases for `receive1`, `receive`, `echo1`, and `echoChunk` on `Handle`. And added `repeatPull2`, analogous to `repeatPull`, useful for building `Tee` values.
No unit tests, but let's just start using these in new definitions and feel free to update old ones to get some ambient testing. I think the `echo`, `echo1`, and `echoChunk` will be particularly useful in various tee and wye definitions.

Added several convenience functions

---

.travis.yml

Now, old scalaz package test has been removed, so `"testOnly fs2.*"` designation is unnecessary.
Compare
https://travis-ci.org/functional-streams-for-scala/fs2/jobs/96390258#L801
with
https://travis-ci.org/functional-streams-for-scala/fs2/jobs/96461525#L806

Removed unnecessary "testOnly" on Travis

---

core/src/main/scala/fs2/util/Task.scala
core/src/test/scala/fs2/async/SemaphoreSpec.scala

I noticed some flaky behavior when using the new queue implementation. After some discussion with @pchiusano, I decided to write some tests for Semaphore. This exposed a bug in Semaphore, which Paul fixed, but even after that fix, I was still experiencing deadlocks with the SemaphoreSpec in this PR. The deadlocks were caused by 2 bugs in AsyncExt[Task], where the waitingModify map was being updated as if it was a mutable map. After fixing, both the semaphore and the queue tests pass.

Fix race condition in AsyncExt[Task] 

---

build.sbt

Without this change, "sbt publish-local" fails on the io module with errors like:
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: fs2#fs2-core_2.11;0.9-287e0d4: configuration not public in fs2#fs2-core_2.11;0.9-287e0d4: 'test'. It was required from fs2#fs2-io_2.11;0.9-287e0d4 test
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          fs2:fs2-core_2.11:0.9-287e0d4
[warn]            +- fs2:fs2-io_2.11:0.9-287e0d4

Fix publishing of fs2-io module

---

core/src/main/scala/fs2/util/Task.scala

Getting the controversial PRs out of the way tonight... :smile: 
This pattern comes up a lot when integrating `Task` with other libraries. For example, completing a spray/akka-http route with a `Task` can be accomplished by running the route as a future and then completing with the future.

Added ability to run a Task as a stdlib Future

---

build.sbt
project/plugins.sbt
version.sbt

This PR sets the build up to publish snapshots and releases to Sonatype. It uses sbt-release to automate the release process, besides the final Sonatype staging repository closure/release step. Publishing snapshots to Sonatype's snapshot repository is done via `+publish-signed`. Releasing a stable build is done via `release` and then `sonatypeReleaseAll`. Instead of the last step, Sonatype's OSS Nexus UI can be used to close and release the staging repository created by the release step.
The generated POMs *should* pass Sonatype's validation rules, as I based the configuration off the scodec build. We won't know until we try to build a release though.
Note that this PR removes git based versioning in favor of snapshot versioning. I realize this may be controversial, though I think it is …

Automated release process; configured for publishing snapshots and releases to Sonatype

---

build.sbt
core/src/main/scala/fs2/Strategy.scala
core/src/main/scala/fs2/Stream.scala
core/src/main/scala/fs2/concurrent.scala
core/src/main/scala/fs2/internal/Future.scala
core/src/main/scala/fs2/internal/LinkedMap.scala
core/src/main/scala/fs2/internal/Ref.scala
core/src/main/scala/fs2/internal/Resources.scala
core/src/main/scala/fs2/task.scala
core/src/main/scala/fs2/util/Free.scala
core/src/main/scala/fs2/util/Task.scala
core/src/test/scala/fs2/ConcurrentSpec.scala
core/src/test/scala/fs2/ResourceSafetySpec.scala
core/src/test/scala/fs2/TestUtil.scala
core/src/test/scala/fs2/internal/RefSpec.scala

This addresses the tests in #516, which I've merged in and cleaned up some. Basic idea is:
* When a `Pull` is being shut down, there may be `awaitAsync` steps still running. If any of those running steps are in the middle of a resource acquisition, we wait until any such acquisitions complete, then interrupt them.
* On shutdown, we run all outstanding finalizers and simultaneously _close the resources tracker_. (See the `Resources` data type in `internal`.) This ensures no new resources can be acquired that we don't know about.
* Any resource acquisition checks the resource tracker to make sure it isn't closed. If it is closed, it fails with `Interrupted` before starting to acquire any resources.
So, you can do a `merge` or `interrupt` where one side never produces a value, and that works …

Fix for interrupt handling to allow for "hanging awaits" on closing a Pull

---

build.sbt
core/src/main/scala/fs2/Strategy.scala
core/src/main/scala/fs2/Stream.scala
core/src/main/scala/fs2/concurrent.scala
core/src/main/scala/fs2/internal/Future.scala
core/src/main/scala/fs2/internal/LinkedMap.scala
core/src/main/scala/fs2/internal/Ref.scala
core/src/main/scala/fs2/internal/Resources.scala
core/src/main/scala/fs2/task.scala
core/src/main/scala/fs2/util/Free.scala
core/src/main/scala/fs2/util/Task.scala
core/src/test/scala/fs2/ConcurrentSpec.scala
core/src/test/scala/fs2/ResourceSafetySpec.scala
core/src/test/scala/fs2/TestUtil.scala
core/src/test/scala/fs2/internal/RefSpec.scala

This should be merged after #526. It replaces the use of `ReentrantLock` with [`Ref.ReadWriteSpinLock`](https://github.com/functional-streams-for-scala/fs2/blob/topic/redesign-fastref/core/src/main/scala/fs2/internal/Ref.scala#L73-L103).
@mpilquist WDYT?
There might be an even lower contention version of this, based on `LongAdder` to track the reader count, but I gave up trying to figure that out.

Implement nonblocking version of `Ref`

---

core/src/main/scala/fs2/time/time.scala
core/src/test/scala/fs2/time/TimeSpec.scala

This PR is a straight PR of the 0.8 time object. The test for `awakeEvery` is commented out because it is failing. Based on some very brief analysis, it appears that discrete mutable signals are broken.

Ported fs2.time object from 0.8

---

core/src/main/scala/fs2/Chunk.scala
core/src/main/scala/fs2/compress.scala
core/src/test/scala/fs2/ChunkSpec.scala
core/src/test/scala/fs2/CompressSpec.scala
core/src/test/scala/fs2/Process1Spec.scala

I suspect this will need some discussion before being added:
I tried using `Chunk[Byte]` instead of `ByteVector`. The variance on `toArray` was annoying :)
Also, it seems that `Byte` values can easily be de-optimized, e.g. if I want an `Either[DataFormatException, Byte]`. Perhaps this should work on the `Chunk[Byte]` level instead? But then there's not a huge amount of benefit to the wrapping of `ByteVector`?
This will need to either return that `Either` I mentioned above, or it will throw exceptions -- if so, it shouldn't have a `Pure` effect, but `F: Catchable`? Is there a particular pattern you'd like here?

Add compress.deflate, compress.inflate, Chunk.toArray

---

core/src/main/scala/fs2/Process1.scala
core/src/main/scala/fs2/Process1Ops.scala
core/src/main/scala/fs2/pull1.scala
core/src/test/scala/fs2/Process1Spec.scala

My approach for takeRight was to use an accumulator of `Vector[I]` and `awaitN` to slide through the Stream. Once the Stream is exhausted the accumulator is written to output. Is there a better way to output a `Vector[I]` other than the foldLeft approach I took?

Adds takeRight & tail to Process1

---

core/src/main/scala/fs2/internal/LinkedMap.scala
core/src/main/scala/fs2/internal/Resources.scala
core/src/test/scala/fs2/ResourceTrackerSanityTest.scala

This fixes a memory leak reported by @mpilquist in the following code:
```Scala
val big = Stream.constant(1).flatMap { n =>
Stream.bracket(Task.delay(()))(_ => Stream.emits(List(1, 2, 3)), _ => Task.delay(()))
}
big.run.run.run
```
(this is now checked in as `ResourceTrackerSanityTest.scala` in the tests. Just as a standalone main for now, though if anyone would like to automate the test somehow that would be great.)
Issue was that `LinkedMap.updated` was not first removing the old key (if it existed), so a bunch of deleted keys were being accumulated in `insertionOrder`.

Fix memory leak in `LinkedMap` implementation

---

core/src/main/scala/fs2/Pull.scala
core/src/main/scala/fs2/Stream.scala
core/src/main/scala/fs2/StreamOps.scala
core/src/test/scala/fs2/StreamSpec.scala

Caught by @mpilquist. This test previously failed:
```Scala
property("onError (4)") = protect {
Stream.eval(Task.delay(throw Err)).map(Right(_)).onError(t => Stream.emit(Left(t)))
.take(1)
.runLog.run.run ?= Vector(Left(Err))
}
```
Now it passes. Also added `Stream.attempt` convenience function.

Fix to Pull.eval that would allow exceptions to go uncaught

---

core/src/main/scala/fs2/Pull.scala
core/src/main/scala/fs2/Stream.scala
core/src/test/scala/fs2/MemorySanityChecks.scala
core/src/test/scala/fs2/StreamPerformanceSpec.scala

This gets rid of any FS2 interpreter internal use of the nonstrict append, which wraps its second argument in a `suspend`. We had a memory leak due to nesting of these suspends. I don't fully understand the bug but this just eliminates this class of errors as a possibility.
I feel like the best solution would be to use types to guarantee that we don't have `suspend { suspend { .. }}` or any nesting of `suspend`, which is redundant and inefficient. I'm not sure if there's a nice way to do this without a major overhaul though. Something to ponder for later, I think this fix is ok for now.

Eliminate class of time/space leaks from internal use of nonstrict append

---

core/src/main/scala/fs2/Stream.scala
core/src/main/scala/fs2/StreamCore.scala
core/src/main/scala/fs2/StreamOps.scala
core/src/main/scala/fs2/Streams.scala
core/src/main/scala/fs2/Trace.scala
core/src/main/scala/fs2/fs2.scala

I can't say I'm enamored with this solution, but I think it would be valuable to support tracing without recompiling FS2. Open to suggestions on how better to implement this. I wanted tracing to have as little overhead as possible -- this implementation results in a invokevirtual call and a branch on each step through the interpreter, which is negligible performance wise.

Formalized tracing support in the interpreter

---

core/src/main/scala/fs2/PullDerived.scala
core/src/main/scala/fs2/util/Free.scala
core/src/main/scala/fs2/util/Monad.scala
core/src/main/scala/fs2/util/Task.scala
io/src/main/scala/fs2/io/file/FileHandle.scala
io/src/main/scala/fs2/io/file/package.scala

@pchiusano This is an early stab at implementing some NIO-based file I/O. Feedback welcome on: style, API, general approach.
Generally:
- `file.open` provides a `Pull` containing a single `AsynchronousFileChannel`.
- `file.readAsync`, `file.writeAsync` take a `AsynchronousFileChannel` and read/write from/to it asynchronously, given an `Async` instance.
- `file.readAllAsync` makes use of `file.open` and `file.readAsync` to read a full file as a `Stream`.
I've never been that convinced that being able to provide the buffer size as a streaming input was that useful, so it's not in this version.
(`Monad.suspend` is also in the tcp rework, and seems essential given the cleanup code in `Stream.bracket` is created before any work is done)

Add async read/write based on NIO

---

core/src/main/scala/fs2/text.scala
core/src/test/scala/fs2/Utf8DecodeSpec.scala

The tests and a lot of the logic are taken from scalaz-stream <= 0.8.
(kind of miss `ByteBuffer` here)
Using `Chunk[Chunk[Byte]]` to make sure that we can round-trip empty strings.

Add fs2.text.utf8Encode and fs2.text.utf8Decode

---

core/src/main/scala/fs2/async/mutable/Queue.scala
core/src/main/scala/fs2/async/mutable/Semaphore.scala
core/src/main/scala/fs2/concurrent.scala
core/src/main/scala/fs2/pipe.scala
core/src/test/scala/fs2/ConcurrentSpec.scala
core/src/test/scala/fs2/ResourceSafetySpec.scala

Note: based on #582 and #581 
Note: don't merge yet, it doesn't work
This uses @pchlupacek's suggestion [here](https://github.com/functional-streams-for-scala/fs2/pull/577#issuecomment-211028139). It's not quite working yet, though. The join(3) test currently hangs for some reason. Good news is that once this is working, it will fix that linear performance problem spotted by @pchlupacek, where we have to scan all open streams to do a cancellation of the losing steps.
Basic idea here is pretty simple - just have the inner streams dump to a synchronous queue. Each is also controlled by an interrupt signal which is set to true when the outer stream terminates, which should ensure that their finalizers get run. But there are various edge cases to think through, and I apparently goofed …

Queue-based implementation of concurrent.join

---

core/src/main/scala/fs2/StreamDerived.scala
core/src/test/scala/fs2/StreamSpec.scala

While porting the scalaz-streams docs to fs2 I found some unexpected behavior with step-sizes & `Stream.range`. Previously only a positive `by` was supported. 
I elected to return the empty list in failure situations, but I'm curious if you think there is a better solution.

Make Stream.range more robust

---

build.sbt
core/src/test/scala/fs2/ChunkSpec.scala
core/src/test/scala/fs2/CompressSpec.scala
core/src/test/scala/fs2/ConcurrentSpec.scala
core/src/test/scala/fs2/Fs2Spec.scala
core/src/test/scala/fs2/Pipe2Spec.scala
core/src/test/scala/fs2/PipeSpec.scala
core/src/test/scala/fs2/ResourceSafetySpec.scala
core/src/test/scala/fs2/StreamPerformanceSpec.scala
core/src/test/scala/fs2/StreamSpec.scala
core/src/test/scala/fs2/TestUtil.scala
core/src/test/scala/fs2/Utf8DecodeSpec.scala
core/src/test/scala/fs2/async/ChannelSpec.scala
core/src/test/scala/fs2/async/QueueSpec.scala
core/src/test/scala/fs2/async/SemaphoreSpec.scala
core/src/test/scala/fs2/async/SignalSpec.scala
core/src/test/scala/fs2/internal/RefSpec.scala
core/src/test/scala/fs2/time/TimeSpec.scala

While trying to determine why tests randomly hang on Travis, I decided to port the tests from pure ScalaCheck to ScalaTest+Scalacheck. This has a number of benefits including:
- Better error messages
- More predictable test ordering
- Ability to add logging around tests
Based on this logging, I suspect the test that randomly hangs is `asynchronous resource allocation (3)` in `ResourceSafetySpec`.

Ported ScalaCheck tests to ScalaTest

---

core/src/main/scala/fs2/StreamCore.scala

Previously, when reaching the end of a stream, any remaining uncalled finalizers were run in LIFO order. Now they are run in FIFO order. I believe this is more correct, especially since when nesting calls to `bracket`, it's actually the innermost finalizer that will be added to the resources map first and we generally want to call finalizers 'innermost first'. This has the effect that `a.onFinalize(f1).onFinalize(f2)` will run `f1` then `f2`.
Review by @pchlupacek

Fix for #589 finalization order bug

---

core/src/test/scala/fs2/Fs2Spec.scala
core/src/test/scala/fs2/ResourceSafetySpec.scala
core/src/test/scala/fs2/TestUtil.scala
core/src/test/scala/fs2/time/TimeSpec.scala

This is one of the causes of the `concurrent.join` failures.

Added test which demonstrates timing bug in interruption of stream that is evaluating a hung effect

---

core/src/main/scala/fs2/Scope.scala
core/src/main/scala/fs2/StreamCore.scala
core/src/main/scala/fs2/internal/Resources.scala

Previously we were getting exceptions from this.
New behavior is to run the finalizer immediately if finishAcquire fails, under the assumption (which I'm not positive is valid) that if the key has been removed from the map, it's because the stream or scope is being closed.

finishAcquire now returns a Boolean, and this is handled in various places

---

core/src/main/scala/fs2/async/mutable/Queue.scala
core/src/main/scala/fs2/concurrent.scala
core/src/main/scala/fs2/util/Task.scala
core/src/test/scala/fs2/Fs2Spec.scala
core/src/test/scala/fs2/ResourceSafetySpec.scala

- New join implementation is fairer than semaphore based implementation.
This implementation ensures inner streams are started in the order
they appear in the outer stream. The semaphore implementation raced the
inner streams against the semaphore decrement.
- Changed the synchronous none terminated queue such that enqueuing a
`Some` does not block after a `None` has been enqueued.
- Fixed a bug in `Task.get` and similar methods in which message ids
were reused across multiple executions of the task. This resulted in
hung tasks under contention. For example, calling `signal.get` and then running that task multiple times in parallel could lead to some of the tasks never completing.
Review by @pchiusano.

Reimplemented join.

---

build.sbt
core/src/main/scala/fs2/text.scala
core/src/test/scala/fs2/TextSpec.scala
docs/CreatingStreams.md
docs/StartHere.md
docs/guide.md
docs/src/StartHere.md

- I created a tut doc for the example, though I didn't know where to include that in the guide, so it is standalone for now.
- I changed the signature of `utf8Encode` and `utf8Decode` -- both were working with `Chunk[Byte]` instead of `Byte` which made using them with the io package annoying. The original signatures are available under a `C` suffix -- `utf8EncodeC` and `utf8DecodeC`.  The implementations did not exploit the chunky nature in any way, except for the handling of encoding/decoding empty strings -- `utf8EncodeC andThen utf8DecodeC == id` for all strings, whereas `utf8Encode andThen utf8Decode == id` for all non-empty strings. I believe this is due to the fact that we don't emit empty chunks in the interpreter.
- Added a new text.lines pipe, which buffers a stream of strings …

Ported the start here example from 0.8

---

core/src/main/scala/fs2/Async.scala
core/src/main/scala/fs2/Scheduler.scala
core/src/main/scala/fs2/internal/Future.scala
core/src/main/scala/fs2/time/time.scala
core/src/main/scala/fs2/util/Task.scala
core/src/test/scala/fs2/TestUtil.scala
core/src/test/scala/fs2/time/TimeSpec.scala

- Introduced `Scheduler` trait as wrapper for `ScheduledExecutorService`
- Replaced usage of `Duration` with `FiniteDuration`
- Removed old methods implemented in terms of millisecond timeouts
I based this off of #611 but if we decide not to merge that, I can fix this PR.

Miscellaneous cleanup related to time

---

core/src/main/scala/fs2/Async.scala
core/src/main/scala/fs2/util/Task.scala

@pchiusano @mpilquist. This is to allow to write libraries using fs2 that do multiple callbacks from outside the fs2 domain. For example you need to enqueue messages from the `Polling` thread to our queue, and still you don't want to specialize to `Task`. 
I didn't find any better alternative than this, not sure if Option[Throwable] is right idea, perhaps we shall just exception to be thrown. Any thoughts on that?

Introduced `Async.Run`

---

core/src/main/scala/fs2/Async.scala
core/src/main/scala/fs2/time/time.scala
core/src/main/scala/fs2/util/Task.scala
core/src/test/scala/fs2/time/TimeSpec.scala

If we merge #610, then we can use the new `Async.Run` type class to implement the `time` package for arbitrary effect types.

Parametric time

---

core/src/main/scala/fs2/Async.scala
core/src/main/scala/fs2/time/time.scala
core/src/main/scala/fs2/util/Effect.scala
core/src/main/scala/fs2/util/Monad.scala
core/src/main/scala/fs2/util/Task.scala
docs/guide.md
docs/src/guide.md
io/src/main/scala/fs2/io/file/package.scala
io/src/main/scala/fs2/io/tcp/Socket.scala

Moved Monad.suspend to Effect.delay and added new Effect.suspend with same signature as Task.suspend. See [conversation on Gitter](https://gitter.im/functional-streams-for-scala/fs2?at=573c137cae26c1967f9f7efa) for motivation. This needs more docs and updates to the guide. I wanted to open the PR for discussion first (not for merge). If folks tend to agree, I'll write some ScalaDoc and update the guide.

Introduced new Effect type class

---

README.md
core/src/main/scala/fs2/Stream.scala
core/src/main/scala/fs2/StreamDerived.scala
core/src/main/scala/fs2/StreamOps.scala
core/src/main/scala/fs2/Streams.scala
core/src/main/scala/fs2/concurrent.scala
core/src/main/scala/fs2/pipe.scala
core/src/main/scala/fs2/pipe2.scala
core/src/main/scala/fs2/util/Task.scala
core/src/test/scala/fs2/BracketBug.scala
core/src/test/scala/fs2/ConcurrentSpec.scala
core/src/test/scala/fs2/MemorySanityChecks.scala
core/src/test/scala/fs2/Pipe2Spec.scala
core/src/test/scala/fs2/ResourceSafetySpec.scala
core/src/test/scala/fs2/StreamSpec.scala
core/src/test/scala/fs2/TestUtil.scala
core/src/test/scala/fs2/async/SemaphoreSpec.scala
core/src/test/scala/fs2/async/SignalSpec.scala
core/src/test/scala/fs2/time/TimeSpec.scala
docs/ReadmeExample.md
docs/guide.md
docs/src/ReadmeExample.md
docs/src/guide.md
io/src/test/scala/fs2/io/tcp/SocketSpec.scala

- Renamed the existing methods to `runXyzFree`
- Created new methods of the form `runXyz` which alias `runXyzFree andThen run`
- Fixed an unrelated bug in `Task.apply`, where the value was being evaluated on the calling thread instead of via the strategy

Changes stream.runXyz methods so that they return effectful values instead of free interpretations

---

sbt

The current `./sbt` shell script attempts to download artifacts from a no longer existent artifactory:
```
Downloading sbt launcher 0.13.11:
From  http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.11/sbt-launch.jar
To  ./.lib/0.13.11/sbt-launch.jar
Download failed. Obtain the jar manually and place it at ./.lib/0.13.11/sbt-launch.jar
```
This updates the `./sbt` to the latest from https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt

Updates the sbt shell script

---

io/src/main/scala/fs2/io/file/FileHandle.scala
io/src/main/scala/fs2/io/file/package.scala
io/src/main/scala/fs2/io/file/pulls.scala

- Create Pull for FileHandle from either paths or channels
- Move Pull constructors to fs2.io.pulls
- Move FileHandle constructors to fs2.io.FileHandle companion
- Make readAllFromFileHandle/writeAllToFileHandle visible
This separates the extra page for the docs, as it isn't finished, and it might be nice if this went into 0.9.0-M2.

Update file NIO support

---

core/src/main/scala/fs2/Async.scala
core/src/main/scala/fs2/time/time.scala
core/src/main/scala/fs2/util/Task.scala
core/src/test/scala/fs2/time/TimeSpec.scala
docs/guide.md
docs/src/guide.md

- Changed `Async.Run` to be asynchronous
- Guarded submission of work to the strategy with a semaphore to prevent unbounded growth of thread pool tasks
See [Gitter](https://gitter.im/functional-streams-for-scala/fs2?at=574301fbd3f431720bb2e335) for discussion.

Fixed deadlock in awakeEvery due to synchronous effect evaluation

---

core/src/main/scala/fs2/Pull.scala
core/src/main/scala/fs2/Pulls.scala
core/src/main/scala/fs2/StreamDerived.scala
core/src/main/scala/fs2/pipe.scala
core/src/main/scala/fs2/pipe2.scala
core/src/main/scala/fs2/text.scala
docs/guide.md
docs/src/guide.md
io/src/main/scala/fs2/io/file/package.scala

I think `close` is clearer for folks learning the library:
- `close` helps separate the act of closing a pull from the act of running a stream
- symmetrical with `open` on `Stream`

Renamed pull.run to pull.close

---

core/src/main/scala/fs2/util/Free.scala

Remove unused `suspend` method left over from moving delay/suspend to `Effect`.

Remove unused suspend method in Free monad instance

---

core/src/main/scala/fs2/Async.scala
core/src/main/scala/fs2/async/mutable/Signal.scala

@mpilquist like we have discussed earlier. This changes signature of `modify` to be almost the same like `modify` in `Async`. Furthermore this simplifies signal's state and removes the `Semaphore` from the implementation.

Changed signature of SIgnal.modify

---

core/src/main/scala/fs2/Async.scala
core/src/main/scala/fs2/async/async.scala
core/src/main/scala/fs2/async/mutable/Topic.scala
core/src/test/scala/fs2/async/TopicSpec.scala

@mpilquist @pchiusano This is a very rough idea on the topic. Can you please comment on Api? In contrast of 0.8 this:
- Allows to set limit per subscriber to stop (block) any publish if that subscriber is behind that amount of messages
- Honors chunking of input stream
- Subscriber always receive single value, even when there was no value yet published. 
- There is a variant of `subscribe` with approximate value of queue size, that eventually may be used to fine-tune dequeue operations based on size of the queue of that subscriber. 
I don't think so there will be need for WriterTopic as in 0.8. I think we should be able to get Writer topic behaviour with this defined as Topic[F,(W,O)]
I am also thinking on ways how to simplify implementation, which is now WIP. I am thinking on …

Initial implementation of Topic

---

core/src/main/scala/fs2/async/channel.scala
core/src/test/scala/fs2/async/ChannelSpec.scala

I don't love this implementation but it works... Review by @pchiusano.

Fixed bug in channel.observe where observing with a finite sink caused hangs

---

core/src/main/scala/fs2/Async.scala
docs/guide.md

When `Strategy` was moved from `fs2.util`, the package name in this hint wasn't changed.

Fix @implicitNotFound hint about required Strategy

---

build.sbt
core/src/main/scala/fs2/Chunk.scala
core/src/main/scala/fs2/async/mutable/Queue.scala
core/src/main/scala/fs2/async/mutable/Topic.scala
core/src/test/scala/fs2/ChunkSpec.scala
io/src/main/scala/fs2/io/tcp/Socket.scala
io/src/main/scala/fs2/io/tcp/tcp.scala
io/src/main/scala/fs2/io/udp/AsynchronousSocketGroup.scala
io/src/main/scala/fs2/io/udp/udp.scala
io/src/test/scala/fs2/io/tcp/SocketSpec.scala
io/src/test/scala/fs2/io/udp/UdpSpec.scala

- Optimized udp implementation
- Changed tcp to work on `Stream[F,Byte]`, and utilizing the underlying
chunk structure
- Changed chunk constructors to return `Chunk[X]` to prevent type
inference issues
Review by @pchlupacek

Miscellaneous cleanup and consistency in IO package

---

io/src/main/scala/fs2/io/tcp/Socket.scala
io/src/main/scala/fs2/io/tcp/tcp.scala
io/src/test/scala/fs2/io/TestUtil.scala
io/src/test/scala/fs2/io/tcp/SocketSpec.scala

...which provides the address of the bound server socket, allowing use of ephemeral port numbers in servers.
This might help with Travis failures if the root cause of them is that port 9999 is in use.

Added io.tcp.serverWithLocalAddress 

---

core/src/main/scala/fs2/PullDerived.scala
core/src/main/scala/fs2/Stream.scala
core/src/main/scala/fs2/StreamCore.scala
core/src/main/scala/fs2/async/mutable/Queue.scala
core/src/main/scala/fs2/async/mutable/Signal.scala
core/src/main/scala/fs2/concurrent.scala
core/src/test/scala/fs2/MemorySanityChecks.scala
core/src/test/scala/fs2/async/TopicSpec.scala
io/src/main/scala/fs2/io/file/pulls.scala

Note that we have a similar memory leak as the one in signal in queue.dequeue
Review by @pchiusano & @pchlupacek

Fixes memory leak in concurrent.join and signal.discrete

---

io/src/test/scala/fs2/io/tcp/SocketSpec.scala

Fixes tcp tests failing on Windows
Binding to the wildcard address binds to localhost on *Nix, but fails on Windows.

use InetSocketAddress with explicit localhost

---

core/src/main/scala/fs2/async/immutable/Signal.scala
core/src/main/scala/fs2/async/mutable/Queue.scala
core/src/main/scala/fs2/async/mutable/Signal.scala
core/src/main/scala/fs2/async/mutable/Topic.scala

This PR adds `imap`/`map` on `fs2.async.mutable.{Queue,Signal,Topic}`. The follow up would be to define the corresponding `Invariant` instances in `fs2-cats`/`fs2-scalaz`.
I'm not sure if I should test that with the invariant laws, bringing the ones from cats with an additional `% "test"` dep, or if you consider the type checker to be enough in that case...
https://github.com/functional-streams-for-scala/fs2-cats/pull/6

Add Queue.imap, Topic.imap and Signal.map

---

core/src/main/scala/fs2/Async.scala
core/src/main/scala/fs2/StreamCore.scala
core/src/main/scala/fs2/async/channel.scala
core/src/main/scala/fs2/async/mutable/Queue.scala
core/src/main/scala/fs2/async/mutable/Semaphore.scala
core/src/main/scala/fs2/async/mutable/Signal.scala
core/src/main/scala/fs2/async/mutable/Topic.scala
core/src/main/scala/fs2/concurrent.scala
core/src/main/scala/fs2/task.scala
core/src/test/scala/fs2/ResourceSafetySpec.scala
core/src/test/scala/fs2/TestUtil.scala
core/src/test/scala/fs2/async/ChannelSpec.scala

Sometimes client code needs to use refs (e.g., when the data types in the async package don't fit a given problem). This can be annoying to work with though, because `Ref[A]` is defined as a type member on the `Async` instance. This requires that folks summon the `Async[F]` instance and then thread it through all usages, or else be at the mercy of scalac's path equality, which often fails.
This PR moves `Ref[A]` to the `Async` companion, and adds the effect type as a parameter, making usage much simpler.
Merge after #670.

Ref usability

---

core/src/main/scala/fs2/Async.scala
core/src/main/scala/fs2/Pulls.scala
core/src/main/scala/fs2/Scope.scala
core/src/main/scala/fs2/StreamCore.scala
core/src/main/scala/fs2/StreamDerived.scala
core/src/main/scala/fs2/async/channel.scala
core/src/main/scala/fs2/async/mutable/Queue.scala
core/src/main/scala/fs2/async/mutable/Semaphore.scala
core/src/main/scala/fs2/async/mutable/Signal.scala
core/src/main/scala/fs2/async/mutable/Topic.scala
core/src/main/scala/fs2/concurrent.scala
core/src/main/scala/fs2/pipe.scala
core/src/main/scala/fs2/task.scala
core/src/main/scala/fs2/text.scala
core/src/main/scala/fs2/time/time.scala
core/src/main/scala/fs2/util/Eq.scala
core/src/main/scala/fs2/util/Free.scala
core/src/main/scala/fs2/util/Functor.scala
core/src/main/scala/fs2/util/Monad.scala
core/src/main/scala/fs2/util/syntax.scala
io/src/main/scala/fs2/io/file/FileHandle.scala
io/src/main/scala/fs2/io/file/pulls.scala
io/src/main/scala/fs2/io/tcp/Socket.scala
io/src/main/scala/fs2/io/tcp/tcp.scala
io/src/main/scala/fs2/io/udp/udp.scala

I renamed `bind` to `flatMap` in order to pick up for-comp syntax. We could have `flatMap` as an alias for `bind` like scalaz does, but I think a single way to do things is better than having folks pick the name they prefer in each case.
Goal of this PR is not to compete with scalaz/cats but rather to cleanup the fs2 internals, where the use of prefix syntax gets pretty complex.
When I started this PR, I used simulacrum. I ended up removing the simulacrum dependency in order to define the syntax in AnyVal classes so that there's no runtime overhead.
Merge after #673

Added infix syntax for fs2.util typeclasses

---

build.sbt
src/main/scala/scalaz/stream/Process.scala

- Bump scalaz to 7.1.8 with a build for 2.12.0-M5
- Add some `asInstanceOf` calls and type ascriptions to fix
compilation errors.

Update scalaz-stream 0.8 to support scala 2.12.0-M5

---

build.sbt
src/main/scala/scalaz/stream/Process.scala

- Bump scalaz to 7.2.4 with a build for 2.12.0-M5
- Add some `asInstanceOf` calls and type ascriptions to fix
compilation errors.

Update scalaz-stream 0.8a to support scala 2.12.0-M5

---

core/src/main/scala/fs2/StreamDerived.scala
core/src/main/scala/fs2/util/Free.scala
core/src/test/scala/fs2/ResourceSafetySpec.scala

The performance optimzation eagerly applied `Bind(Pure(x), f)`
while stepping. IIRC, this optimization gave ~20% performance
improvement in some benchmarks. Unfortunately, it is unprincipled. More
specifically, the optimization assumed that `f` is pure. However,
`Free.suspend` (and `Stream.suspend`) are implemented as
`pure(()).flatMap(_ => s)`, so we either need to introduce `suspend` as
a new primitive in `Free` (and `Stream` and maybe other places) or we
need to avoid the assumption that `f` is pure.
Note that the optimization allowed us to use `Either[Throwable,?]` in
the evaluation of pure streams in a stack safe way. Removal of the
optimization requires the effect type to provide its own stack safety.
For now, I've changed pure streams to use `Task` again, though I'm
considering …

Removed a performance optimization in Free#step.

---

benchmark/src/main/scala/fs2/benchmark/StreamBenchmark.scala
core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/shared/src/main/scala/fs2/Handle.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/pipe.scala
core/shared/src/main/scala/fs2/pipe2.scala
docs/guide.md
docs/src/guide.md

As a result of the recent work on API usability, `Handle` is more of a Real Type in the API. As a result, we can move all of the methods from `Pull` that returned functions of `Handle => Pull` directly on to the handle class.
This has a number of advantages:
- there's only one way to invoke these functions (e.g., `h.receive { ... }`) instead of two (e.g., `Pull.receive { ... }`)
- there's only one place to define these functions. Previously, we defined everything on `Pull` (mostly) but then added forwarders from `Handle` for the really common functions
- the functions are easier to find for folks using IDEs or browsing ScalaDoc
- the API footprint of the `Pull` object is much smaller
- we generally get better type inference
- arguably, it's more intuitive that methods on `Pull` return …

Moved methods from Pull => Handle that returned a Handle => Pull

---

io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/main/scala/fs2/io/file/file.scala
io/src/main/scala/fs2/io/package.scala

InputStream/OutputStream support is not exclusively for files, so it should be
in the fs2.io package. Because these calls are blocking, adds a variant that
uses the backing `fs2.Async` instance for asynchronous behavior.
@pchlupacek Comments welcome.

Move InputStream/OutputStream from fs2.io.file to fs2.io, add async variants

---

core/jvm/src/main/scala/fs2/hash/hash.scala
core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/shared/src/main/scala/fs2/Stream.scala
docs/guide.md
docs/migration-guide.md
docs/src/guide.md

This avoids any temptation of using `onComplete` for resource cleanup. Note the slight behavior change in the `hash` module -- old implementation erroneously masked errors in the stream.

Removed onComplete from Stream

---

core/shared/src/main/scala/fs2/util/Effect.scala
core/shared/src/main/scala/fs2/util/Suspendable.scala
docs/guide.md
docs/src/guide.md
io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/main/scala/fs2/io/file/FileHandle.scala
io/src/main/scala/fs2/io/file/file.scala
io/src/main/scala/fs2/io/file/pulls.scala
io/src/main/scala/fs2/io/package.scala

This PR moves `suspend` and `delay` from the `Effect` type class to a
new `Suspendable` type class. There are two motivations for doing this:
- Exposing `unsafeRunAsync` to any function that requires `suspend`
or `delay` gives up a lot of parametricity.
- Some type constructors have `Suspendable` instances but do not
support value extraction. This came up in the [port of Doobie to
FS2](https://github.com/tpolecat/doobie/pull/323#issuecomment-239822666).
This [came up on Gitter a while back as
well](http://www.gitterforum.com/discussion/scalaz-scalaz-stream?page=143).
/cc @tpolecat @guersam

Introduced Suspendable type class

---

core/jvm/src/test/scala/fs2/PipeSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/pipe.scala

Both `distinctConsecutive` and `distinctConsecutiveBy` use natural equality instead of relying on type class based equality. We can add type class variants in fs2-cats and fs2-scalaz by delegating to `filterBy2`. I don't love the name `filterBy2` but I don't have any other suggestions I like better -- e.g. `filterSliding2`, `filterWithLast` -- so I stuck with the name from 0.8.
The implementation of `filterBy2` is optimized for chunks where most elements are distinct. Specifically, it attempts to preserve the chunk structure if possible and only if not does it build a new filtered chunk.

Added distinctConsecutive and various related pipes

---

core/jvm/src/main/scala/fs2/compress.scala
core/jvm/src/main/scala/fs2/hash/hash.scala
core/jvm/src/test/scala/fs2/ResourceSafetySpec.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Handle.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/StreamCore.scala
core/shared/src/main/scala/fs2/pipe.scala
core/shared/src/main/scala/fs2/pipe2.scala
core/shared/src/main/scala/fs2/util/Free.scala
core/shared/src/test/scala/fs2/Fs2Spec.scala
core/shared/src/test/scala/fs2/TextSpec.scala
core/shared/src/test/scala/fs2/time/TimeSpec.scala
docs/guide.md
docs/src/guide.md

This PR introduces the `NonEmptyChunk` type and changes `step` and `stepAsync` to return `NonEmptyChunk` instead of `Chunk`. Removed the non-empty variants of `await` and `receive` since this PR makes them redundant.
Note that folks can't pattern match on a subtype of `Chunk` now but that's okay -- instead, they can call `c.toBytes` to unify the code that works on the underlying array.
Fixes #708 
@pchiusano Sorry for the delay on this one. Busy week. ;)

Introduced NonEmptyChunk

---

src/main/scala/scalaz/stream/async/mutable/Queue.scala
src/test/scala/scalaz/stream/QueueSpec.scala

This should fix #685.  Basically it defers the actual enqueue until there is room in the queue, whereas before it enqueued immediately even if over the bound and delayed the ACK.  This is very similar to the series/0.9 design.

Delay bounded enqueue until there is space

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Scope.scala
core/shared/src/main/scala/fs2/StreamCore.scala
core/shared/src/main/scala/fs2/util/Free.scala

Changed the way "bound" cases are encoded in both `Free` and
`StreamCore`. Rather than passing only the bound cases via a trait with
a single universally quantified method, all cases of the fold are passed
in as a trait. This results in significantly less runtime allocations,
as each call to `fold` was allocating a bound instance anyway but now we
can avoid some anonymous function allocations and some Left/Right
allocations.
In a fairly non-scientific test, these changes resulted in a 7%
performance increase for me (aka, I ran the test suite a few times and
measured how long the last run took).
This encoding is more verbose due to having to specify the type
signatures of the various abstract methods representing each case, but
the benefits to both performance and readability outweigh the …

Improved performance and readability of GADT encoding

---

build.sbt
core/jvm/src/test/scala/fs2/PipeSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/async/immutable/Signal.scala
core/shared/src/main/scala/fs2/async/mutable/Queue.scala
core/shared/src/main/scala/fs2/async/mutable/Signal.scala
core/shared/src/main/scala/fs2/async/mutable/Topic.scala
core/shared/src/main/scala/fs2/pipe.scala
project/plugins.sbt

- Enabled sbt-doctest
- Minor ScalaDoc consistency changes
- Removed `pipe.changes` and renamed `distinctConsecutive` and
`distinctConsecutiveBy` to `changes` and `changesBy`
- Removed `Signal#changes` in favor of calling `discrete.changes.map(_
=> ())`. Rationale is that a common use case is `s.discrete.changes` (without the map to unit) and that's confusing compared to `s.changes`.
Will merge tomorrow if there are no objections by then.

ScalaDoc updates and minor API adjustments

---

core/jvm/src/test/scala/fs2/async/QueueSpec.scala
core/shared/src/main/scala/fs2/async/mutable/Queue.scala

Adds `dequeueAvailable` which dequeues all available values from the queue.
Alters the queue state from containing `Async.Ref[F,A]` to `Either[Async.Ref[F,A], Async.Ref[F,Vector[A]]`, depending on whether the waiter is looking for single, or all queued values.

Add dequeueAvailable and supporting code.

---

io/src/main/scala/fs2/io/file/file.scala
io/src/main/scala/fs2/io/file/pulls.scala

Also fixes the signature of fromPathAsync to only require a single
implicit parameter of type Async.

Add ExecutorService parameter to AsynchronousFileChannel.open call.

---

core/shared/src/main/scala/fs2/pipe.scala

Scaladoc example for the `zipWithScan1` has been copy-pasted from `zipWithScan`.
I ran the command
```scala
Stream("uno", "dos", "tres", "cuatro").zipWithScan1(0)(_ + _.length).toList
```
in the REPL and pasted correct `res0`

Fix scaladoc example for the zipWithScan1

---

benchmark/src/main/scala/fs2/benchmark/StreamBenchmark.scala
core/shared/src/main/scala/fs2/Stream.scala

runLog builds its result by repeatedly appending to a `Vector`.  For large streams, better performance is possible using a `VectorBuilder`, at some cost to smaller streams.  The crossover point is not clear from [initial benchmarks], but might be evaluated with a smarter choice of GenerateN.
[initial benchmarks]: https://gist.github.com/rossabaker/3e141683db87728824b254f3a281201b

Build runLog result with a VectorBuilder

---

core/jvm/src/test/scala/fs2/TaskSpec.scala
core/shared/src/main/scala/fs2/Task.scala

As per comments in `fs2.Task.ref` the nonce should be updated with every successful set or modify, up till now for set the nonce was updated only in case of the first set, this PR addresses this issue. 
Added a test that demonstrates the case in which this would be an issue. This would also affect modify of the ref in case there was a concurrent set on it.

Task Ref now increments nonce with every set

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/test/scala/fs2/ChunkSpec.scala

Critical motivating example: `ByteVectorChunk`.  Without the ability to write this kind of `Chunk`, fs2 cannot be easily used for high-performance IO, simply because it will lack the ability to operate on direct `ByteBuffer` instances (via scodec's `ByteVector`).  This is a pretty big deal for frameworks like http4s.
Now, `Chunk` is not sealed (good!), but `Chunk.concat` has a fairly significant amount of hard-coded assumptions about the type of specialization which is possible.  Specifically, it's assuming that the `Chunk.*` implementations are the _only_ specialized chunks that will ever be useful, with all other unforeseen `Chunk` subtypes falling more into the camp of `Chunk.indexedSeq`.  This assumption stems from the fact that it has a hard-coded set of cases that it checks (very …

Fixed Chunk.concat to not smash custom chunks

---

core/shared/src/test/scala/fs2/TextSpec.scala

Looks like a porting bug
https://github.com/functional-streams-for-scala/fs2/commit
/97ad8d6f0b9e98f7fc14b7304b0f5c6b69d4e693#diff-542dd3ea6873dc327e3c7395d4fa9400R52
https://github.com/scalaz/scalaz-stream/blob/series/0.8/src/test/scala/scalaz/stream/Utf8DecodeSpec.scala#L57-L60

Fix a bug in test code

---

core/shared/src/main/scala/fs2/Stream.scala

This is partially in response to #760. The right identity monad law uses a weaker notion of equality, since `s flatMap emit` produces singleton chunks. _I think the other laws are still good with 'full equality' but would appreciate if others would think about whether this is true and raise any counterexamples._
Also added a note about how `map` can differ from the monad-derived map, in particular for exceptions in pure code.

Updated laws with clarifications

---

benchmark/src/main/scala/fs2/benchmark/FreeBenchmark.scala
core/shared/src/main/scala/fs2/util/Free.scala

This PR improves performance of Free by eagerly applying `Bind(Pure(a), f)` patterns in `Free#step`. We used to do this but it had the unfortunate side effect of evaluating suspends, because suspend is (still) implemented as `pure(()) >> fa`. This PR takes a conservative approach to fixing this issue by introducing a new flag on the `Pure` constructor, indicating whether or not eager evaluation is supported. `Free.pure` sets the flag to true whereas `Free.suspend` sets the flag to false.
The Free benchmarks show 18% - 42% increase:
a0aef44d45e76ebfe6b24aee3fa71664b7bbca0e (head of series/1.0)
```
[info] Benchmark                      Mode  Cnt   Score   Error  Units
[info] FreeBenchmark.nestedFlatMaps  thrpt   10  11.023 ± 1.311  ops/s
[info] FreeBenchmark.nestedMaps      thrpt   10 …
```

Minor performance improvement in Free

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/StreamCore.scala

There's a small performance improvement as a result but nothing major. There are less allocations so perhaps less GC pressure.
Before:
```
[info] Benchmark                                  Mode  Cnt    Score    Error  Units
[info] StreamBenchmark.awaitPull_256             thrpt   20  170.066 ±  5.208  ops/s
[info] StreamBenchmark.eval_102400               thrpt   20    1.450 ±  0.025  ops/s
[info] StreamBenchmark.leftAssocConcat_102400    thrpt   20    4.836 ±  0.228  ops/s
[info] StreamBenchmark.leftAssocFlatMap_102400   thrpt   20   12.296 ±  0.660  ops/s
[info] StreamBenchmark.rightAssocConcat_102400   thrpt   20    5.095 ±  0.303  ops/s
[info] StreamBenchmark.rightAssocFlatMap_102400  thrpt   20   12.748 ±  0.482  ops/s
[info] StreamBenchmark.runLog_102400             thrpt   20 …
```

Reduced allocations in StreamCore#step by using subtype polymorphism instead of a catamorphism

---

benchmark/src/main/scala/fs2/benchmark/CatenableBenchmark.scala
core/shared/src/main/scala/fs2/StreamCore.scala
core/shared/src/main/scala/fs2/util/Catenable.scala

This PR drastically improves constant factor performance of `Catenable` in certain usage patterns. API is changed a little bit:
- `push` was renamed `cons`
- `::` was renamed to `+:`
- `:+`/`snoc` was added
- `toStream` replaced with `toList`
- `foldLeft` and `foreach` added
- fixed stack safety bug in `uncons` and `fromSeq` -- `reduceRight` is *not* stack safe so the input is now reversed
Of particular note is the fact that singleton catenable construction was only about 1.5x as fast as creating a singleton vector, and small catenable construction was a bit slower than small vector creation.
Please excuse the while loops, but this is performance sensitive code so :shrug:.
8e20c6f1305ada0f50ed441f706228d1b5133f93 (before the changes in this PR)
```
[info] Benchmark …
```

Stack safety and constant factor improvements of Catenable

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Stream.scala

Allows Discarding A Stream Value for Another.
Refs #800 
I am uncertain where you are at in preparing for 0.9.3, this was just a cherry pick of the commit in case you would like to incorporate it.

Added >> Method to Stream for 0.9

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Stream.scala

Allows Discarding A Stream Value for Another.
Closes #800

Added >> Method to Stream

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Stream.scala

Hi,
I was asking on FS2 gitter for a way how to create a stream from a resource that has sth similar to `hasNext` like in iterator or `next` like in `ResultSet` from JDBC but I wanted to emit multiple values at once if there are ready to be published.
The solution could be to use unfold, but it can only publish a single value. 
@edmundnoble suggested I could easily write function that would publish Seq and submit a MR so here it is.
Sorry if I'm doing sth wrong but this is my first PR on github.

Added unfoldSeq and unfoldSeqEval

---

core/jvm/src/test/scala/fs2/ResourceSafetySpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/StreamCore.scala

I was looking into clarifying the docs on `uncons` and `uncons1` to say that they should be used in conjunction with `Stream.scope` (see #797) and noticed what I'd say is a problem - if you use `uncons` but don't have a surrounding `scope` call or `Pull` (which uses `scope`), you can have a finalizer not run. This test used to fail:
```Scala
"early termination of uncons" in {
var n = 0
Stream(1,2,3).onFinalize(Task.delay(n = 1)).uncons.run.unsafeRun
n shouldBe 1
}
```
That test is now fixed, by adding a call to `scope` in `runFold`, but the note about using `scope` in conjunction with `uncons` still applies if you want prompt finalization.
Sorry @jedesah but my docs kind of clobber some of your work in #797. I felt like the docs were trying to cover too many things (like the fact that if …

Fix issue with use of "root" `uncons` / `uncons1` and clarify docs

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/concurrent.scala
io/src/main/scala/fs2/io/file/FileHandle.scala
io/src/main/scala/fs2/io/file/file.scala
io/src/main/scala/fs2/io/file/pulls.scala

Fixes #772.
If we're good with this overall approach, TCP/UDP sockets should get a similar treatment. Specifically, we should *not* expose a `close` method on `FileHandle`/`Socket`/etc. and instead, return a `Cancellable[F,Resource]` from pulls.

Changed io.file.pulls API to return cancellable file handles

---

docs/guide.md
docs/src/guide.md

It looks like this line was missed after 'awaitLimit' was moved onto Handle in functional-streams-for-scala/fs2#701.

Update mention of 'Pull.awaitLimit'

---

io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/test/scala/fs2/io/JavaInputOutputStreamSpec.scala

This fixed `fs2.io.toInputStream` so that [InputStream#read()](https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#read()) only returns values of 0 to 255 and -1 for signalling the end.

convert bytes to 0-255 Int for InputStream#read()

---

core/jvm/src/test/scala/fs2/PipeSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/pipe.scala

Adds a `scanF` pipe.  
For a `Stream[F, I]`, this has the signature `scan(z: O)(f: (O, I) => F[O]): Stream[F, I]`.
This allows scanning over a stream with a function which returns a Task.

Add scanF pipe

---

README.md

This adds [fs2-reactive-streams](https://github.com/zainab-ali/fs2-reactive-streams) to the list of projects using fs2.

Add fs2-reactive-streams to list of projects

---

core/jvm/src/main/scala/fs2/compress.scala

Reading the scaladoc, it is a bit irritating reading the word *compression* in the *inflate* aka *decompression* function. I suppose, this was introduced by copy-pasting.
---
> This is CONSISTENCY!
>
> -- Leonidas

clarifies nowrap argument for inflate / decompression

---

core/shared/src/main/scala/fs2/ScopedFuture.scala
core/shared/src/main/scala/fs2/StreamCore.scala
core/shared/src/main/scala/fs2/Task.scala
core/shared/src/main/scala/fs2/async/mutable/Queue.scala
core/shared/src/main/scala/fs2/async/mutable/Semaphore.scala
core/shared/src/main/scala/fs2/async/mutable/Signal.scala
core/shared/src/main/scala/fs2/async/mutable/Topic.scala
core/shared/src/main/scala/fs2/util/Concurrent.scala
core/shared/src/test/scala/fs2/util/ConcurrentSpec.scala
io/src/test/scala/fs2/io/tcp/SocketSpec.scala

Review by @pchlupacek 
Note that I did not thread-shift invocation of the callback in order to be consistent with `TrySet`. I tried thread-shifting both `TrySet` callback invocation and `Set` callback invocation, but that caused the `publish synchronous` test to fail in `TopicSpec`. Maybe you can investigate?

Fixed #782

---

core/jvm/src/test/scala/fs2/ConcurrentSpec.scala
core/shared/src/main/scala/fs2/concurrent.scala

@mpilquist I think this is not that critical fix, but perhaps we shall make 0.9.6? Not sure if anything else is on table for 0.9 branch
Shall I create another PR for 1.0.0 series?

Fixes Outer Stream in concurrent.join to fail join

---

core/jvm/src/main/scala/fs2/compress.scala
core/jvm/src/test/scala/fs2/CompressSpec.scala

The current behavior of `fs2.compress.deflate` is to skip deflation on empty streams. I would argue that this behavior is incorrect given the following example:
```scala
import java.io.ByteArrayOutputStream
import java.util.zip.{Deflater, DeflaterOutputStream}
val byteArrayStream = new ByteArrayOutputStream()
val deflater = new Deflater(Deflater.DEFAULT_COMPRESSION, true)
val deflaterStream = new DeflaterOutputStream(byteArrayStream, deflater)
deflaterStream.write(Array[Byte]())
deflaterStream.close()
byteArrayStream.toByteArray()
// => Array(3, 0)
```
These changes fix the behavior by making sure that `_deflate_finish` is called regardless of whether the stream was empty or not.

Make sure empty streams get deflated properly

---

core/jvm/src/test/scala/fs2/Pipe2Spec.scala
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/async/mutable/Queue.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/Free.scala
core/shared/src/test/scala/fs2/ErrorHandlingSpec.scala

Tests are passing except for this one in `StreamSpec`:
```Scala
"onError (1)" in {
pending // fails when exception thrown from pure code - e.g., s.map(_ => throw Err)
forAll { (s: PureStream[Int], f: Failure) =>
val s2 = s.get ++ f.get
runLog(s2.onError(_ => Stream.empty)) shouldBe runLog(s.get)
}
}
```

Switch to simpler encoding of `Free`, make `ViewL` a value class

---

io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/main/scala/fs2/io/io.scala
io/src/test/scala/fs2/io/IoSpec.scala

The existing `readInputStream` recycles the input buffer.  This is akin to the behavior of scalaz-stream's `unsafeChunkR`, except it is not advertised as unsafe.
This passes the input buffer into `readInputStreamGeneric` in `F`.  `readInputStream` and `readInputStreamAsync` create a new array on each invocation, while `unsafeReadInputStream` and `unsafeReadInputStreamAsync` behave as the previous versions.

Recycle input buffer only in unsafeReadInputStream{,Async}

---

README.md

Just seen this PR: https://github.com/functional-streams-for-scala/fs2/pull/882/files adding the fs2-kafka library and reminded me of adding fs2-rabbit.

Link to fs2-rabbit library added.

---

core/jvm/src/test/scala/fs2/StreamPerformanceSpec.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Segment.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/SegmentSpec.scala
io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/main/scala/fs2/io/file/FileHandle.scala
io/src/test/scala/fs2/io/JavaInputOutputStreamSpec.scala

- Improved performance of Segment#uncons1 when working with array backed chunks
- Improved performance of Segment#foldRightLazy
- Restored ability to have array backed chunks with offsets and changed `strict.splitAt` to take advantage of this, resulting in O(1) `splitAt`, `take`, and `drop`.
Quick review by @pchiusano.

Minor performance improvements

---

core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/FreeC.scala

The cached `ViewL` structure in `FreeC` leaks memory (though I don't
understand why exactly). Replacing the cached hard reference with a soft
reference helps, but heap usage grows until GC decides to clear soft
references. Replacing with a weak reference fixes that but it's not
clear how often we get a cache hit with a weak reference. Further, the
soft and weak reference versions have a performance impact on the common
case where stream evaluation does not benefit from ViewL caching --
about 5% in my tests.
To see the leak, run the `ConstantEvalSanityTest` with caching enabled.
In this PR, I've disabled caching completely. We can always add it back
if we determine why it leaks. Before adding it back, I'd like to have
some tests that demonstrate the cost of caching pays off in common use …

Fixed memory leak in FreeC

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Segment.scala
core/shared/src/test/scala/fs2/SegmentSpec.scala
scodec/shared/src/main/scala/fs2/interop/scodec/ByteVectorChunk.scala

Like a hypothetical `flatMap` but `f` returns a `Chunk[O2]` instead of `Segment[O2,R]`, allowing for a fused implementation with same performance as `map`.

Added Segment#mapConcat

---

core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/jvm/src/test/scala/fs2/PipeSpec.scala
core/shared/src/main/scala/fs2/Pipe.scala
core/shared/src/main/scala/fs2/Pipe2.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

This PR fixes a memory leak in `Stream#flatMap` when defining a recursive stream. Consider:
```scala
def loop: Stream[IO,Unit] = Stream(()).covary[IO].flatMap(_ => loop)
loop.run.unsafeRunSync
```
Before this PR, running this program would fill the heap within seconds. This was due to this code in `Stream#flatMap`:
```scala
hd.map(f).foldRightLazy(Stream.fromFreeC(tl).flatMap(f))(_ ++ _).get
```
Each element is mapped to a `Stream[F,O2]` and the resulting `Segment[Stream[F,O2],Unit]` is then lazily folded in to a `Stream[F,O2]` via the `++` operator.
Recursive streams of the form of `loop` emit a single element at a time, but the fold turns that in to `f(hd(0)) ++ Stream.empty.flatMap(f)`. This is equivalent to `f(hd(0))` but pushes the concatenation of `Stream.empty.flatMap(f)` in to a …

Fixes memory leak in recursive streams

---

core/shared/src/main/scala/fs2/Scheduler.scala
core/shared/src/test/scala/fs2/RetrySpec.scala

Once the Scheduler rework is merged, I will do the (very small) changes required to adapt this branch to the new Scheduler mechanism, but apart from that, this is ready to receive feedback I think.
The `delays` test has consistently succeeded on my machine, but let me know if you think there are risks of flakiness.

Add `retry` combinators 

---

core/jvm/src/test/scala/fs2/ConcurrentlySpec.scala
core/jvm/src/test/scala/fs2/async/QueueSpec.scala
core/jvm/src/test/scala/fs2/async/SignalSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/async/async.scala
core/shared/src/main/scala/fs2/async/immutable/Signal.scala
docs/ReadmeExample.md
docs/guide.md
docs/migration-guide-0.10.md
docs/src/guide.md

Introduced `s.concurrently(t)` as a safe replacement for `s.mergeHaltR(t.drain)`. Removed `mergeHaltL` and `mergeHaltR`. Changed `hold` to be implemented with `concurrently`.
@pchlupacek This should cover everything from #911. /cc @SystemFw

Fixes #907

---

core/jvm/src/main/scala/fs2/compress.scala
core/jvm/src/test/scala/fs2/CompressSpec.scala

Without this, a deflated stream fails on second run because the deflater has been closed.  This is similar to the behavior in 0.10, where the pull is suspended.

[0.9] Suspend deflated streams so they are pure

---

core/jvm/src/test/scala/fs2/PipeSpec.scala
core/shared/src/main/scala/fs2/Stream.scala

Previously `scan` kept last known value until next one or the end of the stream.
Now it matches [Rx equivalent](http://rxmarbles.com/#scan)

More eager version of a scan: emits values immediately upon calculation

---

core/shared/src/main/scala/fs2/Segment.scala

I detected this issue when I was running old code that I ported from 0.9 to 0.10. I discovered that there is the real possibility of a null pointer exception in the `flatMap` method of `Segment`, see the backtrace here: http://lpaste.net/358781
This problem is related to https://github.com/functional-streams-for-scala/fs2/pull/922 where a null pointer exception was discovered and fixed in the `flatMapAccumulate` method, also of `Segment`.
I tested the fix with my code, and the problem has disappeared.
Take this fix with a grain of salt. It might be incorrect. I can't say I understand the segment stepper code very well. I followed the types and used common sense to create this solution.

fix for npe in segment's flatmap

---

core/shared/src/main/scala/fs2/Stream.scala

This doctest may help making the connection between using `cats` syntax for `Stream`s and making `syncInstance` implicit more obvious.

Add doctest making Stream.syncInstance implicit

---

core/jvm/src/main/scala/fs2/hash.scala

Make sure MessageDigest respects Chunk size and offset

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

This came up in a discussion with @tpolecat on Gitter today. Example use case is translating from `IO` to some free algebra that doesn't have an `Effect` instance via `translateSync` and then at the end of the program, translating back to `IO` via `translate`.
Prior to this PR, any `UnconsAsync` steps in the program (e.g., those arising from `unconsAsync`, `merge`) were replaced with an `Eval(F.raiseError(new IllegalStateException(...)))`. In this PR, I introduced a new `UnconsAsyncDeferred` constructor which acts as a sort of higher kinded `Coyoneda`. When calling `translate` later, any `UnconsAsyncDeferred` steps are rewritten to `UnconsAsync` steps using the captured `Effect` instance.
I have a more drastic idea on how to fix this, where we no longer capture the `Effect` instance on …

Fixed issue where translate after translateSync should restore any UnconsAsync steps

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Pipe.scala
core/shared/src/main/scala/fs2/Pipe2.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
docs/ReadmeExample.md
docs/guide.md
docs/src/guide.md

This is the more ambitious version of the fix for #948.
The `Algebra.UnconsAsync` case no longer captures the `Effect[F]` instance, which means we can have the standard definition of `Stream#translate`. However, running a stream now requires an `Effect[F]` instead of a `Sync[F]`. I provided an alternative for each run function that requires a `Sync[F]` but that fails if an `UnconsAsync` step is encountered.
Overall, the expressiveness of the library is not changed by this PR. Rather, we moved where `Effect` instances are required.
/cc @tpolecat

Changed UnconsAsync so that it does not capture Effect[F] instance, resulting in proper translate signature

---

core/shared/src/main/scala/fs2/async/Ref.scala

Make the constructor of Ref private. Fixes #951

---

core/shared/src/main/scala/fs2/Stream.scala

The implementation of `Stream#runSync` does not match its documentation. Given the background which introduced this method, I guess we have to rewrite it.

Fix Stream#runSync to use `Sync` instead of `Effect`

---

benchmark/src/main/scala/fs2/benchmark/StreamBenchmark.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Segment.scala

Fixes #958.
Before this fix:
```
[info] Benchmark                                   Mode  Cnt           Score   Error  Units
[info] StreamBenchmark.emitsThenFlatMap_1          avgt             2527.329          ns/op
[info] StreamBenchmark.emitsThenFlatMap_10         avgt            34048.764          ns/op
[info] StreamBenchmark.emitsThenFlatMap_100        avgt          1298487.894          ns/op
[info] StreamBenchmark.emitsThenFlatMap_1000       avgt         79365209.923          ns/op
[info] StreamBenchmark.emitsThenFlatMap_10000      avgt       6324507135.000          ns/op
```
After this fix:
```
[info] Benchmark                                   Mode  Cnt        Score   Error  Units
[info] StreamBenchmark.emitsThenFlatMap_1          avgt          2311.262          ns/op
[info] …
```

Fixed performance issue in Stream.flatMap exposed by streams like Stream.emits(...).flatMap(Stream(_))

---

core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

When a scope is closed, it should be unregistered from its parent scope
so that it is eligible for GC. This PR implements this by tracking
spawned scopes via a token based LinkedHashMap and upon scope closure,
removing the entry in the parent's map.
Fixes #962.

Fixed memory leak in scope management.

---

core/jvm/src/test/scala/fs2/MergeJoinSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
io/src/test/scala/fs2/io/tcp/SocketSpec.scala

Added test case showing that join/joinUnbounded release resources from outer stream too early

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

Scope#releaseResource only searched the local resources map for a
resource, so if the resource was in a spawn's map or a parent map, the
release was skipped. This masked a bug in the new join import/export
support, which treated explicit resource releases as forced releases,
skipping reference counting.

Fixed 2 bugs in scope management

---

core/jvm/src/main/scala/fs2/compress.scala
core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/jvm/src/test/scala/fs2/MergeJoinSpec.scala
core/jvm/src/test/scala/fs2/PipeSpec.scala
core/jvm/src/test/scala/fs2/ResourceSafetySpec.scala
core/jvm/src/test/scala/fs2/StreamPerformanceSpec.scala
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/FreeC.scala
core/shared/src/test/scala/fs2/CompilationTest.scala
core/shared/src/test/scala/fs2/ErrorHandlingSpec.scala
core/shared/src/test/scala/fs2/TestUtil.scala
docs/ReadmeExample.md
docs/guide.md
docs/src/guide.md
io/src/main/scala/fs2/io/tcp/Socket.scala
io/src/test/scala/fs2/io/udp/UdpSpec.scala

If you `import cats.implicits._`, the cats syntax for methods like `flatMap`, `*>`, and `handleErrorWith` overrides the methods from `Stream`. The cats versions of these methods don't support all the variance tricks that the FS2 equivalents support. Hence, users may need to use `covary` in more cases than they'd normally need to if they are importing cats syntax.
This exposed some inconsistencies with cats methods -- e.g., `onError` in cats means something different than `onError` in fs2, so I renamed `onError` to `handleErrorWith` to match the cats name. Similarly, I renamed `fail` to `raiseError` to match the cats name.
Note that the `Pull` API doesn't need the same variance tricks that `Stream` uses because (1) we don't create `Pull[Pure,O,R]` instances out of thin air (if we have one, …

Make Sync instances for Stream and Pull implicit

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Segment.scala

- Introduced a type for the trampoline (instead of passing a plain linked list around)
- Introduced an alias for the defer callback to clarify it's purpose
- Converted `stage` and `stage0` functions in to methods to avoid unneeded allocation and to make the signature clearer (as a result, types have to be specified on each subtype but I think the resulting code is easier to read)
Will merge later today if there are no objections.

Minor refactoring in Segment to make code easier to understand (no change in meaning)

---

core/shared/src/main/scala/fs2/Chunk.scala
io/src/main/scala/fs2/io/file/FileHandle.scala
io/src/main/scala/fs2/io/tcp/Socket.scala

Fixes #977.
Includes a series of optimizations:
- `Chunk#toArray` now simply uses a while loop instead of using the segment machinery to access each element (not sure why it ever did what it was doing...)
- `toArray` is overridden on each array backed chunk subtype using `.slice` operation
- `toByteBuffer` was added to `Chunk.Bytes` allowing a zero-copy view of the underlying array
@fiadliel could you take a look at this?

Performance improvements in Chunk#toArray

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
io/src/main/scala/fs2/io/io.scala
io/src/test/scala/fs2/io/IoSpec.scala

Fixes #971 
If you are interested in this being implemented. It used to be present in scalaz-stream, and is a useful piece of functionality. If there is a problem in this implementation I would like to know so I can avoid it.

Iterator Handling in IO Package

---

core/jvm/src/main/scala/fs2/ExitCode.scala
core/jvm/src/main/scala/fs2/StreamApp.scala
core/jvm/src/test/scala/fs2/StreamAppSpec.scala

This is a first attempt at a `StreamApp` in fs2. I've taken the one in http4s, tried to conform to the code style in fs2 and named it `fs2.StreamApp`. I've also added `fs2.ExitCode`. It could live in the same file as `StreamApp`, to keep the entire machinery contained in one file.
I have added the tests we had in http4s as well.
Closes #973

Add fs2.StreamApp from http4s

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Stream.scala

The PR builds off of #950 and implements `repartition` such that each segment in the underlying stream is scanned instead of unconsing single elements.
Note I had to change the repartition function to return a `Chunk` instead of a `Segment` but this is okay -- repartitioning a single element should not require an expansion in to an infinite segment.
@soumyarupsarkar -- please take a look. This uses the double layer scanning algorithm I attempted to describe in one of the reviews of #950.

Segmented repartition

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Stream.scala

This PR reintroduces the `repartition` combinator. This was originally added to scalaz-stream by @fthomas in #93

Reintroduce repartition

---

io/src/main/scala/fs2/io/file/FileHandle.scala
io/src/main/scala/fs2/io/file/pulls.scala

Fixed memory leak in readAllFromFileHandle due to use of for/yield

---

core/shared/src/main/scala/fs2/internal/Actor.scala

This would have saved me  a  _ton_ of time when I was first learning about Actor, so I think it's worth linking.
I do have a question though: the article explains how the state of the queue is correctly shared in the presence of concurrency, but what about the state that the handler mutates?
In other words, let's say two calls to `act` happen on 2 different threads, and the handler is mutating a variable `myVar` , how will the update to `myVar` from one call be propagated to the other thread? (also assume that any call to `!` is happening on another thread still).  `act` doesn't write to any `volatile` (or Atomic*) field after running `handler`, so I don't see where the memory barrier is.
There's a comment saying:
"Memory consistency guarantee: when each message is processed by the …

Add link to Actor docs

---

CONTRIBUTORS.md
build.sbt
core/jvm/src/test/scala/fs2/async/QueueSpec.scala
core/shared/src/main/scala/fs2/async/mutable/Queue.scala

`Queue#peek1` and `timedPeek1` (fixes #983).
I'm unsure about the semantics for `synchronous` (and consequently for `synchronousNoneTerminated`). If I understand correctly, that queue is (conceptually) always empty. That would suggest, that `peek1` should never finish. However, it is in fact possible (sometimes) to dequeue an element from such a queue. Thus, peek could also work. This seems more useful, so this is what this PR currently implements.

Queue#peek1 and timedPeek1

---

core/shared/src/main/scala/fs2/CompositeFailure.scala
core/shared/src/main/scala/fs2/Lease.scala
core/shared/src/main/scala/fs2/Pipe.scala
core/shared/src/main/scala/fs2/Pipe2.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Scope.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/Resource.scala
core/shared/src/main/scala/fs2/internal/RunFoldScope.scala
core/shared/src/main/scala/fs2/internal/Token.scala

Non-doc changes include:
- Moving `Lease` back to a type-level type since it's used by both `Scope` and `Resource`
- Changing `CompositeFailure` so that it always represents at least 2 exceptions
- Moving `Algebra.Token` to top level of `internal` package since it's used by `Resource` and `Scope`

Edited documentation of new scope/lease management

---

core/shared/src/main/scala/fs2/AsyncPull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/async/Ref.scala
core/shared/src/main/scala/fs2/async/async.scala
core/shared/src/main/scala/fs2/async/mutable/Queue.scala
core/shared/src/test/scala/fs2/async/RefSpec.scala

As per the title, it partially addresses #993 .
Note that the behaviour of all code that depends on Ref within fs2 has _not_ been changed, e.g. I haven't experimented with changing on what EC anything runs, or switching async to sync or anything like that.
This is a sheer refactor, that shouldn't affect the behaviour of the rest of fs2 at all. The semantics of Ref have slightly changed though (hopefully for the best), and the implementation should be a bit clearer without Throwable. 
The commits are self-contained if you prefer to look at them them individually.
Let me know what you think.

Remove Throwable from Ref

---

sbt

This is a copy pasta of the sbt script from https://github.com/paulp/sbt-extras/blob/77686b3dfa20a34270cc52377c8e37c3a461e484/sbt
It needs to be updated because if you don't already have the sbt version required installed, it attempts to install it from http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.0/sbt-launch.jar which returns a 404.
With the updated script it downloads from
http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.0/sbt-launch.jar

Updates to latest sbt launch script

---

core/shared/src/main/scala/fs2/Segment.scala

Includes:
* `Traverse` and `Monad` implicitly for any `Segment[A, Unit]`
* A function to create a `Monad[Segment[A, ?]]`

Add cats instances for segment

---

benchmark/src/main/scala/fs2/benchmark/ByteBufferChunkBenchmark.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/test/scala/fs2/ChunkProps.scala
core/shared/src/test/scala/fs2/ChunkSpec.scala

Optimization for streams sourced from and sunk to `ByteBuffer`s.  This avoids copying bytes on direct buffers, and the overhead of wrapping and unwrapping array-backed buffers.
Moves `.toByteBuffer` operation to `Chunk` with `Byte` evidence.
Brings back some properties for `Chunk`, and tests the new implementation.

Introduce Chunk.ByteBuffer

---

core/shared/src/main/scala/fs2/Stream.scala

Anything involving `unconsAsync` (e.g.` merge`, `interruptWith`) was affected, and the side-effecting behaviour resulted in weird things happening. As an example:
```scala
object Bug {
import fs2._
import cats._, implicits._
import cats.effect._
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration._
def stepAsync(s: Stream[IO, Unit]): Stream[IO, Unit] =
s.pull.unconsAsync.flatMap { ap =>
ap.pull.flatMap {
case None => Pull.done
case Some((hd, tl)) => Pull.output(hd) >> tl.pull.echo
}
}.stream
def stream = Scheduler[IO](2).flatMap { s =>
val a = s.sleep_[IO](1.seconds) ++ Stream.eval(IO(println("tick")))
//side effects
val broken = stepAsync(a)
def works = stepAsync(a)
broken ++ broken ++ broken ++ works ++ works ++ works ++ broken ++ broken ++ broken …
```

Fix a purity breakage in `unconsAsync`, resulting in wild behaviour

---

core/shared/src/main/scala/fs2/Segment.scala
core/shared/src/test/scala/fs2/SegmentSpec.scala

If a chunk was emitted whose size was exactly equal to the number of
remaining elements to take, the remainder was decremented to zero and
the take did not complete until the next element or chunk was emitted.
If another chunk was never emitted, the resulting segment hung.

Fixed #1039 - bug in Segment#take

---

build.sbt

Not a fundamental fix, but handy in repeated tests.

Workaround for #1046; use forked JVM in tests

---

io/src/test/scala/fs2/io/tcp/SocketSpec.scala

This is a test for #957 
```
[info] SocketSpec:
[info] tcp
[info] - echo.requests (683 milliseconds)
[info] - readN *** FAILED *** (65 milliseconds)
[info]   Vector(1, 2, 3, 4, 4, 4, 4) was not equal to Vector(1, 2, 3, 4, 3, 2, 1) (SocketSpec.scala:90)
```

Test for 957

---

core/jvm/src/test/scala/fs2/Pipe2Spec.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/CompileScope.scala

Fixes the scenarios in the two new tests

Fixed issue with interrupting inner scope from interruptable parent.

---

core/jvm/src/test/scala/fs2/SchedulerSpec.scala
core/shared/src/main/scala/fs2/Scheduler.scala

Fixes #1077 
`Scheduler.effect.timedCancellable` schedules an action that completes a Promise with `Some(a)` after a timer completes, and returns the result of reading the Promise along with an action that cancel s the timer and completes the Promise with `None`.
This means that if `cancel` is called after the timer and the action have completed, it will try to complete the Promise with None after the action has already completed it with `Some(a)`, and therefore the cancel action will fail with a PromiseAlreadyCompletedException.
If you look at `timedGet` (or `timedDecrementBy` in Semaphore, which has the same problem), we can see where the problem is:
```scala
cancellableGet.flatMap {
case (g, cancelGet) =>
scheduler.effect.delayCancellable(F.unit, timeout).flatMap {
case (timer, …
```

Remove race condition in Scheduler.effect.delayCancellable

---

core/shared/src/main/scala/fs2/async/async.scala
core/shared/src/main/scala/fs2/internal/Resource.scala
core/shared/src/test/scala/fs2/async/PromiseSpec.scala

This PR adds `fs2.async.once`. We already have `start` for eager memoization; `once` has the same signature, but it memoizes lazily.

fs2.async.once

---

site/src/guide.md

As per https://gitter.im/functional-streams-for-scala/fs2?at=5a778d38e217167e2c40cc1a the old code doesn't work with 0.10.0
Passes `sbt microsite/makeMicrosite`

Fix documentation example

---

site/src/concurrency-primitives.md
site/src/faq.md
site/src/guide.md

Adding examples of the concurrency primitives present in the `fs2.async` package object, taken from the examples I've been working on [here](https://github.com/gvolpe/advanced-http4s/tree/master/src/main/scala/com/github/gvolpe/fs2).
Not sure if the layout structure seems okay to you but I can always change it, this is just the first attempt to have something. ~~I didn't use `tut` for the examples because I do not know how. It seems to work only with trivial examples but not when you use different classes and objects.~~
~~Also, I'm not sure that the relatives links added (exactly two) are working. When I generate the site locally the relative links don't get parsed correctly but neither does the Scala code.~~
Submitting this PR as @SystemFw pointed out it would be nice to have it in the …

Adding Concurrency Primitives examples section

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/CompileScope.scala

This now properly translates the RunLeg algebra. 
Now I am sure this will properly fix the #1099. 
This implementation will have an issue when someone will manage to pass `Stream.StepLeg` over the `translate` boundary. I have no idea how to properly fix that, it may be just something we will have to live with.
The core issue with that is that the `FreeC` which is stored in the `Stream.StepLeg` can be seen multiple times in the `RunLeg`(as well we can make the `FreeC` go back into the stream that will be once again translated then), as such we cannot translate the whole `FreeC` in one go.

RunLeg now only translates what it requires for its step.

---

core/shared/src/main/scala/fs2/Chunk.scala
scodec/shared/src/main/scala/fs2/interop/scodec/ByteVectorChunk.scala

Unfortunately, the override is necessary as discussed on [gitter](https://gitter.im/functional-streams-for-scala/fs2?at=5aa462170a1614b712061479) as making `splitAtChunk` different breaks binary compat.

Refactor drop and take to be specialized.

---

build.sbt
core/jvm/src/main/scala/fs2/StreamApp.scala
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/CompileScope.scala

@mpilquist @SystemFw 
Pavel have came up with simplified interpreter, that did multiple things for us: 
+ Fixed the SOE and memory leak for the #1107 .
+ Merged `StepLeg` and `Uncons` into one operation, which simplified translate for these cases.
+ Remove of `SetScope` from algebra.
I implemented largely simplified translate. 
The main idea of the new interpreter is that there is no more specialised interpretation of the `Algrebra` for when in normal stream, uncons stream or stepLeg stream. They all have been merged. The interpreter no longer needs to go to he lowest level when opening scope, but does it where it requires. The only exception for this is when creating an interruptible scope, which needs to be done on the `compileLoop` level, this is however optimised with passing the next …

Simplification of interpreter, fixing the SOE

---

core/shared/src/main/scala/fs2/Stream.scala

Since we started to look a bit to performance, I noticed these two things:
As of now we created new scope for each bracket, which is a minor issue in terms of performance, but since we already have the Aquire/Release algebra, why not to use it properly right? 
Second, thing that bugged me was that `eval_` was implemented via `eval(fa).drain` which adds an unnecessary `Output` and `Step` algebra. 
Running a stream that did 10000 `eval_` seen about 25% increase in performance.

Removed new scope in bracket + optimised eval_

---

core/jvm/src/test/scala/fs2/Pipe2Spec.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/CompileScope.scala

We did not correctly pass the next scope for the `Algebra.Step` we always passed the original scope before the evaluation of the algebra. 
As well there was an issue that if we already were on root scope we would not search its children for scopes for `Algebra.Step`.
This fixes #1120 .

Fix scope passing in Algebra.Step evaluation.

---

core/jvm/src/main/scala/fs2/internal/ThreadFactories.scala
core/shared/src/main/scala/fs2/internal/AcquireAfterScopeClosed.scala
core/shared/src/main/scala/fs2/internal/Canceled.scala
core/shared/src/main/scala/fs2/internal/NonFatal.scala
core/shared/src/main/scala/fs2/internal/TranslateInterrupt.scala

I'm not sure what to do about the 0.10 series. The reason I came across this the other day is because we had a dev use things from the internals package.
At least in the 1.0 series, we can hide it from the get-go.

Make fs2.internal inhabitants private to fs2

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/CompilationTest.scala

It closes #1138 
As discussed in the issue mentioned above, adding a `covaryId[F]` as part of `IdOps`.

Adding covaryId[F] for interop with cats.Id

---

core/jvm/src/test/scala/fs2/StreamPerformanceSpec.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Segment.scala
core/shared/src/test/scala/fs2/ChunkProps.scala
core/shared/src/test/scala/fs2/ChunkSpec.scala
scodec/shared/src/main/scala/fs2/interop/scodec/ByteVectorChunk.scala

See #1160 for details, but basically, operations like `Stream#map` result in dechunking if an `unconsChunk` is encountered. To fix, this PR changes `Segment#unconsChunk` such that when stepping, all of the emitted chunks from a single step get copied to a new chunk instead of taking the first and pushing the rest in to the tail.
In the test added to `StreamPerformanceSpec`, this change results in an improvement from about 2500ms to 15ms.
To implement an efficient `Chunk.concat`, I lifted the implementation from fs2 0.9 and added support for the primitive chunk types. One note: calling `concat` with `ByteVectorChunk`s results in `instanceOf[Byte]` checks on each element. I have two ideas on how to fix this:
1) Introduce a trait like: `trait KnownClass[A] { self: Chunk[A] => val classTag: …

Optimized unconsChunk

---

core/jvm/src/test/scala/fs2/PipeSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/TestUtil.scala

Add a new test generator that gives us a filtered stream, which can emit
empty chunks.
The groupAdjacentBy test goes red with only the generator change; the
code change brings it back to green
Closes #1162 
-----
I don't know the right way to fix the `mapSegments` test failure yet.
I think the test is nonsensical; The test says
```scala
runLog(s.get.mapSegments(identity).segments) shouldBe runLog(s.get.segments)
```
but the `Segment` docstring says
>   The `equals` and `hashCode` methods are not defined for `Segment`.
So this means that `shouldBe` is not safe to use with `Segment` values
What if we change the test to say this?
```scala
runLog(s.get.mapSegments(identity).segments.map(_.force.toVector) shouldBe runLog(s.get.segments.map(_.force.toVector))
```

Fix groupAdjacentBy handling empty chunks

---

core/shared/src/main/scala/fs2/Catenable.scala
core/shared/src/main/scala/fs2/Segment.scala

By changing `unconsChunks` to use a list instead of catenable, we avoid overhead of tracking the rights in `Segment#uncons` and `Segment#foreach`.
Additionally, `Catenable#{uncons,foreach}` was allocating an `ArrayBuffer` even if the catenable was a singleton or empty. This resulted in a 16-element array allocation.

Small performance improvements in Segment#unconsChunks

---

scodec/shared/src/main/scala/fs2/interop/scodec/ByteVectorChunk.scala

Allowing extractor to be used with io.tcp.Socket.read/write.

Changed ByteVectorChunk to case class as in #1181

---

core/jvm/src/main/scala/fs2/compress.scala
core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/jvm/src/test/scala/fs2/MergeJoinSpec.scala
core/jvm/src/test/scala/fs2/PipeSpec.scala
core/jvm/src/test/scala/fs2/ResourceSafetySpec.scala
core/jvm/src/test/scala/fs2/StreamPerformanceSpec.scala
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/jvm/src/test/scala/fs2/async/QueueSpec.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Pipe.scala
core/shared/src/main/scala/fs2/Pipe2.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/text.scala
core/shared/src/test/scala/fs2/CompilationTest.scala
core/shared/src/test/scala/fs2/SegmentSpec.scala
core/shared/src/test/scala/fs2/TextSpec.scala
docs/ReadmeExample.md
io/src/main/scala/fs2/io/file/file.scala
io/src/main/scala/fs2/io/file/pulls.scala
site/src/guide.md

Fixes #1175
See #1175 for performance test results before and after this change.
Overall, chunk based streams perform better than segment based streams. It's possible to construct specialized benchmarks where segment based streams perform better but such benchmarks aren't transferrable to real stream programs. Given that we get better performance and the API ends up *significantly* simpler to work with, these issues outweigh the API breakage concerns, which I do take very seriously. Also note that we no longer have weirdness around when evaluation occurs and when exceptions are thrown due to the lazy nature of `Segment`.
I left `Segment` in place, and kept the `Stream.segment` and `Pull.segment` constructors, which now lazily unfold the segment in to chunks. This is nice in that users can …

Changed core interpreter and API to be chunk based instead of segment based

---

core/shared/src/main/scala/fs2/Segment.scala

This part in `Segment` (line 1393) compares a segment against the empty segment
```scala
val step = self
.stage(
Depth(0),
trampoline.defer,
o => emits(Chunk.singleton(o)),
os => emits(os),
r => {
if (result.isEmpty || result
.flatMap(_.toOption)
.fold(false)(_ == Segment.empty)) result = Some(Left(r));
throw Done
}
)
.value
```
There is a class `SingleChunk` implementing `Segment` that is defined as a case class. Thus it gets `equals` implicitely. In my case that lead to comparing to SingleChunk segments where one was not empty, calling `equals` on its chunks which dramatically affected performance. In my case the code that took >3s before runs in ~200ms with the `case` modifier removed.

Remove `equals` introduced by case class

---

docs/migration-guide-1.0.md

We'll need at least another edit before 1.0 as we'll likely remove `StreamApp` and change some stuff due to pending changes in cats-effect (w.r.t blocking). I'm also going to make an attempt at a ScalaFix for at least the method renames.
@pchlupacek Let me know if you ran in to stuff when migrating your libraries & apps that aren't covered here.

Made a pass at 1.0 migration guide

---

core/shared/src/main/scala/fs2/Pipe.scala
core/shared/src/main/scala/fs2/Pipe2.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/FreeC.scala

@mpilquist, @SystemFw this is a slight modification to ViewL, that is now trait with own case class for Eval Type. I think this cleans pattern match a bit (no Eval case anymore). 
Also this removes need for viewL suspension in main interpreter, savings on 2 allocation through every step of the interpreter (Suspend + Bind of F).

Introduced FreeC.ViewL type

---

core/shared/src/main/scala/fs2/Stream.scala

Small but nasty bug :)
We'll probably need an M4 soon, fs2-reactive-streams relies on this op and broke on M2-M3

Fix bug with .pull.take computing wrong remainder

---

benchmark/src/main/scala/fs2/benchmark/ConcurrentBenchmark.scala
build.sbt
core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/jvm/src/test/scala/fs2/async/TopicSpec.scala
core/shared/src/main/scala/fs2/Segment.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/async/async.scala
core/shared/src/test/scala/fs2/CompilationTest.scala
core/shared/src/test/scala/fs2/Fs2Spec.scala
core/shared/src/test/scala/fs2/TestUtil.scala
core/shared/src/test/scala/fs2/async/OnceSpec.scala
io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/main/scala/fs2/io/file/FileHandle.scala
io/src/main/scala/fs2/io/file/file.scala
io/src/main/scala/fs2/io/file/pulls.scala
io/src/main/scala/fs2/io/io.scala
io/src/main/scala/fs2/io/tcp/Socket.scala
io/src/main/scala/fs2/io/tcp/tcp.scala
io/src/main/scala/fs2/io/udp/Socket.scala
io/src/main/scala/fs2/io/udp/udp.scala
io/src/test/scala/fs2/io/JavaInputOutputStreamSpec.scala
io/src/test/scala/fs2/io/tcp/SocketSpec.scala

This includes support for `ContextShift` (aka, the cats-effect version of `Linebacker`).
Note: in a separate PR, after this is merged, I am planning on getting rid of the synchronous/blocking versions of various `io` streams. E.g., deleting `fs2.io.stdout` and renaming `fs2.io.stdoutAsync` to `stdout`. The synchronous ones are dangerous and if we fix that by adding a blockingEC + `ContextShift[F]`, we've made them redundant with the async ones.
Similarly, we might want to do something similar with the `fs2.io.file` package, though there I can see keeping the synchronous ones, changing them to take the blocking ec + `ContextShift[F]`, and leaving the async ones use java.nio async file handle stuff.

Upgraded to latest cats-effect hash release

---

core/jvm/src/test/scala/fs2/PipeSpec.scala
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Stream.scala

These changes were backported from the series/1.0 PR https://github.com/functional-streams-for-scala/fs2/pull/1220

add Stream.fromEither

---

core/jvm/src/test/scala/fs2/MergeJoinSpec.scala
core/jvm/src/test/scala/fs2/PipeSpec.scala
core/jvm/src/test/scala/fs2/ResourceSafetySpec.scala
core/jvm/src/test/scala/fs2/StreamPerformanceSpec.scala
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/ErrorHandlingSpec.scala
core/shared/src/test/scala/fs2/TestUtil.scala
io/src/main/scala/fs2/io/tcp/Socket.scala

I [asked on gitter](https://gitter.im/functional-streams-for-scala/fs2?at=5b74a2b049932d4fe4e8ac65) whether there was any `Either[Throwable, A] ⇒ Stream[Pure, A]` method in fs2. After some discussion, the conclusion that it doesn't make sense to have a `Pure` version, but a `Stream.fromEither` constrained to an `F[_]` with an `ApplicativeError[F, Throwable]` was a good idea.
This PR is to constrain the methods already in fs2 in the same way, so we can add `Stream.fromEither`, either in an addition to this PR or in a subsequent PR.
Thanks to @SystemFw, @mpilquist, and @ChristopherDavenport for helping me figure out how to make the necessary changes and tweaking the initial question into something worth adding to fs2.

Constrain raiseError with ApplicativeError

---

docs/ReadmeExample.md
docs/migration-guide-1.0.md
docs/src/ReadmeExample.md
io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/main/scala/fs2/io/file/FileHandle.scala
io/src/main/scala/fs2/io/file/file.scala
io/src/main/scala/fs2/io/file/pulls.scala
io/src/main/scala/fs2/io/io.scala
io/src/test/scala/fs2/io/IoSpec.scala

Consolidated the sync/async versions of methods that deal with input and output streams. The sync versions were dangerous and when their signatures were corrected to use a blocking execution context, the async ones became redundant.
Similar PR coming for `file` package.

Removed sync/async split in input stream methods

---

core/jvm/src/test/scala/fs2/GroupWithinSpec.scala
core/jvm/src/test/scala/fs2/StreamCancelationSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/TestUtil.scala

This is a prototype for `groupWithin`, same as #1157 
Still missing tests and docs, but worth submitting since it uses a different approach.
Looking for feedback from @Daenyth and @changlinli

Add `groupWithin`

---

README.md

This adds [fs2-cron](https://github.com/fthomas/fs2-cron) to the list of projects using FS2. It is a small library that provides variants of `Stream.awakeEvery` and `Stream.sleep` that uses [Cron4s](https://github.com/alonsodomin/cron4s) cron expressions and the current date-time to determine the duration these streams will sleep.
Here is a simple example from the README:
```scala
import cats.effect.{IO, Timer}
import cron4s.Cron
import eu.timepit.fs2cron.awakeEveryCron
import fs2.Stream
import java.time.LocalTime
import scala.concurrent.ExecutionContext
implicit val timer: Timer[IO] = IO.timer(ExecutionContext.global)
val evenSeconds = Cron.unsafeParse("*/2 * * ? * *")
// evenSeconds: cron4s.expr.CronExpr = */2 * * ? * *
val printTime = Stream.eval(IO(println(LocalTime.now)))
// …
```

Add fs2-cron to the list of projects using FS2

---

site/src/guide.md

It currently looks like this on the site:
There's a small typo fix as well.

Fix missing opening code block in Chunks guide section

---

io/src/main/scala/fs2/io/file/file.scala

This was discussed in the [http4s Gitter room](https://gitter.im/http4s/http4s?at=5b995f1a7ce5f5314fa0d75c).  See https://github.com/http4s/http4s/issues/2071 for a usage

Modify file.readRange to take in Long range instead of Int

---

core/shared/src/main/scala/fs2/Stream.scala

This is a convenience I've written a handful of times to hold a server application open.
Couldn't think of a test that adds to the type.

Add Stream.never

---

.travis.yml
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/concurrent/Queue.scala
core/shared/src/test/scala/fs2/ChunkProps.scala
io/src/main/scala/fs2/io/file/file.scala

Saw this when using http4s 0.19.0-M3:
```
"message":"Error writing body",
"logger_name":"org.http4s.server.blaze.Http1ServerStage$$anon$1",
"thread_name":"scala-execution-context-global-26",
"level":"ERROR",
"level_value":40000,
"stack_trace":"java.nio.BufferUnderflowException: null
at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
at fs2.Chunk$ByteBuffer.get(Chunk.scala:1035)
at fs2.Chunk$ByteBuffer.get(Chunk.scala:1021)
at fs2.Chunk$Buffer.toArray(Chunk.scala:787)
at fs2.compress$.$anonfun$_deflate_stream$2(compress.scala:36)
at fs2.compress$.$anonfun$_deflate_stream$2$adapted(compress.scala:34)
at fs2.Pull$.$anonfun$flatMap$1(Pull.scala:60)
at fs2.internal.FreeC.$anonfun$flatMap$1(FreeC.scala:35)
at fs2.internal.FreeC$ViewL$.$anonfun$mk$1(FreeC.scala:233)
at …
```

Fixed a bug in Chunk#toArray when the backing type is ByteBufferChunk

---

core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/shared/src/main/scala/fs2/concurrent/Topic.scala

During some stress testing of my app i encountered a stackoverflow in [Topic](https://github.com/functional-streams-for-scala/fs2/blob/ff319f2310ef94d6c8781b5de46203f5dfdda47f/core/shared/src/main/scala/fs2/concurrent/Topic.scala#L166). The problem seems to be the use of `mapValues` in `publish` since it only wraps the `Map` in `MappedValues` ([known issue](https://github.com/scala/bug/issues/9499)). So if `accepts` is called after a lot of successive `publish` calls it blows up with a stackoverflow.
After applying this patch i did not encounter any stackoverflows anymore.

Avoid stackoverflow in Topic

---

core/shared/src/main/scala/fs2/concurrent/Queue.scala

The implementation of `FIFO` is actually `LIFO` and vice-versa. The default strategy is `LIFO` which actually acts as a `FIFO`, which is quite confusing.
This PR fixes the function names (`FIFO` to `LIFO` and vice versa) and sets the default to `FIFO`.

Fix lifo/fifo terminology in Queue

---

core/shared/src/main/scala/fs2/internal/CompileScope.scala

Some small code changes for the `CompileScope` class.
- The `ancestors` inner function, which runs through the chain of a scope's parents, is a pure function and  needs no `F` wrapper.
- We use functions from `cats.Traverse` and `cats.TraverseFilter`, for removing nested container layers.

Small Change: Ancestors need no F

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Resource.scala

Useful for cases like #1312 
Better have something like this in the public than creating an Algebra node in a high level operation like `groupWithin`

Add bracketCancellable

---

core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Resource.scala

Attempts to fix #1303
In particular, it definitely fixes the original leak, and it appears to not leak outstanding timeouts either, but I'm not 100% sure about how airtight the resource safety on that timeout being canceled is. 
It kinda relies on `onFinalise` not running until the `finaliser` in the `bracket` in `startTimeout` has completed. Ideas welcome

groupWithin leak

---

core/jvm/src/test/scala/fs2/PipeSpec.scala
core/shared/src/main/scala/fs2/Stream.scala

Fix #1297. Explanation is in https://github.com/functional-streams-for-scala/fs2/issues/1297#issuecomment-436666729.

Fix parEvalMap getting stuck on exception

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

We make some changes to the internal Stream implementation, in the `Algebra` file, to avoid using implicit classes.
- We remove the syntax extension implicit class `AlgScopeSyntax`, which was not being used anywhere.
- We remove the syntax extension `AlgEffectSyntax`, and extract its only method as an internal private function. We move this method to the bottom of the file, closer to the related _translate_ methods. We replace the only two uses needed for this function.
- Without `AlgScopeSyntax`, the sub-trait `AlgScope` is not used anywhere, so we can remove it and replace it with `AlgEffect`.

Internal changes to the implementation of `translate`.

---

build.sbt
core/jvm/src/test/scala/fs2/PipeSpec.scala
core/jvm/src/test/scala/fs2/ResourceSafetySpec.scala
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/fs2.scala

We remove the `EitherSyntax` implicit class. 
This implicit class was introduced to provide a Right-biased `flatMap` for the `Either` type when compiling with `Scala 2.11`. However, although `fs2` still supports Scala 2.11, the special right-biased `flatMap` was used nowhere in `fs2`. The only method being used was the `toOption`; and since that is was followed with `Option.get`, we can just use `.right.get` instead by way of the `Either.RightProjection` class.

Remove the EitherSyntax class

---

core/jvm/src/test/scala/fs2/MergeJoinSpec.scala
core/jvm/src/test/scala/fs2/Pipe2Spec.scala
core/jvm/src/test/scala/fs2/ResourceSafetySpec.scala
core/jvm/src/test/scala/fs2/StreamCancelationSpec.scala
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/jvm/src/test/scala/fs2/StreamTimerSpec.scala
core/jvm/src/test/scala/fs2/SwitchMapSpec.scala
core/jvm/src/test/scala/fs2/concurrent/QueueSpec.scala
core/jvm/src/test/scala/fs2/concurrent/SignalSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/TestUtil.scala
io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/main/scala/fs2/io/file/Watcher.scala
io/src/test/scala/fs2/io/file/WatcherSpec.scala
reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamSubscriber.scala
reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamSubscription.scala
reactive-streams/src/test/scala/fs2/interop/reactivestreams/SubscriberSpec.scala

`*>` has potential memory problems due to strictness, from the known stackoverflows issues on recursion to weirder cases like https://github.com/typelevel/cats-effect/issues/401#issuecomment-440750872

Replace *> with >> to avoid memory issues

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/CompileScope.scala

We extend the ScalaDocs description of the Stream class.
- We adds some descriptions for the notions of pull-based evaluation, and laziness. We show some special cases of Streams.
- We add a section describing the equivalence between some of the methods of the Stream class, and similar methods in the List class. This equivalences hold true for finite and pure streams.
- We add into the docs of some of methods a description of how the methods handles non-terminating streams.
Thanks to @SystemFw for clarifying some doubts and questions for this PR.

Expands the ScalaDocs for the Stream class.

---

io/src/main/scala/fs2/io/JavaInputOutputStream.scala
reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamSubscriber.scala

When working on #1332, I noticed we could use some simple syntax cleanup in JavaInputOutputStream. No functional changes in this PR.

Cleaned up the implementation of JavaInputOutputStream

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/CompileScope.scala

This commit removes the type parameter `O`, which is usually associated to the output of a `Stream[F, O]`, from several internal classes and types, such as `CompileScope`, its internal `State`, the `InterruptContext, and the algebra operation `GetScope`. We also remove it from the definitions of several auxiliary methods.
It turns out that `CompileScope` is not really concerned itself with the emission of values of type `O`, but merely with the correct handling of the shared resources in a common scope. Removing the parameter `O` helps to make this fact clear.

Remove the `O` parameter from CompileScope.

---

core/shared/src/main/scala/fs2/Chunk.scala
io/src/main/scala/fs2/io/tcp/Socket.scala
io/src/main/scala/fs2/io/udp/AsynchronousSocketGroup.scala

```
env JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home amm
Loading...
Welcome to the Ammonite Repl 1.4.4
(Scala 2.12.7 Java 1.8.0_192)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ sys.props("java.version")
res0: String = "1.8.0_192"
@ import $ivy.`co.fs2::fs2-io:1.0.1`, fs2.Chunk
import $ivy.$                     , fs2.Chunk
@
Chunk.byteBuffer { val b = java.nio.ByteBuffer.allocate(10); b.position(2); b.limit(7); b }.toByteBuffer
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
fs2.Chunk.toByteBuffer(Chunk.scala:284)
ammonite.$sess.cmd2$.<init>(cmd2.sc:1)
ammonite.$sess.cmd2$.<clinit>(cmd2.sc)
```
After this PR:
```
env JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home …
```

Fixed #1357

---

core/jvm/src/test/scala/fs2/PipeSpec.scala
core/shared/src/main/scala/fs2/Stream.scala

We still have some projects on 0.10.6 and are affected by #1297.

Backport #1311 (fix for #1297) to 0.10

---

io/src/main/scala/fs2/io/io.scala

* Document that the io implementations do, in fact, block
* Recommend an unbounded thread pool
* Reference Cats Effect docs on blocking threads

Add recommendations for blockingExecutionContext

---

build.sbt
core/shared/src/main/scala/fs2/Pipe.scala

No one must have used `Pipe.join` ever, because it looks very broken to me. Anyway, this PR reimplements it with `broadcast`.  Pavel already had a look on gitter

Express Pipe.join with broadcast

---

.gitignore
build.sbt
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

I noticed this when working on tagless branch -- the error handling case in `bracketFinalizer` could never be hit b/c it was only called immediately after a simple emit, which cannot fail with an exception.

Removed dead code path in Stream.bracket

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

This PR modifies the Algebra object, to hide all the sub-classes of that algebra. Thus, the implementation are not visible outside it, and only in the algebra are those constructed/deconstructed.
To allow this, we cut from the implementation of `Pull.mapOutput` the part that  generates a natural transformation, to a new `Algebra.mapOutput` operation.

Make all Algebra subclasses private.

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/RepeatSpec.scala
site/src/guide.md

Lately, I found myself several times in the need of repeating a `Stream` a specific number of times and I don't see a good way of doing this with the existing combinators - one can do `repeat.take(n * s)` for a `Stream` of known size `s`, but that usually doesn't help as the length is unknown. Also added a scalacheck spec for testing `repeat` and `repeatN` on simple, pure streams.
Maybe not worth being added, but as there's a chance others need this as well, I wanted to give it a try ;)
Questions and/or comments welcome!

Add repeatN combinator to Stream and a spec for repeat and repeatN

---

core/jvm/src/test/scala/fs2/ResourceCompilationSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/CompileScope.scala

Motivation: be able to return a `Resource` instead of a singleton Stream, for an abstraction whose constructor uses Stream concurrency combinators.
What we can do today:
- Return a singleton stream. Example:
```scala
def hold[F2[x] >: F[x], O2 >: O](initial: O2)(
implicit F: Concurrent[F2]): Stream[F2, Signal[F2, O2]] =
Stream.eval(SignallingRef[F2, O2](initial)).flatMap { sig =>
Stream(sig).concurrently(evalMap(sig.set))
}
```
- Fall back to use `start` + `Fiber` directly. Way more error prone and lower level.
Status: I thought using `Resource` to manage the top level scope is enough, but it's not.
Look at the `basic` test for the gist of the behaviour I want to enable.

Compile a Stream down to a Resource

---

CONTRIBUTORS.md
core/shared/src/main/scala/fs2/Stream.scala

Resolves #1184 
As per the conversation on the issue, this PR adds `scanMap` and `scanMonoid` with similar signature as `foldMap` and `foldMonoid`, but emit intermediate results.

scanMap and scanMonoid

---

build.sbt
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/CompileScope.scala
core/shared/src/main/scala/fs2/internal/Resource.scala
io/src/test/scala/fs2/io/tcp/SocketSpec.scala

Prior to this PR, resources were released in two main ways:
1. `Algebra.Release` would release a specific resource
2. `Algebra.CloseScope` would close a scope, releasing all resources in that scope (and child scopes)
While working on the topic/tagless2 branch, I noticed that we hardly ever hit case (1) above. Almost all resources get released as a result of (2). I added instrumentation to the interpreter to track those conditions and ran our test suite with these results:
|Release Type|Pre PR|Post PR|
|-------------|-------|--------|
|Explicit|59465|0|
|Scope Closure| 1492331| 1545044|
Prior to this PR, over 96% of all release releases were due to scope closure.
In this PR, I removed the `Algebra.Release` constructor and changed `Stream.bracket` to no longer explicitly release the …

Removed Algebra.Release

---

core/jvm/src/test/scala/fs2/Pipe2Spec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/CompileScope.scala

This makes `eval` nodes properly interruptible. For this PR I decided to go with the least intrusive approach possible, there is plenty of (relatively) low hanging fruit to make things better, simply because they were designed without taking F interruption into account.
As a mitigating factor though, a lot of code which would naively be leaky is actually in an `F.start` section plus custom Stream interruption,  and that makes it unreachable for F interruption, which is why I believe we are not seeing problematic behaviour across the board.
In any case, I'll be auditing and fixing for this when time permits, but the problematic behaviour should be fixed as is

Interruptible eval

---

build.sbt
io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/main/scala/fs2/io/io.scala
io/src/test/scala/fs2/io/JavaInputOutputStreamSpec.scala

I think it makes sense considering `toInputStream`  returned singleton stream.
Not sure what to do with bin compat though. Is there some branch for breaking changes?

add `toInputStreamResource` 

---

core/shared/src/main/scala/fs2/text.scala
io/src/main/scala/fs2/io/io.scala

Add stdoutLines and stdinLines as commented in the issue https://github.com/functional-streams-for-scala/fs2/issues/1328

Printing sinks should take ContextShift + EC

---

core/shared/src/main/scala/fs2/Stream.scala

LinearSeq is caluculate every time of size. I refactored of emits.

Avoid calculate size of emits

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

I'm not sure if these are the right places for these functions, but it seemed like a good start. This PR was prompted by reading @gvolpe's TypeLevel blog post [“Tagless Final algebras and Streaming”](https://typelevel.org/blog/2018/05/09/tagless-final-streaming.html) and trying to implement an interpreter parameterized by `F[_], G[_]`. For example, given this algebra:
```scala
import cats._, cats.arrow.FunctionK, cats.effect.IO
trait FooAlg[F[_], G[_]] {
def foo(): G[Int]
def bar(): F[Int]
}
```
if I want to implement `foo()` in terms of `bar()` without fixing `G` as `Stream[F, ?]`, I think one must have an `F ~> G` available.
```scala
class FooImpl[F[_] : Applicative, G[_] : Monad](implicit FtoG: F ~> G) extends FooAlg[F, G] {
def foo(): G[Int] = FtoG(bar()).flatMap(x => …
```

add FunctionK instances for Stream and Pull

---

build.sbt
core/shared/src/main/scala/fs2/concurrent/PubSub.scala
core/shared/src/main/scala/fs2/concurrent/Queue.scala
core/shared/src/main/scala/fs2/concurrent/Signal.scala
core/shared/src/main/scala/fs2/concurrent/Topic.scala
experimental/src/main/scala/fs2/experimental/concurrent/Queue.scala

Adds constructors similar to those we now have in cats-effect, for SignallingRef, Queue and Topic, as proposed by @mpilquist @ [gitter](https://gitter.im/functional-streams-for-scala/fs2?at=5cb1f90fbd70a40d5f436249).

Add dual constructors for fs2.concurrent datatypes

---

build.sbt

it would be helpful to have this merged for the Scala community
build. normally we're able to override this kind of thing in our
own config but it's not working in this case for some reason

kind-projector has moved to typelevel org

---

README.md

Obviously up to you guys to decide whether this should be added or not. I guess as a word of warning, the API isn't very stable, but otherwise we have been using that library in production for around 6 months now.

Add fs2-google-pubsub as a related project

---

build.sbt
core/shared/src/main/scala-2.12-/fs2/internal/package.scala
core/shared/src/main/scala/fs2/Stream.scala

It seems like a shame to have a dependency on scala-collection-compat (which is currently broken and waiting for an incompatible 2.0 release) when all that fs2 needs from it is one alias and one extension method.
This change shouldn't affect compatibility for any Scala version and would unblock #1453.
r? @mpilquist

Remove scala-collection-compat dependency

---

core/jvm/src/test/scala/fs2/PipeSpec.scala
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/PullSpec.scala

The unicode arrow `⇒` is deprecated in 2.13, and it's used very inconsistently here anyway, so it seems reasonable just to standardize on `=>`.

Replace deprecated ⇒

---

build.sbt
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala-2.13+/internal/package.scala

This reverts #1452, which was breaking builds on master, and includes a couple of fixes. I've got an update for #1453 that should be pretty easy to merge, so the kind-projector version should be back to latest soon.

Fix master

---

.travis.yml
build.sbt
core/shared/src/test/scala/fs2/ChunkGen.scala
core/shared/src/test/scala/fs2/FreeCSpec.scala
core/shared/src/test/scala/fs2/TestUtil.scala

Includes @kubukoz's commit from #1453 but rebased after my #1454, #1455, #1456, and one additional fix for an interaction between ScalaCheck 1.14's `Cogen.apply` and the backported SAM support in 2.11.

Updates for 2.13.0-RC1

---

core/jvm/src/test/scala/fs2/PipeSpec.scala
core/shared/src/main/scala/fs2/Stream.scala

This adds a chunkMin combinator which is like that pair of chunkLimit, but puts a combination into each chunk having atleast N elements, but does not stop their, continues with the values available to any particular Chunk if they are available and larger than the size.

Add chunkMin Combinator

---

core/shared/src/main/scala/fs2/Chunk.scala

Originally reported by @Taig  
```scala
Stream.emit(1).mapFilter { x => println(x); Some(x) }
1
1
```
The reason is that `mapFilter` goes through `collect`, which takes a `PartialFunction` and says
```scala
val o = apply(i)
if (pf.isDefinedAt(o))
b += pf(o)
```
generally `pf.isDefinedAt` does not require the body of `pf` to be evaluated when it's defined by pattern matching, but in this case it's coming through `Function.unlift`, and therefore the body executes twice.
In terms of correctness, this is only observable via side-effects, but it still feels weird and I don't think it was foreseen, hence this quick fix

Avoid executing function twice in `mapFilter`

---

README.md
site/src/main/tut/documentation.md

Removed API links from the documentation page, as they are broken anyway and to avoid need to keep them in sync in two different places
Refs #1470

Fix API links

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/concurrent/PubSub.scala
core/shared/src/main/scala/fs2/internal/CompileScope.scala
core/shared/src/main/scala/fs2/text.scala
io/src/test/scala/fs2/io/JavaInputOutputStreamSpec.scala

Sometimes it's "loop" and sometimes "go". If there is no semantics in "loop" I think is better to make them uniform.

Fix recursive aux functions differences

---

scalafix/build.sbt
scalafix/input/src/main/scala/fix/AkkaSink.scala
scalafix/input/src/main/scala/fix/Fs2sinkremoval.scala
scalafix/output/src/main/scala/fix/AkkaSink.scala
scalafix/output/src/main/scala/fix/Fs2sinkremoval.scala
scalafix/rules/src/main/scala/fix/v1.scala

One possible issue with this PR is that there are 2 input and output files associated with this scalafix rule.  Would it be preferred that they be combined into one?

Scalafix for replacing Sink with Pipe

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

Propagate error from inner stream of parJoin before continue on with ++.

---

README.md
docs/ReadmeExample.md
docs/src/ReadmeExample.md

We probably don't want to use a fixed thread pool in a blocking context; update the examples accordingly. This is per a discussion with @djspiewak in the cats-effect gitter room this morning (couldn't figure out how to link directly to it).

Replace pool used in example blocking execution context

---

io/src/main/scala/fs2/io/tcp/Socket.scala

I was trying to create a ConnectionPool for a client. However these sockets sitting somewhere may be dead whenever we come back to them, presently I have no way to tell which of a pool of sockets would be still active to be reused. This would hopefully restore my ability in this regard.

Add isOpen to Socket Interface

---

io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/main/scala/fs2/io/udp/AsynchronousSocketGroup.scala
io/src/test/scala/fs2/io/JavaInputOutputStreamSpec.scala

This resulted in garbled data when using `fs2.io.toInputStream`. I've found another instance of such broken call in `AsynchronousSocketGroup`, so I fixed that as well.
I've also replaced a custom generator in `JavaInputOutputStreamSpec` with the one leveraging the standard `Chunk[Byte]` generator. Now the existing tests also cover the issue in question.

Fix offsets for some Array.copy calls

---

build.sbt

Note: we have to keep test dependency on 2.0.0-M3 in order for our test suite to work (cats 1.6 is on scalacheck 1.13 whereas 2.0.0 is on 1.14).

Rolled back cats-core to 1.6.1 in prep for 1.0.5 release

---

.sbtopts
core/shared/src/main/scala/fs2/Stream.scala

This PR deletes the `evalMap` unnecessary restriction of receive a function returning `Unit` because the result type of that function will be actually ignored.

Delete evalMap return restriction

---

core/jvm/src/main/scala/fs2/compress.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/concurrent/Signal.scala
core/shared/src/main/scala/fs2/text.scala
core/shared/src/test/scala/fs2/CompilationTest.scala
core/shared/src/test/scala/fs2/PullSpec.scala

This was something I noticed when working on the topic/fs3 branch. This PR changes the `stream` and `streamNoScope` methods to require the result type of the `Pull` to be `Unit`. This is the `Pull` equivalent of `-Xfatal-warnings -Ywarn-value-discard` -- folks can explicitly indicate they want the result type thrown away via `p.void.stream`.
Note how many cases in fs2 itself were using a nonsensical result type -- these are vestiges of the old 0.9 `Pull` API where termination has to be explicitly signaled via an `Option` result type.

Changed Pull#{stream,streamNoScope} to require Unit result type

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

It may save allocating a lambda. Even if it can be optimized away, 
the first-order code in this case may be easier to read.

Replace a Option.fold with an Option.isEmpty

---

core/shared/src/main/scala/fs2/Chunk.scala

Adds methods to convert a Chunk to Bit and Byte Vector, for easier integration with `scodec-stream`.
They are fairly unobvious for casual users. I was also tempted to add `.bits` to stream to be `chunks.map(_.toBitVector)` but perhaps that could go in `scodec-stream` directly

Add conversions to BitVector and ByteVector

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

This reverts commit e0eb895113352ce429560b0b2170f0d0cf4bffd4.
Forgot to revert this after the bug was fixed in Scala 2.13. Do we want to?

Revert "Applied workaround for scala/bug 11303 from @joroKr21"

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

Now, when calling `Stream.fromIterator` one only has to specify the effect type. Instead of also having to specify the type of the elements inside the iterator, which IMHO was very pointless.

Adding the Partially-Applied trick to Stream.fromIterator

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpec.scala
io/src/main/scala/fs2/io/file/file.scala
io/src/test/scala/fs2/io/file/BaseFileSpec.scala
io/src/test/scala/fs2/io/file/FileSpec.scala

Wrap up `getDirectoryStream(...)` and `walk(...)`  `java.nio.file.Files` into nice streams while taking care of resource management, blocking I/O and exceptions.
Implements parts of #1533, complementary to #1540.

Add streams for entries of directories & file trees

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

The `Sync` is only needed in the call to `suspend`, to recur through the `GetScope` case.

No Sync for compileLoop

---

core/shared/src/main/scala/fs2/internal/FreeC.scala

In the FreeC datatype, the Bind constructor represents the case of a `bind` or `flatMap` operation in a free monad constructor: it takes the step `FreeC[F, A]`, and the continuation of what to do with the result. Currently, the implementation represents that continuation using a value of type `Function1`. In Scala there is another way to represent that a record has a function attached: by declaring an abstract method, and using inheritance as a form of parameterisation.
- This commit changes the Bind case class to an abstract class with an abstract `cont` method, which represents that continuation. This may avoid the allocation and indirection of `Function1` instances.
- Because we are using method calls instead of functions, and because a delegated call from a `Bind` object to another …

FreeC.Bind: use method for continuations

---

benchmark/src/main/scala/fs2/benchmark/FreeCBenchmark.scala
core/shared/src/main/scala/fs2/internal/FreeC.scala

The internal `FreeC` includes an implicit extension class `InvariantOps`, with a method `run` for running a `FreeC`. As it turns out, this method is only ever used in the benchmarks, not to implement Stream or Pull. Therefore, we can move it to that package.

Move InvariantOps to benchmarks.

---

core/shared/src/main/scala/fs2/internal/FreeC.scala

Back-port of #1528 from `series/1.1` to `series/1.0`

Backport "Bind use methods no functions" to series/1.0

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/internal/FreeC.scala

Since `FreeC` is a private type, its type-class instances are of no use.
All we need is the bracketCase method, because it is used in the actual instances of `Pull`.

Remove the instance of Sync for FreeC.

---

.scalafmt.conf
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

Add Stream.evals, evalSeq

---

README.md

VinylDNS is an open source project that processes a lot of DNS changes.  VinylDNS leverages FS2 in order to protected the DNS backends from getting overwhelmed or perhaps DDoS'd as this would be disastrous for our enterprise.

Adding vinyldns to README

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

Given that the suspend method of the `Algebra` object simply redirects to that of `FreeC`, we may save the "middle man". 
This is different from other methods, where it has to add the `Algebra[]` parameterisation.

Unfold Algebra.suspend.

---

core/shared/src/main/scala/fs2/Stream.scala

As mentioned in #1582, using `Stream.emits(foo.toList)` will be much faster for lists than `foldMap` when used with a list or structure like Chain (I suppose it'll still depend on how the Chain is built and so on, but users can optimize for their specific use-cases themselves).
Also closes #1571

Optimize `evals` for lists

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

These three combinators behave like `bracket`, `bracketCase`, and `onFinalize` did in 1.0.5. One nice property of having these three operations is that we won't run in to a situation where someone was relying on the 1.0.5 behavior and there's no way to get it back in 1.1.0.

Added bracketWeak, bracketCaseWeak, and onFinalizeWeak to allow scope-less resource management

---

.travis.yml
core/shared/src/main/scala/fs2/Stream.scala
sbt

Apparently master had some scalafmt edits it needed made. 
The sbt file became outdated, and 2.12.9 is supported so seems good to get into CI.

Update Scala and SBT Version where outdated

---

core/shared/src/main/scala/fs2/Stream.scala

Just a convenience to allow people to work with streams rather than with `Pull` when they really just want an easy stream constructor

Add combinator unfoldLoopEval

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/CompileScope.scala
io/src/main/scala/fs2/io/file/FileHandle.scala
io/src/main/scala/fs2/io/file/file.scala
io/src/main/scala/fs2/io/file/pulls.scala

`Stream.bracketCancellable` and `Stream.bracketCaseCancellable` allowed early, manual finalization of resources. Upon invoking the finalizer, the internal resource would be cleaned up, ensuring we don't leak references to already invoked finalizers. Now that we introduce a scope for each `bracket`, folks would expect that invoking cancelation of this case also closes the dedicated scope -- i.e., we don't leak scopes either. Instead of implementing this, I'd like to remove these operations instead. There were no tests for these operations and they were very rarely used. Searching GitHub shows no GH hosted open source projects use either operation.
Similarly, `Pull.acquireCancellable` provided a mechanism to manually invoke finalizers. I added this back in #662 to fix resource leaks, but …

Removed Stream.bracketCancellable and Pull.acquire*

---

benchmark/src/main/scala/fs2/benchmark/FreeCBenchmark.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/FreeC.scala

The subclasses of Algebra, like Output, Eval, or Acquire,
were private to the Algebra object, but that is private to fs2.
Since we no longer have the nested types, we can remove and unfold
the internal factory methods, and just call the case classes.

Algebra: open visibility of Algebra subclasses 

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

Stream.evalFilter

---

core/shared/src/main/scala/fs2/Stream.scala

I can't see any unit test related to the `uncons*` method? Shall this one follow the rule as well

Add unconsNonEmpty (#1527)

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

A recent PR #1619 added `evalFilter` and `evalFilterAsync`, here I'm added their cousins `evalFilterNot` and `evalFilterNotAsync`.
This is an optimisations instead of doing something like
```
_.evalFilter(foo.map(!_))
```
we simply do the more obvious
```
_.evalFilterNot(foo)
```
Only issue I see is the name of `evalFilterNotAsync` being bad. But it's follows the same pattern so not sure what else to call it...
P.S. I am expecting the tests to fail on this first commit. Specifically hoping only one of them fails and I'll fix it once it does.

Add `evalFilterNot` and `evalFilterNotAsync`

---

README.md

Update documentation with new library which support Ftp / Ftps / SFtp

update documentation - section project

---

io/src/main/scala/fs2/io/io.scala
io/src/test/scala/fs2/io/IoSpec.scala

I still need to finalize the unit tests - I copied what was in my gist with minor adaptations, needs cleaning still
Close #1641

Add `readOutputStream` combinator in fs2-io

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

Thanks to @marcodippy for bringing this regression up here: https://github.com/functional-streams-for-scala/fs2/pull/1574#issuecomment-541148263

Changed handleErrorWith to guarantee resource finalization (again)

---

.travis.yml
benchmark/src/main/scala/fs2/benchmark/FreeCBenchmark.scala
build.sbt
core/jvm/src/main/scala/fs2/internal/ThreadFactories.scala
core/jvm/src/test/scala/fs2/CompressSpec.scala
core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/shared/src/main/scala-2.12-/fs2/CollectorPlatform.scala
core/shared/src/main/scala-2.13+/fs2/CollectorPlatform.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Collector.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/CompileScope.scala
core/shared/src/main/scala/fs2/internal/FreeC.scala
core/shared/src/main/scala/fs2/text.scala
core/shared/src/test/scala/fs2/ChunkQueueSpec.scala
core/shared/src/test/scala/fs2/ChunkSpec.scala
core/shared/src/test/scala/fs2/Fs2Spec.scala
core/shared/src/test/scala/fs2/StreamPerformanceSpec.scala
core/shared/src/test/scala/fs2/StreamSpec.scala
core/shared/src/test/scala/fs2/concurrent/TopicSpec.scala
core/shared/src/test/scala/scalacheck/GeneratorCompat.scala
io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/main/scala/fs2/io/tcp/SocketGroup.scala
io/src/main/scala/fs2/io/udp/AsynchronousSocketGroup.scala
io/src/test/scala/fs2/io/file/FileSpec.scala
io/src/test/scala/fs2/io/file/WatcherSpec.scala
io/src/test/scala/fs2/io/tcp/SocketSpec.scala
reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamSubscriber.scala
reactive-streams/src/test/scala/fs2/interop/reactivestreams/StreamUnicastPublisherSpec.scala

Fixes #1654
This PR introduces an overload of `.compile.to` that takes a `Collector[O]`. Best explained via usages:
```scala
s.compile.to(List)
s.compile.to(Array)
s.compile.to(Map)
s.compile.to(Chunk)
s.compile.to(ByteVector)
```
I deprecated `.compile.{toMap, toChunk}` as they aren't often used and their functionality is provided by the above. I left `.compile.string` b/c `String` doesn't have a companion object, making `s.compile.to(String)` impossible. I left `toList` and `toVector` undeprecated as they are used a lot and forcing folks to change syntax seemed hostile. Finally, I left `.to[C]` undeprecated because Scala's deprecation checker has a bug which flags uses of `.to(collector)` as deprecated calls despite only type param version being deprecated.
To build a custom collector, …

Added alternative compile.to syntax, providing more efficient and uniform collection building

---

benchmark/src/main/scala/fs2/benchmark/StreamBenchmark.scala
core/shared/src/main/scala/fs2/Stream.scala

Some changes involving the `Stream.range` factory method: 
- We introduced a small benchmark that involves creating a Stream of integers,  using the `range` operation, and then folding that Stream by adding those numbers. 
- We change the implementation of `Stream.range` to avoid using `unfold`, which is  too general (wide) for what we need in the `range` method. 
We have measured the results of this improvement with the given benchmark, using the command `jmh:run -f 1 -i 8 -wi 4 .*StreamBenchmark*. -prof gc`, and they show a reduction in memory allocation (`gc.alloc.rate.norm`) going from 2.5% for the small case `N=1`, to 4.2% for the `N=4096` case, and up to 5.2% for the large case `N=67108863`.

Stream.range: add benchmark and improve implementation

---

site/src/main/tut/ecosystem.md

I am proposing the addition of **neotypes** to the library list on the ecosystem section.
Even though **neotypes** is not directly built using **cats-effect** nor **fs2**, it does provides two modules to integrate with these two.
Let me know if I should make something else.

Request: Add neotypes to the library ecosystem

---

README.md

README mentions other Scala versions but not 2.13. Somebody could be mislead that it is not supported, hence these small changes.

Mention Scala 2.13 in README

---

.travis.yml
build.sbt

Lightbend released the last version of Scala 2.11 almost two years ago, and both `cats` and `cats-effect` are also dropping it.
https://github.com/typelevel/cats-effect/pull/713
https://github.com/typelevel/cats-effect/issues/667
https://github.com/typelevel/cats/pull/3051

Drop support for Scala 2.11

---

core/shared/src/main/scala/fs2/Stream.scala

As per discussion on gitter:
> @CremboC 
> Just looking at the profiler for an fs2 app, and looking specifically at the groupWithin function.. It seems like just Chain.toList (which I believe only happens here: https://github.com/functional-streams-for-scala/fs2/blob/master/core/shared/src/main/scala/fs2/Stream.scala#L1386) takes up 36% of the time, isn't that a bit crazy?
> @mpilquist 
> I’d try replacing that Chain[Chunk[O]] with a Chunk.Queue[O] — I bet it performs much, much better
Now I don't actually know if this is exactly what @mpilquist meant, but it does compile and tests pass, so maybe? If not, please let me know if there's anything better to be done here!
I haven't tested the performance yet. I'll see if there's any performance gains like that and report back.

Optimise groupWithin to use Chunk.Queue instead of Chain

---

benchmark/src/main/scala/fs2/benchmark/ChunkBenchmark.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Stream.scala

I ran `jmh:run -i 3 -wi 3 -f1 -t1 fs2.benchmark.ChunkBenchmark` for benchmarking.
I tried three options:
- before (current implementation)
- after (concatting done via `Array[Any]`)
- sizeHint (concatting done via `Array[Any]` + a `totalSize` parameter that avoids doing the `foldLeft` to determine the total size)
Here are the results:
```
before
[info] Benchmark              (chunkCount)  (chunkSize)   Mode  Cnt        Score        Error  Units
[info] ChunkBenchmark.concat             1           16  thrpt    3  3284142.155 ± 126490.513  ops/s
[info] ChunkBenchmark.concat             1          256  thrpt    3   473260.526 ±   7160.038  ops/s
[info] ChunkBenchmark.concat             1         4096  thrpt    3    32789.284 ±   1017.692  ops/s
[info] ChunkBenchmark.concat            20 …
```

Optimise Chunk.concat

---

benchmark/src/main/scala/fs2/benchmark/StreamBenchmark.scala
core/shared/src/main/scala/fs2/Chunk.scala

Sort of related to the previous PR (#1712)
Benchmark results:
```
sliding before
[info] Benchmark                       Mode  Cnt     Score     Error  Units
[info] StreamBenchmark.sliding_1      thrpt    3  2896.600 ± 125.799  ops/s
[info] StreamBenchmark.sliding_10     thrpt    3  2642.172 ± 102.039  ops/s
[info] StreamBenchmark.sliding_100    thrpt    3  2576.285 ±  30.050  ops/s
[info] StreamBenchmark.sliding_1000   thrpt    3  2488.486 ±  50.568  ops/s
[info] StreamBenchmark.sliding_10000  thrpt    3  2119.792 ± 102.849  ops/s
sliding after
[info] Benchmark                       Mode  Cnt     Score     Error  Units
[info] StreamBenchmark.sliding_1      thrpt    3  3234.381 ±  85.597  ops/s
[info] StreamBenchmark.sliding_10     thrpt    3  2853.583 ± 140.551  ops/s
[info] …
```

Use preallocated array instead of mutable.Buffer in more places

---

build.sbt
core/shared/src/main/scala/fs2/Collector.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/concurrent/Balance.scala
core/shared/src/test/scala/fs2/CompilationTest.scala
io/src/test/scala/fs2/io/IoSpec.scala

`.to` was overloaded -- one took the `Collector` and the other took an implicit factory. When the target type was known, the 2.12 compiler was picking the factory overload. To fix, I removed the old overload -- or rather, made it `private[Stream]` so that it cannot be called but it stays around for binary compatibility reasons.
Note that in practice, any `s.compile.to[C]` can be written as `s.compile.to(C)` b/c `Collector` can be implicitly instantiated from any `Factory`. Only case where that's not true is when `C` doesn't implement `Factory` directly and instead, there's some implicit factory in scope.

Fixed #1709 - .to(Collector) syntax fix for 2.12

---

build.sbt
core/jvm/src/main/scala/fs2/compress.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

The internal methods `fromFreeC` and `get` of Pull and Stream were needed at first to convert between the wrapped `FreeC` and them. This conversion was needed due to the difference between `FreeC` invariant type-parameter `F[_]`, and Stream/Pull covariant `+F[_]`. Now that `FreeC` is also covariant on F[_], we can drop these converters. Also, a few uses of `covary` and extra type parameters can be simplified as well.
Since these methods were private to fs2, but not entirely private, it turns out that Mima detects them as missing methods. We have to mark them as exceptions in the build

Stream/Pull Internals: purge fromFreeC/get converters.

---

LICENSE
core/shared/src/main/scala/fs2/text.scala
core/shared/src/test/scala/fs2/TextSpec.scala

Adapted the implementations from scodec-bits for streaming / continuation.

Added text.base64Encode and text.base64Decode

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/test/scala/fs2/ChunkSpec.scala

@CremboC Could you review? Trick here is to avoid specializing `toArray` on `Boxed` -- it was making a bad assumption that the `ClassTag[O2]` passed to `toArray` was the same as used to create the underlying array.

Fixed ClassCastException in Chunk#toArray, fixes #1745

---

core/shared/src/main/scala-2.12/fs2/CollectorPlatform.scala
core/shared/src/test/scala/fs2/CompilationTest.scala

Brought up in Gitter: https://gitter.im/functional-streams-for-scala/fs2?at=5e315e3a40da694c5ee6bf85
`.compile.to(Set)` doesn't work on Scala 2.12. This PR fixes it by adding a `Collector` instance for any `SetFactory`.

Fixed Stream#to(Set) on 2.12

---

io/src/main/scala/fs2/io/tls/TLSParameters.scala
io/src/test/scala/fs2/io/tls/TLSParametersSpec.scala

Calling `setWantClientAuth` clears `setNeedClientAuth` and vice versa.  Since `setWantClientAuth` is called last, `getNeedClientAuth` is never true.
Changes so if `needClientAuth` is true, it is set on `SSLParameters`, regardless of `wantClientAuth`.  If `needClientAuth` is false, `wantClientAuth` wins.  The default of both `SSLParameters` and `TLSParameters` is that neither is set.

Support setting needClientAuth with TLSParameters

---

core/shared/src/main/scala/fs2/text.scala

Using `text.base64Encode` on JDK8 throws:
```scala
java.lang.NoSuchMethodError: java.nio.CharBuffer.flip()Ljava/nio/CharBuffer;
at fs2.text$.encode$1(text.scala:369)
at fs2.text$.$anonfun$base64Encode$1(text.scala:380)
at fs2.text$.$anonfun$base64Encode$1$adapted(text.scala:378)
at fs2.Pull$.$anonfun$flatMap$1(Pull.scala:51)
```
This is another instance of #1357.

Fixed NoSuchMethodError in text.base64Decode when run on JDK8

---

site/docs/guide.md

I suppose it's a historical leftover, but `Sync` doesn't offer any way to `run` an effect, so I'm just removing that. `unsafeRunSync` being specific to IO is mentioned before.

Remove misleading note from guide

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

On a day-to-day job basis we often use such a combinator for `Stream`, allowing us to time out and interrupt streams that do not complete within given `FiniteDuration`. Such a combinator may be useful as a part of the `Stream` itself

Add withTimeout combinator

---

io/src/main/scala/fs2/io/file/file.scala
io/src/test/scala/fs2/io/file/FileSpec.scala

Part of #1533. 
~Just a draft PR for now.~ I wasn't completely sure if this was the sort of intended implementation or if should just be a wrapper around the `nio` functions and leave removing files/directories to the user (or something else). Happy to close if this is quite far off from what was intended.

Add temporary files and directories to io module

---

io/src/main/scala/fs2/io/tcp/SocketGroup.scala
io/src/test/scala/fs2/io/tcp/SocketSpec.scala

I had to tune the test parameters (message size and write buffer size) to make the test consistently fail on my machine without this change - hopefully it does so on other machines too 🙂

Prevent concurrent writes to fs2-io TCP socket from causing WritePendingException 

---

core/shared/src/main/scala/fs2/Chunk.scala

Override Chunk.BufferChunk.iterator to return buffer.iterator.
Chunk.iterator reasonably assumes that the underlying collection is indexed and iterates through the chunk with sequential calls to apply(), but Chunk.BufferChunk can be created from a ListBuffer which has a non-constant time apply() implementation. Because Chunk.flatMap makes use of Chunk.iterator, flat mapping over a ListBuffer backed BufferChunk has high cost complexity. The simplest solution is to override BufferChunk's iterator implementation with the iterator implementation of the underlying buffer.
Alternatively or subsequently, there may be a gain in having different chunk implementations for Buffer and IndexedBuffer.

Override Chunk.BufferChunk.iterator to return buffer.iterator

---

core/jvm/src/test/scala/fs2/CompressSpec.scala
core/jvm/src/test/scala/fs2/HashSpec.scala
core/shared/src/test/scala/fs2/ChunkQueueSpec.scala
core/shared/src/test/scala/fs2/ChunkSpec.scala
core/shared/src/test/scala/fs2/CompositeFailureTest.scala
core/shared/src/test/scala/fs2/Fs2Spec.scala
core/shared/src/test/scala/fs2/HotswapSpec.scala
core/shared/src/test/scala/fs2/PullSpec.scala
core/shared/src/test/scala/fs2/StreamPerformanceSpec.scala
core/shared/src/test/scala/fs2/StreamSpec.scala
core/shared/src/test/scala/fs2/TextSpec.scala
core/shared/src/test/scala/fs2/concurrent/BalanceSpec.scala
core/shared/src/test/scala/fs2/concurrent/BroadcastSpec.scala
core/shared/src/test/scala/fs2/concurrent/QueueSpec.scala
core/shared/src/test/scala/fs2/concurrent/TopicSpec.scala
io/src/test/scala/fs2/io/IoSpec.scala
io/src/test/scala/fs2/io/JavaInputOutputStreamSpec.scala
io/src/test/scala/fs2/io/file/FileSpec.scala
io/src/test/scala/fs2/io/tcp/SocketSpec.scala
io/src/test/scala/fs2/io/tls/DTLSSocketSpec.scala
io/src/test/scala/fs2/io/tls/TLSParametersSpec.scala
io/src/test/scala/fs2/io/tls/TLSSocketSpec.scala
io/src/test/scala/fs2/io/udp/UdpSpec.scala
reactive-streams/src/test/scala/fs2/interop/reactivestreams/PublisherToSubscriberSpec.scala

Fixes #1764
This PR replaces all `should` matchers in all tests at one go.
It may be a lot of changes to review... If necessary, I could break this PR into few smaller ones.

Replace ShouldMatchers in tests with assertions

---

io/src/test/scala/fs2/io/file/FileSpec.scala
io/src/test/scala/fs2/io/tcp/SocketSpec.scala

Mops up a few `unsafeRunSync()`s, too.

Fix compilation errors in FileSpec and SocketSpec

---

README.md

There are two projects with the same name that provide Apache Kafka bindings for fs2. I feel like both should be included in the list of projects that use fs2 because that is something that puzzled me as a new user. I included the projects in lexicographical order, so the ordering should not be interpreted as a matter of personal preference.

Include fd4s/fs2-kafka in the list of projects that use fs2

---

benchmark/src/main/scala/fs2/benchmark/StreamBenchmark.scala
core/shared/src/main/scala/fs2/Stream.scala

```
[info] Benchmark                   (n)   Mode  Cnt       Score       Error  Units
[info] StreamBenchmark.evalMap      10  thrpt    3  240385.919 ± 33389.928  ops/s
[info] StreamBenchmark.evalMap     100  thrpt    3   39834.763 ±  3967.529  ops/s
[info] StreamBenchmark.evalMap    1000  thrpt    3    4105.834 ±   867.816  ops/s
[info] StreamBenchmark.evalMap   10000  thrpt    3     212.373 ±  1205.824  ops/s
[info] StreamBenchmark.evalMaps     10  thrpt    3  230966.575 ± 89764.693  ops/s
[info] StreamBenchmark.evalMaps    100  thrpt    3   71055.648 ± 10100.526  ops/s
[info] StreamBenchmark.evalMaps   1000  thrpt    3    9802.130 ±   795.724  ops/s
[info] StreamBenchmark.evalMaps  10000  thrpt    3     881.018 ±    96.295  ops/s
```
Sorry, I accidentally switched a tab Chrome on the …

Add `evalMapChunk` and `evalTapChunk` which operate on chunks

---

README.md
site/docs/ecosystem.md

https://github.com/lendup/fs2-blobstore/ has moved to https://github.com/fs2-blobstore/fs2-blobstore, ref https://github.com/lendup/fs2-blobstore/issues/61
Update links in docs
@gafiatulin @rolandomanrique @matthewgraf

Update repository for fs2-blobstore

---

core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/text.scala
core/shared/src/test/scala/fs2/CompilationTest.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

Fixes #1838
A pipe is invariant so we never should have supported `covary`, either implicitly or explicitly. The minimization in #1838 exposes the variance cheating. :)

Fix #1838 soundness bug that allowed a pure pull to be used on effectful streams

---

core/shared/src/main/scala/fs2/Stream.scala

Write that there is no guarantee regarding the stream
from which the last element was generated.

Detail scaladoc of Stream.mergeHaltL/R

---

core/jvm/src/main/scala/fs2/compression.scala

Improve compression.gunzip to eagerly stream chunks while the inflater is unfinish before validating the trailer.
See: https://github.com/functional-streams-for-scala/fs2/issues/1831
Benchmark of compression.gunzip not significantly changed.
Before:
[info] Benchmark                    (withRandomBytes)   Mode  Cnt     Score    Error  Units
[info] CompressionBenchmark.gunzip               true  thrpt   25  2697.478 ± 23.129  ops/s
[info] CompressionBenchmark.gunzip              false  thrpt   25   472.732 ±  1.771  ops/s
After:
[info] Benchmark                    (withRandomBytes)   Mode  Cnt     Score    Error  Units
[info] CompressionBenchmark.gunzip               true  thrpt   25  2686.658 ± 22.094  ops/s
[info] CompressionBenchmark.gunzip              false  thrpt   25   470.444 ± …

Improve compression.gunzip to eagerly stream chunks while the inflater is unfinish before validating the trailer.

---

site/docs/concurrency-primitives.md
site/docs/guide.md

Fix relative documentation paths by using a `.html` extension as opposed to `.md` one.
The relative `.md` extensions could work as outlined [here](https://github.com/functional-streams-for-scala/fs2/issues/1836) but that would involve updating a Jekyll instance with a new plugin which could get messy. 
I've based this fix on the Doobie [docs](https://tpolecat.github.io/doobie/docs/18-FAQ.html) which use the same approach.

Fix relative document paths

---

core/shared/src/main/scala/fs2/Stream.scala

Add Stream#chunkAll

---

README.md

This just adds another project that uses FS2 for Kafka in the README.

Add in Kafka4s under Projects using FS2

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/test/scala/fs2/ChunkSpec.scala

Adds zipWithIndex function on `Chunk`, similar to that of `Stream`.
e.g.
```
fs2.Chunk("The", "quick", "brown", "fox").zipWithIndex.toList
res0: List[(String, Int)] = List((The,0), (quick,1), (brown,2), (fox,3))
```

adds zipWithIndex function on Chunk

---

io/src/main/scala/fs2/io/tcp/SocketGroup.scala

Threads produced by the `nonBlockingThreadFactory` are used in a non-blocking fashion, but their names suggest otherwise. Let's change the prefix to `fs2-socket-group-non-blocking` to align with the actual usage pattern.

Adjust thread names of tcp.SocketGroup's nonBlockingThreadFactory

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

Fixes #936.
This PR adds the elusive `yip` operator, under the more modern name of `parZip`, with the following semantics:
- combines elements pairwise
- executes effects concurrently
- no side is allowed to get ahead by more than one element
- terminates when either stream terminates
The key insight of the implementation is that `parZip` is a special case of `merge`, where the two sides wait on each other.
I've also added `parZipWith`, and I'm considering `parZipRight` and `parZipLeft`, though I would probably not add `parZipAll` since it requires changing the implementation and it's rare.
Testing has proved a bit challenging, I have added two alternatives for the same test (marked -1 and -2), I'd appreciate input on which one to keep

Add parZip

---

build.sbt
io/src/main/scala/fs2/io/tls/DTLSSocket.scala
io/src/main/scala/fs2/io/tls/InputOutputBuffer.scala
io/src/main/scala/fs2/io/tls/TLSContext.scala
io/src/main/scala/fs2/io/tls/TLSEngine.scala
io/src/main/scala/fs2/io/tls/TLSSocket.scala
io/src/test/scala/fs2/io/tls/TLSSocketSpec.scala

The key part of the fix is the guard in `TLSEngine.read` that checks if a session is active and if not, handshakes before reading. I think a similar deadlock can still occur if a mid-session renegotiation is requested while an application level read is pending. Though TLS1.3 has dropped support for renegotiation.

Fix #1873 - deadlock in TLSEngine

---

README.md
site/docs/ecosystem.md

Some projects were present in the README file but not in the Ecosystem page and vice-versa. This PR eliminates this duplication. The list of projects using FS2 is now under `ecosystem.html` and it is linked from the README file.

Add neutron & re-organize list of projects

---

build.sbt
io/src/main/scala/fs2/io/tls/InputOutputBuffer.scala
io/src/main/scala/fs2/io/tls/TLSEngine.scala

Followup to https://github.com/functional-streams-for-scala/fs2/pull/1896.
- Update test for completed handshake to not use `isValid` on `SSLSession`. On JDK 1.8.0_192, after the handshake completes with postgres, `engine.getSession.isValid` returns false and `engine.getSession.getId` returns an empty array. Same program works fine on JDK 11. This was tricking `TLSEngine.read` in to thinking it needed to handshake again, ad infinitum. Switched to comparing cipher suite to `SSL_NULL_WITH_NULL_NULL`, which is the documented cipher suite prior to handshake completion.
- Respect maxBytes on TLSSocket.read. This is needed b/c the sample program makes the correct assumption that calling `socket.read(n)` will return a chunk with <= n bytes, but `TLSEngine` was violating that.
Most of the diff is …

TLS handshaking issues with Postgres

---

io/src/main/scala/fs2/io/tls/TLSEngine.scala

I was working with @tpolecat on testing Postgres TLS integration in skunk (#1897). While it's working now, Rob noticed lots of buffer underrun events during unwrapping as a result of requesting a single character from the `TLSSocket`. This turned in to a call to `socket.read(1)`. Consequently, the `TLSSocket#read1` implementation would read a single byte at a time from the underlying raw socket. This would continue until enough individual bytes had been read and queued that an unwrap operation could succeed.
In this PR, we guard against very small `maxBytes` by requesting up to `session.getPacketBufferSize` bytes from underlying socket when `maxBytes` is less than that value.
The result of the Postgres integration now completes with no underrun:
```scala
[info] Writing 8 byte(s).
[info] …
```

Improve efficiency of network reads in TLSEngine

---

core/shared/src/main/scala-2.13/fs2/CollectorPlatform.scala
core/shared/src/test/scala-2.13/fs2/ArraySeqCollectorSpec.scala

This PR adds a `Collector` for `scala.collection.immutable.ArraySeq` where a `ClassTag` is available.
Support for untagged `ArraySeq` already exists via `ArraySeq.untagged`, eg:
```scala
Stream.range(1, 5).compile.to(ArraySeq.untagged)
```
`ArraySeq`s created this way will fail to take advantage of the specialised implementations provided for arrays of primatives.
The immutable `ArraySeq` is newly added in Scala 2.13. It is an immutable wrapper over a bare array with specialised implementations for primitives. As such it is well suited to the kinds of performance-sensitive uses for which fs2 is commonly used.

Collector support for ArraySeq

---

core/shared/src/main/scala/fs2/concurrent/Queue.scala
core/shared/src/test/scala/fs2/concurrent/QueueSpec.scala

This PR add  None-terminated circularBuffer for Queue
https://github.com/functional-streams-for-scala/fs2/issues/1621

Add Queue.circularBufferNoneTerminated

---

site/docs/ecosystem.md

I've recently published a CSV parser based on FS2 and I would be grateful for the possibility to add it to the list of libraries in FS2 ecosystem.

Add information about FS2-based library

---

core/shared/src/main/scala/fs2/Stream.scala

#1912 : forgot to remove this subtype match for `Token`

Fix: redundant cast, forgotten in #1912,

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

`translate0` is only used in the translate method, so no need to keep it separate. This removes an extra definition.

Small cleanup in FreeC: merge translate, translate0

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

There are several places in the code in which we use pairs of elements
that are just the components of a `Result.Interrupted`, and in which
in fact come from one. So we can instead start using this class.

FreeC: use the Result.Interrupted a bit about.

---

io/src/main/scala/fs2/io/tcp/SocketGroup.scala

I believe this step unnecessarily copies when we just wish to write what we have available.
I might be wrong though.

Remove toBytes intermediate

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

Resolves #1925.
Straightforward implementation reusing other combinators. This is my first contribution to the project. Please let me know if I have missed something.

Add evalMapFilter combinator

---

core/jvm/src/main/scala/fs2/compression.scala
core/jvm/src/main/scala/fs2/internal/AsyncByteArrayInputStream.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/AcquireAfterScopeClosed.scala
core/shared/src/main/scala/fs2/internal/SizedQueue.scala

This PR makes a bunch of adjustments to the source of coreJVM project so that it cross compiles against 2.12, 2.13, and latest Dotty nightly build. Note Dotty 0.25.0-RC2 has a bug that prevents its use with FS2 (https://github.com/lampepfl/dotty/pull/9275).
In particular, Dotty is much better w.r.t. detecting soundness issues. I fixed as many as possible without casts but had to add some, in particular in `Pull` -- some of those seem to be Dotty limitations but I'm not certain about that. Some of the others are definitely us doing dodgy things.

Dotty source compatibility

---

benchmark/src/main/scala/fs2/benchmark/ChunkBenchmark.scala
core/shared/src/main/scala/fs2/Chunk.scala

I noticed that `Stream.evalMapChunk`, which is a common operation for me, goes through `Chunk.traverse`, however that is implemented in a pretty expensive way: via foldRight which wraps everything in another layer of Eval.
I instead implemented a tree-based approach (to keep stack safety) but without wrapping in another Eval layer.

Optimize Chunk traverse

---

benchmark/src/main/scala/fs2/benchmark/TextBenchmark.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/text.scala
core/shared/src/test/scala/fs2/ChunkQueueSpec.scala

This does four things:
1. adds Chunk.Queue.startsWith so we can be a bit more precise when checking for utf8 byte order mark
2. be miserly in internal methods with allocations and use null instead of Option (avoid allocation of Some on a loop).
3. use a Builder to avoid having to return a tuple and to reverse a list in an internal method.
4. avoid fold on an internal loop and just write out the while loop.

Add some optimizations to utf8 decoding

---

core/shared/src/main/scala/fs2/Chunk.scala

this is a followup to #1952 
In that, I used a binary tree to implement Chunk.traverse. This gives stack safety, but it doesn't make it faster. I observed later and noted in https://github.com/typelevel/cats/issues/3517 that nothing requires the tree to be binary.
So, here, I use a tree with 128 children, and in all the internal nodes, I use `map2Eval` which allows short-circuiting and laziness for applicative instances that can avoid evaluating one side in some cases.
This results in a significant speed-up over the foldRight based implementation:
```
[info] Benchmark                       (chunkCount)  (chunkSize)   Mode  Cnt        Score       Error  Units
[info] ChunkBenchmark.traverse                    1           16  thrpt    6  1694967.533 ± 28309.177  ops/s
[info] …
```

Optimize Chunk.traverse take 2

---

build.sbt
core/shared/src/test/scala-2.13/fs2/ChunkPlatformSuite.scala
core/shared/src/test/scala/fs2/BracketSuite.scala
core/shared/src/test/scala/fs2/ChunkSuite.scala
core/shared/src/test/scala/fs2/PullSuite.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala
core/shared/src/test/scala/fs2/StreamConcurrentlySuite.scala
core/shared/src/test/scala/fs2/StreamInterruptSuite.scala
core/shared/src/test/scala/fs2/StreamSwitchMapSuite.scala
io/src/main/scala/fs2/io/file/Watcher.scala
io/src/test/scala/fs2/io/IoSuite.scala
reactive-streams/src/test/scala/fs2/interop/reactivestreams/CancellationSpec.scala

Rather than waiting for sbt-doctest to implement support for munit, this PR just changes sbt-doctest to use ScalaCheck instead of ScalaTest.
This PR also makes a few additional syntax changes due to recent Dotty changes -- in particular, it seems lambdas without parens are no longer supported. E.g. map { x: Int => is no longer allowed.

Remove ScalaTest dependency and more dotty source compat

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala

Added `withFilter` as an alias to `filter` to `Stream` to enable filtering inside of for comprehensions.
Closes #1971

Add `withFilter` to Stream in order to filter in for comprehensions #1971

---

core/shared/src/main/scala/fs2/concurrent/Queue.scala

Reading through queue and noticed `a` was used for a `B` type.

Fixed typo in queue arguments.

---

build.sbt
core/shared/src/test/scala/fs2/Fs2Suite.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala
core/shared/src/test/scala/fs2/StreamZipSuite.scala
io/src/test/scala/fs2/io/IoSuite.scala

Note we'll need to undo some of this on the CE3 branch as the compat lib is only published for CE2.

Use munit-cats-effect library

---

io/src/main/scala/fs2/io/tls/TLSSocket.scala

I have no idea how to write a test for this but it fixes the problem I'm seeing in at https://github.com/tpolecat/skunk/issues/238.

fix over-read in TLSSocket.readN

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamMergeSuite.scala

Fixes functional-streams-for-scala/fs2#1987

---

core/shared/src/main/scala/fs2/Stream.scala

- Extract functions for ending "fork" and queue operations
- Write chain of flatMap into a for comprehensions.

Stream - parJoin: small rewrites for readability.

---

core/shared/src/main/scala/fs2/Stream.scala

We restructure the code implementation of `parEvalMap`
to make it more readable:
- Top-level, we use `Stream.eval(--).flatten`.
- We extract the function for enqueuing each effect-action
- We use for comprehensions to reduce nesting.
_Note_ Since we are replacing a few `Stream.eval(--).flatMap` at the beginning with the use of a for comprehension in `F`, I am not sure if there is any change in the use of scopes that could be a problem. I do not expect it, but cannot be certain.

Stream - parEvalMap: rewrite for readability.

---

core/shared/src/main/scala/fs2/Stream.scala

Backports changes in https://github.com/typelevel/fs2/pull/1997 from the `develop` branch to the `main` branch
In the `Stream.merge` method, port some changes from the `develop` branch to the `main` branch, to reduce `diff` distance between those branches, and to merge https://github.com/typelevel/fs2/pull/1832 into the `main` first and then `develop` branches.

Backport: rewrite merge for readability.

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala

Improves performance of `Stream.fromIterator` and `Stream.fromBlockingIterator` by creating chunks of requested size, as described in #2010.

Create chunks in Stream.fromIterator (#2010)

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala
io/src/main/scala/fs2/io/file/file.scala

I think that in reference to #2010 we can make `fromIterator` in the 3.x series chunk-aware from beginning and similar to most other methods which create chunks, do not provide any default value. Because the code for blocking and non-blocking `PartiallyAppliedFromIterator` is nearly identical, I would suggest to merge it into single class.

Create chunks in Stream.fromIterator and Stream.fromBlockingIterator

---

site/docs/guide.md

- Use `NoneTerminatedQueue` now that it exists
- Add some more comments aimed at new-to-functional-effects readers

Update "Asynchronous effects" section of the guide

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala

Consider this synthetic example:
```
import fs2.Stream
def getFraction(n: Int): Option[Float] = if(n == 0) None else Some(1.toFloat / n)
val stream =
for {
i <- fs2.Stream.repeatEval(IO.delay(Random.nextInt))
fractionOpt = getFraction(i)
fraction1 = Stream.emits(fractionOpt.toList)
fraction2 = Stream.fromIterator(fractionOpt.iterator)
fraction3 = Stream.fromOption(fractionOpt)
fraction <- fraction1
} yield fraction
```
I want to transform the result of the stream with use of `getFraction` method. I've found 2 method to accomplish it: emits, fromIterator. But the most accurate method is fromOption, which seems to be absent from Stream companion object. This PR adds fromOption.

fs2.Stream convenient fromOption method

---

.github/workflows/publish-site.yml
.github/workflows/update-nix-cache.yml
nix/pkgs.nix
shell.nix

In addition to fixing the command to build the microsite, I made some other small changes:
- Add `nix/pkgs.nix` to pin to a specific version of Nixpkgs for reproducibility.
- Add new CI job to update the binary cache when any of the Nix files change.
- Modify `shell.nix` to import packages from `nix/pkgs.nix`.

Fix microsite CI build

---

core/shared/src/main/scala/fs2/Compiler.scala
core/shared/src/main/scala/fs2/Stream.scala

This PR moves the builder creation and finalization in to the `to` method, resulting in `Compiler#apply` being a simple chunky fold. This did require exposing a `Monad[G]` though. Tradeoff seems worth it.

Cleanup Compiler.apply

---

README.md

The current links on the website (and README) point to a rather old version of the documentation, without the new operators.

Bump library version in scaladoc links

---

README.md
io/src/main/scala/fs2/io/file/FileHandle.scala
io/src/main/scala/fs2/io/file/Files.scala
io/src/main/scala/fs2/io/file/ReadCursor.scala
io/src/main/scala/fs2/io/file/WriteCursor.scala
io/src/main/scala/fs2/io/file/file.scala
io/src/test/scala/fs2/io/file/BaseFileSuite.scala
io/src/test/scala/fs2/io/file/FileSuite.scala
io/src/test/scala/fs2/io/file/WatcherSuite.scala

Stuff to address:
- ~`FileHandle` currently can be constructed via `Files[F].open*` or directly via `FileHandle.from*`. Should the `from` constructors be made private or otherwise removed?~
- ~`ReadCursor` and `WriteCursor` have convenience constructors in their companions. Should those be removed or moved to `Files`?~
- ~Is there a better name for `BaseFiles`?~ Renamed to `SyncFiles`
- Docs

Move file operations to a Files[F] tagless interface

---

core/shared/src/main/scala/fs2/internal/CompileScope.scala
core/shared/src/test/scala/fs2/StreamSuite.scala

Includes a minimized test case for the bug reported in #2072.

Fix resource leak that occurs when stream is canceled while a resource is being acquired

---

core/shared/src/main/scala/fs2/internal/CompileScope.scala
core/shared/src/main/scala/fs2/internal/ScopedResource.scala
core/shared/src/test/scala/fs2/StreamSuite.scala

This needs a lot more work but committing what I've found so far. When the resource acquisition completed in `CompileScope#acquireResource`, the wrapper `ScopedResource` instance was getting registered on the containing scope, but the containing scope's state was already closed. Not sure why the test I added yesterday passed though.

Fix for resource leak that occurs when parent scope is closed during resource acquisition

---

core/shared/src/main/scala/fs2/text.scala

Emitting a chunk per string in the input stream can result in huge slow
down if strings are small. Using `mapChunks` we can keep the chunk
structure, resulting in better performances.

Keep chunk structure when encoding text

---

core/shared/src/main/scala/fs2/Stream.scala

Leverage `Stream.emit` in `Monad.pure` implementation instead of `Stream.apply` (which always takes `Seq`).
Conversation it [here](https://gitter.im/functional-streams-for-scala/fs2?at=5f90715aa0a3072b43973c3c)

Slightly optimize Monad.pure for Stream

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

The ViewL operation and trait, which represents loop unrolling,  is only ever used when interpreting or compiling a Stream.
Therefore, we can assume that it onlt works on Pull with Unit as the result type. For this we remove references to it from the Pull class itself. For that:
- Remove the class method `mapOutput` of the Pull class. Instead we write a new method with large match.
- Remove the `asHandler` method of the `Pull` class and expand it in where it was used, at top of compilation.
- Remove nested object ViewL, but make all its subclasses Private to the Pull object.

Restrict Pull.ViewL to Streams (Unit result)

---

io/src/main/scala/fs2/io/file/Files.scala
io/src/test/scala/fs2/io/file/FileSuite.scala

Hello,
Added a couple of small calls to the `Files` capability: `isFile` and `isDirectory`
I opted to make these more granular calls instead of the ability to fetch `BasicFileAttributes` because I wasn't sure if `BasicFileAttributes` is referentially transparent. 
I added `isDirectory` and `isFile` separately (as opposed to implementing one and allowing the other via negation of the implemented one) because according to the [javadoc](https://docs.oracle.com/javase/8/docs/api/java/nio/file/attribute/BasicFileAttributes.html) a path may also be a symbolic link or "other". I did not how to test the other 2 cases however, so I did not implement appropriate methods for them.
Lastly, according to the contributor docs I should run `fmtCheck; test; doc; mimaReportBinaryIssues; docs/mdoc; …

Added isFile and isDirectory to Files

---

io/src/main/scala/fs2/io/file/Files.scala
io/src/main/scala/fs2/io/file/file.scala
io/src/test/scala/fs2/io/file/FilesSuite.scala

Hello.
Made the dir parameter on `tempFile` and `tempDirectory` an `Option[Path]`. Specifying `None` (which is also the default) delegates to using the system's default temp directory. Specifying `Some` works same as it did previously.

Temp file dirs optional for file system default

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

No need to map the 3-tuple to the 2-tuple, if we can just match and ignore the middle element. This should save some FreeC allocations.

FreeC - FlatMapOutput: avoid intermediate Map.

---

core/shared/src/main/scala/fs2/Pull.scala

The definition of flatMapOutput was using the method `uncons`, which
includes a call to `Pull.map` and thus to `Pull.flatMap`, which
can incur extra allocations, all to remove second element of 3-tuple.
We can easy do that in the continuation of the flatMap.

Pull - FlatMapOutput - Remove middle map.

---

core/shared/src/main/scala/fs2/Stream.scala

Noticed some clock drift when looking in to https://github.com/typelevel/fs2/issues/2142
Using @adamw's test program:
Before:
```
Ping! 1067ms
Ping! 2069ms
Ping! 3072ms
Ping! 4077ms
Ping! 5082ms
Ping! 6086ms
Ping! 7090ms
Ping! 8095ms
Ping! 9099ms
Ping! 10103ms
Ping! 11108ms
Ping! 12113ms
Ping! 13117ms
Ping! 14119ms
Ping! 15122ms
Ping! 16126ms
Ping! 17130ms
Ping! 18136ms
Ping! 19141ms
Ping! 20146ms
Ping! 21150ms
Ping! 22155ms
Ping! 23158ms
Ping! 24162ms
Ping! 25167ms
```
After:
```
Ping! 1041ms
Ping! 2005ms
Ping! 3003ms
Ping! 4004ms
Ping! 5001ms
Ping! 6001ms
Ping! 7004ms
Ping! 8003ms
Ping! 9001ms
Ping! 10003ms
Ping! 11002ms
Ping! 12002ms
Ping! 13003ms
Ping! 14002ms
Ping! 15003ms
Ping! 16004ms
Ping! 17005ms
Ping! 18005ms
Ping! 19004ms
Ping! 20000ms
Ping! 21001ms
Ping! 22000ms
Ping! 23002ms …
```

Changed awakeEvery and fixedRate to avoid clock drift

---

README.md

Closes #1824 
There is a challenge with links to Javadocs — they carry versions inside. Do we need to generate them dynamically?

Remove version from README.md

---

core/shared/src/main/scala/fs2/Pull.scala

The implementation of `flatMap` was exposing to the ou
- Introduce a new subtype of `Pull`, which is `flatMapOutput`.
- Interpretation of the `flatMapOutput` is done within the loop-unrolling mechanism. When a `FlatMapOutput` object is found, we direcly create a `View` from it. The `View` issues a `Step` on the stream as its action. 
- For the continuation of those views, we extract a `flatMapOutputCont` function.

Introduce FlatMapOutput constructor.

---

core/shared/src/main/scala/fs2/Compiler.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/concurrent/Broadcast.scala
core/shared/src/main/scala/fs2/concurrent/PubSub.scala
core/shared/src/main/scala/fs2/concurrent/Queue.scala
core/shared/src/main/scala/fs2/concurrent/Signal.scala
core/shared/src/main/scala/fs2/concurrent/Topic.scala
core/shared/src/main/scala/fs2/internal/InterruptContext.scala
core/shared/src/main/scala/fs2/internal/Scope.scala
core/shared/src/main/scala/fs2/internal/ScopedResource.scala
core/shared/src/main/scala/fs2/internal/Unique.scala
core/shared/src/test/scala/fs2/UniqueSuite.scala

cc @ChristopherDavenport 
Looks like we'll be able to replace the fs2 Token with `cats.effect.std.Unique` by pushing construction in to `Compiler.Target`

Prepare for using cats.effect.std.Unique

---

benchmark/src/main/scala/fs2/benchmark/LinesBenchmark.scala
core/shared/src/main/scala/fs2/text.scala

Current `def lines` looks complex.
I've rewritten it to a simpler one, that doesn't break tests.
I haven't touched `def linesFromString`, because I'm not sure if java string.lines can or should be used.
Moreover, I haven't tried stringBuilder for the same concerns.

simplify def lines

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/Logger.scala

We don't need `MonadCancelThrow` - we only make use of `uncancelable` and don't actually care about the error type.

Simplify Acquire and weaken MonadCancel constraint

---

site/docs/faq.md

`scalacOptions in Console += "-Ydelambdafy:inline"` fails with 
```
/home/lcampos/Development/experiment-with-stuff-scala/build.sbt:90: error: overloaded method value in with alternatives:
(scope: sbt.Scope)sbt.TaskKey[Seq[String]] <and>
(c: sbt.ConfigKey)sbt.TaskKey[Seq[String]] <and>
(t: sbt.Scoped)sbt.TaskKey[Seq[String]] <and>
(p: sbt.Reference)sbt.TaskKey[Seq[String]]
cannot be applied to (sbt.Console.type)
scalacOptions in Console += "-Ydelambdafy:inline"
^
[error] Type error in expression
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

FAQ - Fix line to add to build.sbt

---

core/shared/src/main/scala/fs2/Stream.scala

I figured these were worth adding, since it's by and far better than blindly running `Stream.repeatEval(queue.take)`. The covariant supertype of `Queue` presents an alternative implementation, but we don't have that for now (https://github.com/typelevel/cats-effect/pull/1553).

Add Stream.fromQueue and Stream.fromQueueChunked

---

site/docs/faq.md

See discussion from gitter: https://gitter.im/functional-streams-for-scala/fs2?at=5ff576eb4498e01bbf8df9e9

Update FAQ with information about REPL hangs in Scala versions 2.12.0-2.13.1

---

io/src/main/scala/fs2/io/net/Socket.scala
io/src/main/scala/fs2/io/net/SocketGroup.scala
io/src/main/scala/fs2/io/net/tls/TLSSocket.scala
io/src/test/scala/fs2/io/net/tcp/SocketSuite.scala
io/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala

- Initializes the socket read buffer to 8192 bytes instead of 0
- Uses `allocateDirect`
- Stores read buffer in a private var instead of a `Ref`

Improve performance of TCP socket reads

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

The `Pull.loop` had the return type `Pull[F, O, Option[R]]`, which suggests that at the end of loop there would be some r or none. But in truth, the loop ends when there is none, with none. So we can just say that it ends with Unit.
This makes `Pull.loop` more similar to the _unfold_ method for building lists from an `A => Option[B]` method. Here we can even build the Stream from it.
Along the way, we save a few calls to `Pull.void`, which will shave some allocations.

Pull.loop: change stream return type, from Option to Unit.

---

README.md

The current one with index.html results in broken empty page:

Fix broken microsite link

---

io/src/main/scala/fs2/io/io.scala
io/src/test/scala/fs2/io/IoSuite.scala

I noticed that regardless of the `chunkSize` passed into `readOutputStream`, the resulting stream has 1024-byte chunks, due to the default buffer size in `PipedInputStream`. Passing the chunk size into the `PipedInputStream` constructor syncs the two up.

make readOutputStream use chunkSize consistently

---

site/guide.md

Solves https://github.com/typelevel/fs2/issues/1561.

Don't mention a non-existent function (interrupt) in the docs (fix #1561)

---

core/jvm/src/main/scala/fs2/compression.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

Currently, the constructors of a Stream (or Pull) ensure that every Chunk in a Stream, that is every `Output` node in a pull, must have a non-empty Chunk. Therefore, where we uncons we always stop at a non-empty chunk-stream, so we can omit the "nonEmpty" methods..

Change: all Output operators are non-empty.

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

- Pull.setepLeg: no need for `asInstanceOf`.
- Stream zipping method: replace unused `Option[INothing]` by unit, which allows us to remove .void calls.
- Stream.zipWith_ method: the parameter `k1` is only ever applied to  a `Left`, so we can reduce it to the left type. Similarly, the parameter `k2` is applied to either a `Right` or a `Left`, so we can split it in two parameters.

Some code cleanups.

---

site/guide.md

Links in navigation and table of contents to the appendix section now works correctly.

Fix appendix navigation (fixes #2235)

---

core/shared/src/main/scala/fs2/Stream.scala

Noticed the documentation had 'we can' in a place that didn't fully connect to the other part of the sentence.

Small Stream.scala documentation wording change

---

site/concurrency-primitives.md

~~Didn't add an example for Queue because [it is being moved to cats-effect](https://github.com/typelevel/fs2/issues/2213). :)~~

Simpler examples of concurrency primitives

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

The `Step` Pull constructor is used to turn a closed pull (a Stream) into a pull that stops at the first `Output` node. It had an optional scopeId parameter, to indicate if we shift to a scope or not.
- The `None` case is used for the `uncons` operation, which maps the return triplet to the tuple and ignores the second element. 
- The `Some` case is used for the `stepLeg`, which maps the triplet to a `StepLeg`.
Since these are different usages with different data and different end return type, it may be better to split the `Step` into two cases `StepCons` and `StepLeg`.
- StepCons is a step without shifting scopes, and it returns just the (option of) tuple of Chunk and tail pull.
- StepLeg is a step that is run in a separate scope, shifting there and back again. Upon reaching an `Output`, …

Pull: split Step operation in two constructors.

---

site/ecosystem.md

Adds two libraries to the ecosystem docs:
* FS2-ES, my custom event-sourcing and event-driven state library using FS2.
* Pure AWS, a newer collection of AWS clients that of course involves FS2 streaming.

Add FS2-ES and Pure AWS to ecosystem.md

---

core/shared/src/main/scala/fs2/Stream.scala

Use the `repeatPull` directly, unfolding the call to `mapChunks`.

Stream: small `drain` tweak

---

core/shared/src/main/scala/fs2/concurrent/Signal.scala

First of a bunch of concurrency PR over the coming days: Signal no longer uses Unique, which we've seen be very beneficial for Deferred

Remove Unique from Signal

---

io/src/main/scala/fs2/io/tls/TLSEngine.scala
io/src/main/scala/fs2/io/tls/TLSSocket.scala
io/src/test/scala/fs2/io/tls/TLSSocketSuite.scala

Fixes the issue seen here: https://github.com/http4s/http4s/issues/4458
The issue was caused by a client that closes the socket for writing while still reading.

Fixes a stall in TLSSocket encountered in ember-server

---

core/shared/src/main/scala/fs2/Stream.scala

Since this stream is drained, we can release them a bit earlier

Stream - replace takeWhile with exists

---

core/shared/src/main/scala/fs2/Compiler.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/internal/Scope.scala
core/shared/src/test/scala/fs2/BracketSuite.scala

See here for a (long) conversation:
https://gitter.im/functional-streams-for-scala/fs2-dev?at=60392cf8d74bbe49e0bdfa49

Fix resource leak with bracketFull, interruption, and no polling

---

core/shared/src/main/scala/fs2/Stream.scala

List of several changes to improve code readability.
- Concurrently: extract inner `watch` method, and rename some vairables.
- Format some scaladocs, to keep on the 80 flexible line.
- InterruptWhen: use a `Stream.force` form, without the  `Stream.eval` operations. Use some variables.
- observeAsync: use the `Stream.force` form, and make some use of recursive pull functions for the sinkers.

Stream - Rewrite some concurrent methods.

---

core/shared/src/main/scala/fs2/Stream.scala

extensions are placed in companion object, thus no imports should be required

Stream replace evidence & asInstanceOf to implicit class

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/test/scala/fs2/StreamConcurrentlySuite.scala

Fixes #2197
Based on the analysis from @RaasAhsan. All tests pass with this change and while it feels pretty adhoc, I think we should fix this in the simplest way possible and then look at revamping stream interruption in general later.

Fix for interruption skipping error handlers in certain cases

---

CONTRIBUTING.md
build-site.md
site/concurrency-primitives.md
site/guide.md

Hello, while browsing docs I noticed two links which currently shows `404 - Not found`.
- In 'Guide' page 'Concurrency' section link leading to 'Concurrency Primitives'
- In 'Concurrency Primitives' page FIFO example linke leading to 'Guide' page 'Talking to the external world' section
Additionally two changes I made while following docs for building site.
- Link to build-site.md now links to main repo instead of fork
- Changed docsify command to not include `fs2/` (when I followed commands I expected that they are executed from root of directory unless specified otherwise and got confused a bit when it didn't work)

Fix two links in site and update site building instructions

---

core/jvm/src/it/scala/fs2/MemoryLeakSpec.scala
core/shared/src/main/scala/fs2/Pull.scala

Recently, Dmitry Golubets submitted a benchmark for the `groupWithin` stream operation, in #2328. That benchmark tapped into a memory leak that was introduced when the `CallRun` middle step was modified.
Reintroducing it in this PR seems to solve the leak.

Fix Memory Leak detected on GroupWithin Benchmark.

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala

This PR removes `lines`, `showLines`, and `showLinesStdOut` and replaces them with `printlns`.
`Stream.random` was also updated to use `cats.effect.std.Random`.
The only uses of `Sync` constraints left are:
1) Creating a stream from an interator
2) Compression package
Thoughts on updating compression package to use a capability trait?

Remove some uses of Sync constraint, fixes #2338

---

io/src/main/scala/fs2/io/net/SocketGroup.scala
site/io.md

My TLS server died because somebody connected to it via plaintext; this was because of no error handling at the client socket level, and @mpilquist suggested I make a PR to warn users of this.
Also I also [wrote up a short retro](https://www.scalawilliam.com/letsencrypt-fs2/) about my experience 😀

Add a note to handle client socket stream errors.

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/concurrent/BroadcastSuite.scala

As discussed on Gitter. I'm still not sure if an error is better than `.drain`, but at least this way the behaviour is explicit and gives a clearer error.

Improve empty broadcastThrough error message

---

core/jvm/src/it/scala/fs2/MemoryLeakSpec.scala
core/jvm/src/main/scala/fs2/compression/Compression.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala-2.12/fs2/ChunkGeneratorsCompat.scala
core/shared/src/test/scala-2.13/fs2/ChunkGeneratorsCompat.scala
core/shared/src/test/scala-2.13/fs2/ChunkPlatformSuite.scala
core/shared/src/test/scala-3/fs2/ChunkGeneratorsCompat.scala
core/shared/src/test/scala/fs2/ChunkGenerators.scala
core/shared/src/test/scala/fs2/StreamObserveSuite.scala
core/shared/src/test/scala/fs2/StreamSuite.scala
core/shared/src/test/scala/fs2/StreamZipSuite.scala
io/src/test/scala/fs2/io/IoSuite.scala

Resolves #1887. And then some.
I'm hoping none of these changes are controversial. It's just some code reordering to help the Scala 2.13 pattern matcher in `Pull.scala` and using `scala.annotation.nowarn` to get rid of the `dead code` warnings around the `INothing` type in tests, as well as silencing of `unused implicit parameters` warnings.
I also trusted the Scala 3 compiler to figure out whether some type tests cannot be checked at runtime (although this is consistent across Scala 2.13 and 3).
Blocked on #2373.

Compile fs2 on all supported Scala versions without warnings

---

reactive-streams/src/test/scala/fs2/interop/reactivestreams/SubscriberStabilitySpec.scala

Resolves #2084.
Since `Dispatcher` is not mockable, is this a suitable reimplementation of this test? Thanks.
Blocked on #2373.

Resurrect SubscriberStabilitySpec

---

README.md

Making the Discord support channel more visible by adding a badge to #fs2 that never expires :)  
This is how it looks like:

Adds Discord badge

---

core/shared/src/main/scala/fs2/concurrent/Channel.scala

Fixes both "hung merge" and "broadcastThrough identity". The `unlessA` breaks monadic tail recursion.
For posterity, here's how I found this one:
- bisect pointed to ef57231 as the first commit for which "hung merge" test failed
- that commit changed `Stream.merge` but none of the changes there changed the "shape" of streams besides swapping in `Channel` for `Queue`
- by poking around in the .hprof written out by `MemoryLeakSpec`, I noticed the `BindBind` chains contained lots of references to `Pull.eval(...).flatMap`, so I searched `Channel.scala` for `Pull.eval` -- there were only 2 matches, one of which had the `unlessA`

Fix memory leak in Channel

---

core/shared/src/main/scala/fs2/concurrent/Signal.scala

Closes #2396.
The primary intention of this PR is to add partial apply factory for SignallingRef.

Add partial apply factory for SignallingRef

---

core/shared/src/main/scala/fs2/Pull.scala

Currently, stream compilation would create one new instance of an `OuterRun` for each `Chunk` that is emitted up to the top level, even if we are just folding them or merely ignoring them (draning them). Perhaps a little bit of mutability would help.
Not sure if this mutable variable would add much risk, since compilation proceeds in sequence, and separate compilations of a same source string would still use separate `OuterRun` instances.

Make the OuterRun class mutable

---

core/shared/src/main/scala/fs2/Pull.scala

With the latest versions of Scala 2.12 and 2.13, some type casts (use of asInstanceOf) are not needed.

Remove some unneeded typecasts.

---

build.sbt
core/shared/src/main/scala/fs2/Pull.scala

- Extract the "Bind" built inside the continuation of `BindBind`
as a separate `DelegateBind` class with clear fields (make links clearer),
- Split `CloseScope` into three classes to narrow combinations.

Pull - Small changes to the Pull GADT

---

io/src/main/scala/fs2/io/net/tls/TLSContext.scala
io/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala

Adds a failing test with fix.
https://bugs.openjdk.java.net/browse/JDK-8242183

Expose Exception caused by not using X509ExtendedTrustManager

---

io/src/main/scala/fs2/io/internal/PipedStreamBuffer.scala
io/src/main/scala/fs2/io/internal/Synchronizer.scala
io/src/main/scala/fs2/io/io.scala
io/src/main/scala/fs2/io/udp/AsynchronousSocketGroup.scala
io/src/test/scala/fs2/io/IoSuite.scala

This backports #2383 to 2.5.x, to address #2037 for those who can't upgrade to 3.x yet.

backport PipedStreamBuffer to 2.5.x

---

io/src/main/scala/fs2/io/internal/PipedStreamBuffer.scala

See #2450. Fixes issues encountered after #2446 on series/2.5.x.

Mask interruption as IOException

---

core/shared/src/main/scala/fs2/Pull.scala

Retries the change in #2196 , which were reverted in #2394.
This "simplification", was tried before and rolled back because  it caused some Memory Leaks. Inspecting a heapdump, we saw that the leaks were caused by the compilation creating many objects of type `Bind`, `BindBind`, or `DelegateBind`, in which the  `step` (the pull on the left of >>=) was just a terminal.  To avoid this problem, we add a "smart constructor" method `bindView`, used when creating a Pull by binding a Pull with a View. This constructor, instead of always creating a new object, applies the "continuation" function directly. This is admisible during compilation.
_Edit:_ one consequence of directly calling the `cont` method, to avoid accumulating the `DelegateBind` objects, is that the `tailrecM` method of the Monad …

Remove use of BuildR

---

core/shared/src/main/scala/fs2/Stream.scala

Fixes a small typo, but more importantly, merging this will get me white-listed for CI in #2453. Thanks in advance!

Fix typo in Stream scaladoc

---

io/src/main/scala/fs2/io/internal/PipedStreamBuffer.scala
io/src/test/scala/fs2/io/IoSuite.scala

Resolves #2457.
I honestly don't know how I ever expected this to work. I must have wanted to iterate on the initial code but obviously forgot to do it. I apologize for the mistake.

PipedStreamBuffer circular copying fix

---

core/shared/src/main/scala/fs2/Pull.scala

Added `Pull.sleep`, analogously to `Stream.sleep`. 
```
import cats.effect.IOApp
import cats.effect.{ExitCode, IO}
import scala.concurrent.duration._
import cats.syntax.all._
object PullSleepApp extends IOApp {
def run(args: List[String]): IO[ExitCode] =
printTime
.productR(Pull.sleep[IO](1.second))
.productR(printTime)
.stream
.compile
.drain
.as(ExitCode.Success)
private def printTime = Pull.eval(IO.delay(println(System.currentTimeMillis())))
}
```
```
[info] running fs2.PullSleepApp 
1625160228568
1625160229692
```

Add sleep to Pull

---

io/src/main/scala/fs2/io/net/tls/TLSEngine.scala

I ran in to an issue with http4s ember servers where JRE HttpsURLConnection clients would stall occasionally. The TLS handshake would complete but ember server would timeout while reading the request body, eventually resulting in a 500 response indicating a request timeout.
The issue was caused by unwrapped data remaining in the `unwrapBuffer` after the handshake completed. As a result, the request to read from the TLS socket would result in an underlying read on the raw socket, but there's no further data available, and hence the read would timeout.
I tried reproducing in a test in fs2-io but due to various timing and buffer sizing sensitivities, I was unsuccessful. I have confirmed a fix using this http4s test though: https://gist.github.com/mpilquist/82726e0f8ff740defca6a235bf3efd41

Fix TLS socket read stall immediately after handshake

---

build.sbt
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala
io/src/main/scala/fs2/io/net/tls/TLSContext.scala
io/src/main/scala/fs2/io/net/tls/TLSEngine.scala
io/src/main/scala/fs2/io/net/tls/TLSLogger.scala
io/src/test/scala/fs2/io/net/tls/DTLSSocketSuite.scala
io/src/test/scala/fs2/io/net/tls/TLSDebugExample.scala
io/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala

This gives us syntax like:
```scala
tlsContext.client(socket).use(...)
tlsContext.clientBuilder(socket).withLogging(...).build.use(...)
```

Avoid allocations in TLSEngine when logging is disabled

---

io/src/main/scala/fs2/io/internal/PipedStreamBuffer.scala
io/src/test/scala/fs2/io/IoSuite.scala

Resolves #2457 for fs2 3.0.
Again, sorry for this whole mess.

PipedStreamBuffer bug fix port

---

core/shared/src/main/scala/fs2/Stream.scala

Supersedes https://github.com/typelevel/fs2/pull/2465
(GH wouldn't let me re-open the old PR)

Relax queue-related signatures to use `QueueSink` / `QueueSource`

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Pull.scala

```scala
import cats.effect.IOApp
import cats.effect.{ExitCode, IO}
import scala.concurrent.duration._
import cats.syntax.all._
object PullOptionApp extends IOApp {
def run(args: List[String]): IO[ExitCode] = {
val single = Pull.outputOption(Some(1))
val empty = Pull.outputOption(None)
val msg = s"single: ${single.stream.compile.toList}\nempty: ${empty.stream.compile.toList}"
IO(println(msg)).as(ExitCode.Success)
}
}
```
```
[info] running fs2.PullOptionApp 
single: List(1)
empty: List()
```

Pull.outputOption

---

.github/workflows/ci.yml
build.sbt
node/yarn.lock

Supersedes #2482 and #2483. Hopefully fixes #2479.
Creates a separate module with the generated Scalably Typed Node.js facade. Quiets nearly all related output (maybe now 10-20 lines of `npm` stuff). Also disables Scaladoc generation per the [recommended settings](https://scalablytyped.org/docs/library-developer#recommended-settings).

Create separate module for Node facade

---

io/js/src/main/scala/fs2/io/net/SocketGroupPlatform.scala
io/shared/src/test/scala/fs2/io/net/tcp/SocketSuite.scala

Adds a listener for errors thrown during client socket connection and server binding. Also adds test coverage.

Catch errors during Node.js socket initialization

---

core/shared/src/main/scala/fs2/Pull.scala

This PR fixes a handful of things in the `Pull` docs.
In this I noticed that only `as` has the `@tparam` and `@param` annotations, I could add these to the other methods like `map` and `flatMap` if that's desired. I'm not sure what the best practice is here.
The docs for fs2 are really great and helpful, thank you so much!

Minor fixes in Pull docs

---

core/shared/src/main/scala/fs2/Pull.scala

We modify transformWith, so that if the left-hand-side pull is a terminal, we directly apply the function. `transformWith` is used in stream flatMap.

Pull - Shortcut in transformWith

---

core/jvm/src/test/scala/fs2/CompressionSuite.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/Generators.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala
core/shared/src/test/scala/fs2/StreamInterruptSuite.scala
core/shared/src/test/scala/fs2/StreamSuite.scala
core/shared/src/test/scala/fs2/StreamZipSuite.scala
core/shared/src/test/scala/fs2/TextSuite.scala

This seemed a strange omission to me, but maybe there's a good reason for it?

Implement `unchunks` (inverse of `chunks`)

---

io/js/src/main/scala/fs2/io/NodeStream.scala

I realized that downstreams can extend these in their own facades and get out-of-the-box interop with fs2.io which is cool :)

Unseal Node.js Stream facades

---

benchmark/src/main/scala/fs2/benchmark/StreamBenchmark.scala
core/shared/src/main/scala/fs2/Stream.scala

I was interfacing with some external methods following the documentation example using cats.effect.std.Queue and was surprised at the extreme slowness of the code. It seems I accidentally came across a bottleneck in the current algorithm that makes it accidentally quadratic whenever the producer submits elements very fast.
In particular, the current code performs a Chunk concatenation via `++` in order to build a chunk as large as possible with the elements available in the queue. This seems to be a massive slowdown in case the chunk gets concatenated a large amount of times (as low as n >= 10). Mainly because all the Chunk methods are using the `apply(Int)` method to access the elements, which has complexity O(n) (n being the index) in the case of a queue due to its List-like structure …

Improve Stream from Cats Effect Queue performance

---

core/shared/src/main/scala/fs2/Stream.scala

Most of this is an indentation change. White space should show that this is just 
```
if (maxOpen === 1) outer.flatten
else ...
```
Basically meaning that when people select this, if the option selected is 1, then they don't pay any penalty for using this combinator.

Special Case parJoin 1

---

io/js/src/main/scala/fs2/io/net/tls/TLSParameters.scala

This one slipped through the cracks, hope it's okay to make this change.

Make internal method `private[TLSParameters]`

---

core/jvm/src/it/scala/fs2/MemoryLeakSpec.scala
core/shared/src/main/scala/fs2/Pull.scala

The compilation of `MapOutput` is the only remaining `Pull` subclass that is compiled by "rewriting" the `MapOutput`, which is to say by reducing the `Pull` object to another `Pull` object, in the `innerMapOutput` auxiliary method.
To remove this last "rewrite" logic, we introduce a new `MapOutR`, a subclass of Runner for the MapOutput object. We remove the innterMapOutout rewrite method.
Add leak test for bug in typelevel#2569

Pull: compile MapOutput with a runner.

---

site/guide.md

Some of the snippets are missing the syntax highlighting. This should
fix it.

Fix syntax highlighting in getting started guide

---

build.sbt
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

Remove optimized Stream.map due to leaky implementation

---

core/shared/src/main/scala/fs2/Stream.scala

This avoids the penalty of using the combinator if there is no
concurrency. Analogous to #2557 which did the same for `parJoin`.

Special case for `parEvalMap` with max concurrency of 1

---

site/api-reference.md
site/getstarted/install.md

This patch improves the formatting on the API reference page and updates links and references for FS2 3.1.1.
| Current | Proposed |
| - | - |
| <img width="385" alt="image" src="https://user-images.githubusercontent.com/4206232/131611572-caaf4414-dc14-4b80-bb12-a3b52f573c7e.png"> | <img width="385" alt="image" src="https://user-images.githubusercontent.com/4206232/131611511-1fb82251-f1b0-45c2-8268-5e5c12d686c7.png">

Update docs for 3.1.1 + improve formatting on API reference page

---

core/jvm/src/it/scala/fs2/MemoryLeakSpec.scala
core/shared/src/main/scala/fs2/Pull.scala

From https://github.com/typelevel/fs2/issues/2598, we add a leak test for pure streams, one with flatMap and uncons, which does not involve parallelism.
We then make the changes in `pull` interpreter that would fix that specific leak test case.

Issue-2598: Fix memory leaks and minimisations.

---

io/js/src/main/scala/fs2/io/IOException.scala
io/jvm/src/main/scala/fs2/io/ioplatform.scala
io/jvm/src/main/scala/fs2/io/net/AsynchronousDatagramSocketGroup.scala
io/jvm/src/main/scala/fs2/io/net/DatagramSocketGroupPlatform.scala

This came up in https://github.com/http4s/http4s/pull/5065#issuecomment-908288405. cc @rossabaker 
Note that I have no idea what the equivalent error type is on Node.js, so this will never be thrown "natively" on JS. But, it is useful for throwing manually as is the case in http4s.

Introduce `fs2.io.ClosedChannelException`

---

core/shared/src/main/scala/fs2/concurrent/Signal.scala

Purely for convenience, this allows for writing
`signal.predicate(f)`
instead of
`signal.get.flatMap(f.whenA)`

Add a convenient shorthand for predicating effects on a boolean signal.

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamParJoinSuite.scala

Rework `parJoin` to work with transformers

---

core/jvm/src/it/scala/fs2/MemoryLeakSpec.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/test/scala/fs2/StreamTranslateSuite.scala

Looking at the translate method, I noticed that, strangely enough,  it was not using the `view` or continuation. This means that any stream after a Translate would be dropped. This was not detected because, in the `StreamTranslateSuite`, none of the unit/property tests was appending something after the translation. Along the way, we also add a leak test that uses translate, to cover that a little bit.

Pull - fix Translate bug.

---

io/jvm/src/main/scala/fs2/io/net/unixsocket/JdkUnixSockets.scala
io/jvm/src/main/scala/fs2/io/net/unixsocket/JnrUnixSockets.scala

Fix UnixSockets classpath detection logic

---

core/shared/src/main/scala/fs2/Stream.scala

- Rename the `n` parameter as `outputSize`
- For `dequeueN` and other internal functions, no need to pass the `n` parameter since that is just the `outputSize` parameter of main function.
- Extract auxiliary `toEnding` function.
- Documentation: add some inline documentation, and the scaladoc of the method...

Stream - GroupWithin - Some changes.

---

build.sbt
core/shared/src/main/scala-3/fs2/ChunkPlatform.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Stream.scala

Fixes #2603 and #2627. Also addresses the issue described here: https://github.com/circe/circe-fs2/issues/273 (cc @samspills)
The `Chunk.Queue` type provides the ability to efficiently create a single chunk out of any number of individual chunks. In 2.x, `Chunk.Queue` was not itself a subtype of `Chunk`. After various individual chunks had been accumulated in to a `Chunk.Queue`, the queue had to be converted to a single chunk via `toChunk`. This operation returned a single array backed chunk. Unfortunately, this relied on reflection and various tricks to build the array backed chunk without access to a `ClassTag` at the call site and ultimately was unsound. We fixed this in https://github.com/typelevel/fs2/pull/2181.
One of the main changes in #2181 was making `Chunk.Queue` a subtype of …

Remove unnecessary indexing in Chunk combinators

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/test/scala/fs2/ChunkQueueSuite.scala
core/shared/src/test/scala/fs2/TextSuite.scala

Per suggestion from @diesalbla

Make indexed traversal of `Chunk.Queue` amortized logarithmic time

---

benchmark/src/main/scala/fs2/benchmark/ParEvalMapBenchmark.scala
core/shared/src/main/scala/fs2/CompositeFailure.scala
core/shared/src/main/scala/fs2/Stream.scala

issue: https://github.com/typelevel/fs2/issues/2297
MR has three commits, the first one contains the implementation of parEvalMapUnordered
using queue. In the second one channel is used instead. Both show 4x performance boost in the benchmark.
Queue version can be backported to 2.x
<pre>
original
[info] Benchmark                                  (chunkSize)  (size)   Mode  Cnt      Score     Error  Units
[info] ParEvalMapBenchmark.evalMap                         10     100  thrpt    5  18371,696 ± 691,166  ops/s
[info] ParEvalMapBenchmark.evalMap                         10   10000  thrpt    5    268,572 ±  50,354  ops/s
[info] ParEvalMapBenchmark.evalMap                        100     100  thrpt    5  20519,182 ± 700,520  ops/s
[info] ParEvalMapBenchmark.evalMap                        100 …

parEvalMapUnordered performance

---

core/shared/src/main/scala/fs2/Pull.scala

Since Actions are pulls, and since we are using the variable for storing the next continuation, we can match with a single
level. This saves the need for extra type variables and some casting.

Pull - Remove nested matches.

---

build.sbt
core/shared/src/main/scala/fs2/Compiler.scala

This is intended to facilitate using `Target` as a context bound when you need `MonadCancelThrow` but don't specifically need either `Sync` or `Concurrent`.

Make Compiler.Target extend MonadCancelThrow

---

io/jvm/src/main/scala/fs2/io/internal/PipedStreamBuffer.scala
io/jvm/src/test/scala/fs2/io/IoPlatformSuite.scala

Resolves #2637.
The built in `%` remainder operator can return a negative result. We're actually interested in the modulus operation which returns a non-negative result.

`PipedStreamBuffer` circular copying overflow fix

---

io/src/main/scala/fs2/io/internal/PipedStreamBuffer.scala
io/src/test/scala/fs2/io/IoSuite.scala

Resolves #2637 for `series/2.5.x`.

`PipedStreamBuffer` circular copying overflow fix backport

---

io/jvm/src/main/scala/fs2/io/net/SocketGroupPlatform.scala
io/jvm/src/main/scala/fs2/io/net/SocketPlatform.scala

This PR fixes a socket / file descriptor leak when opening sockets to domains that dont resolve. eg Network[IO].client(SocketAddress(Host.fromString("nodomain.fs2.io").get, port"80"))
Fix for https://github.com/typelevel/fs2/issues/2643
Please review. The main change is just to `close` with `Resource.make` in `def client(..` rather than later in `Socket.forAsync`. Im not sure why it was in `Socket.forAsync`, the other usages I found in `fs2.io.net` seemed to be already closing. Im not sure if that instance could have been used elsewhere, it shouldnt because its private.
PS. Thanks for the excellent library 😊

fix socket leak for unresolvable domains

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamConcurrentlySuite.scala
io/src/test/scala/fs2/io/IoSuite.scala

Fixes #2647 for `series/2.5.x`.

Fix `Stream#concurrently` for short-circuiting monad transformers - `2.5.x`

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamConcurrentlySuite.scala
io/jvm/src/test/scala/fs2/io/IoPlatformSuite.scala

Fix `Stream#concurrently` for short-circuiting monad transformers

---

io/jvm/src/main/scala/fs2/io/compressionplatform.scala

It turns out this was a good idea. The problem is that when this is empty for JVM, it becomes an unused import which is problematic with fatal warnings enabled.

Revert "Remove unnecessary delegate" for `fs2.io.compression`

---

core/shared/src/main/scala/fs2/internal/Scope.scala
core/shared/src/test/scala/fs2/StreamInterruptSuite.scala

Addresses #2371.  Solution first discussed in #2650.
Before, compiling a concurrent stream with the Sync compiler would fail quickly and pessimistically.  Now we proceed with no-op interruption.  We can now successfully process more streams with this compiler at the expense of non-termination of some.
This is helpful when constraining to `Sync` when `Async` would have brought a more powerful compiler, or translating a Concurrent stream to a Synchronous effect like Doobie's `ConnectionIO`.

Make interruptWhen a no-op with the Sync compiler

---

io/js/src/main/scala/fs2/io/IOException.scala
io/js/src/main/scala/fs2/io/file/FileSystemException.scala
io/js/src/main/scala/fs2/io/net/NetException.scala
io/jvm/src/main/scala/fs2/io/ioplatform.scala
io/jvm/src/main/scala/fs2/io/net/net.scala
io/shared/src/test/scala/fs2/io/file/FilesSuite.scala
io/shared/src/test/scala/fs2/io/net/tcp/SocketSuite.scala

This improves the consistency of IO exceptions on Node.js with their JVM counterparts by providing identical messages. This came up in https://github.com/http4s/http4s/pull/5290.

Improve IO exceptions on Node.js

---

core/shared/src/main/scala/fs2/text.scala
core/shared/src/test/scala/fs2/TextSuite.scala

Only necessary in a handful of non-UTF-8 charsets.  Setting the last input flag on the final `decode` isn't sufficient: the decoder state must be flushed in a separate call.
Fixes #2664.

Flush CharsetDecoder to produce final chunk

---

io/jvm/src/main/scala/fs2/io/net/SocketPlatform.scala

This partially reverts #2644 to fix the socket close bug that came up in https://github.com/http4s/http4s/pull/5316#issuecomment-933920782 while preserving the fix for #2643. Not sure what caused the regression, or why this fixes it.

Fix socket close regression

---

build.sbt
core/jvm/src/main/scala/fs2/compression/CompressionPlatform.scala
core/jvm/src/test/scala/fs2/JvmCompressionSuite.scala
core/shared/src/main/scala/fs2/compression/DeflateParams.scala

Context here: https://github.com/http4s/http4s/issues/5417
This FHCRC flag is an optional feature that fs2 is opting-in to (with an implementation that looks good BTW), but unfortunately, many clients have/had a bugged implementation (e.g. https://github.com/netty/netty/pull/11805) of it or perhaps don't even support it at all (and that's fine, as soon as they don't break 😄 ).
This PR is making it configurable, restoring a default of `0` (no FHCRC). 
The client can choose to opt-in by specifying the `fhCrcEnabled` property in `DeflateParams`.
Ideally, we should backport this to 2.x (for supporting http4s 0.22 as well).
Hopefully, I preserved the binary compatibility.

Opt-in for FHCRC in gzip compression

---

build.sbt

Turns out it interacts very badly with the ScalaJSBundlerPlugin.

Make fs2-io osgi jvm-only

---

CONTRIBUTING.md
build-site.md
shell.nix
site/documentation.md
site/guide.md

This PR improves the section of the guide on `fs2.Pull`. Feedback is of course very welcome!
I've also upgraded the JDK version in the nix shell to 16. This is necessary for compiling the `java.net.UnixDomainSocketAddress` ([JEP 380](https://openjdk.java.net/jeps/380)).

Improve the guide on Pull

---

benchmark/src/main/scala/fs2/benchmark/ChunkBenchmark.scala
benchmark/src/main/scala/fs2/benchmark/ChunksBenchmark.scala
core/shared/src/main/scala-2.12/fs2/ChunkPlatform.scala
core/shared/src/main/scala-2.13/fs2/ChunkPlatform.scala
core/shared/src/main/scala-3/fs2/ChunkPlatform.scala
core/shared/src/main/scala/fs2/Chunk.scala

This PR:
- replaces uses of mutable.Buffer with mutable.ArrayBuilder
- allocates primitive arrays when possible (e.g. filter)
```
[info] ChunkBenchmark.map           16  thrpt    5  20039615.265 ± 492279.237  ops/s
[info] ChunkBenchmark.map          256  thrpt    5   1278011.968 ±  42407.622  ops/s
[info] ChunkBenchmark.map         4096  thrpt    5     46243.164 ±    295.401  ops/s
[info] ChunkBenchmark.map           16  thrpt    5  43344785.011 ± 665760.099  ops/s
[info] ChunkBenchmark.map          256  thrpt    5   3551895.914 ±  12759.777  ops/s
[info] ChunkBenchmark.map         4096  thrpt    5     69298.960 ±   4435.243  ops/s
[info] ChunkBenchmark.filter           16  thrpt    5  30132296.897 ± 378366.725  ops/s
[info] ChunkBenchmark.filter          256  thrpt    5   2326540.853 ± …
```

Improve memory efficiency of Chunk.filter and replace internal use of mutable.Buffer with mutable.ArrayBuilder

---

io/js/src/main/scala/fs2/io/ioplatform.scala
io/jvm/src/main/scala/fs2/io/ioplatform.scala
io/shared/src/main/scala/fs2/io/io.scala

This reworks the stdin/stdout wrappers in fs2.io to use `process.stdout` etc. in Node.js. Part of my plan to fix https://github.com/typelevel/cats-effect/issues/2588; more details there.
I regret not doing this before: it required upgrading the constraint to `Async` so is source-breaking and jumps through bincompat hoops.
As a bonus, I snuck in a new API wrapping `stderr` :)

Use Node.js API for stdout/stdin

---

io/js/src/main/scala/fs2/io/file/FilesPlatform.scala
io/shared/src/test/scala/fs2/io/file/FilesSuite.scala

In nodejs, calling `stat` throws an exception if the path does not exist, thus making `isDirectory`, `isFile` and `isSymbolicLink` fail as well. In jvm, on the other hand, the underlying calls do not throw and return `false` when the path does not exist.
This is an attempt to make the behaviour of these functions more aligned across platforms.
---
~There's a couple of TODOs in the tests, not sure how important these are:~
* ~not sure how to easily create a symlink for tests~
* ~not sure how to create a "hidden" file for tests~

ioJS: handle NoSuchFileException in isDirectory, isFile and isSymbolicLink

---

core/shared/src/main/scala/fs2/Stream.scala

Opened to address some of the inaccuracies discussed in #2600 
- Formulate the coordination condition as: "no pipe can pull and start processing any source chunk until after all pipes have pulled and started processing the previous chunk", which is a bit more accurate than "are done"

Extend `broadcastThrough` documentation

---

core/shared/src/main/scala/fs2/Stream.scala

This PR tweaks the documentation example for `filterWithPrevious` to hopefully better highlight that the `previous` value is the last *emitted* value.
The prior example would have returned a similar answer even if the behaviour was to compare one element with its previous element in the original input Stream.
Co-authored-by: @samspills

Change filterWithPrevious example list in Scaladoc

---

build.sbt
io/jvm/src/main/scala/fs2/io/net/SocketPlatform.scala
io/jvm/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala
io/shared/src/test/scala/fs2/io/net/tcp/SocketSuite.scala
project/plugins.sbt

Fixes https://github.com/typelevel/fs2/issues/2709
We explored four solutions here:
1) Making reads uncancellable
2) Allow read to be canceled and then any subsequent reads hang
3) Improving the error message when reading from a socket that's had a canceled read
4) Making reads after a canceled read behave like a closed socket
The JVM's async channel read does not support cancelation. Hence, the simplest approach is wrapping the channel read with an `F.uncancellable`. We modified `readChunk` and wrapped the `F.async_` call with `F.uncancellable(_ => F.async_(...))`. Unfortunately, this resulted in stream hangs any time a read was pending at the time of shutdown. For example:
```scala
val server = Network[IO].server(...)
doStuff.concurrently(server)
```
When `doStuff` completes, the …

Change Socket#read to disallow a read after a timeout

---

build.sbt
core/shared/src/main/scala/fs2/Chunk.scala

This PR replaces all remaining internal uses of `collection.mutable.Buffer` with `Array` - not sure how I missed these all the first time around. :)
It also adds the `Chunk.to` method, allowing usage like `Chunk.to(Set)`.

Deprecate Chunk.buffer, add Chunk.to(Collection)

---

io/jvm/src/test/scala/fs2/io/file/JvmFilesSuite.scala
io/shared/src/main/scala/fs2/io/file/Files.scala
io/shared/src/test/scala/fs2/io/file/FilesSuite.scala

Changes the behaviour of `walk` to emit files in the order it visits them, which in turn enables streaming copy since it lets you create folders before copying the files they contain, which is a prerequisite for `copy`.
The behaviour of `walk` in main is arguably a regression since it behaves differently from `NIO.walk`, which it used to wrap, so I'm targetting `main` with a straight change, rather than a new method or a flag.

Files walk order

---

io/js/src/main/scala/fs2/io/file/FilesPlatform.scala
io/shared/src/test/scala/fs2/io/file/FilesSuite.scala

calls to `realPath` in nodejs throw an `ENOENT` exception if the path doesn't exist. In order to align the behaviour of `realPath` with what we have in JVM, those errors are re-raised as a `NoSuchFileException`.

fsIO - realPath:  re-raise ENOENT javascript exceptions as NoSuchFileException

---

core/shared/src/main/scala/fs2/text.scala
core/shared/src/test/scala/fs2/TextSuite.scala

* add support for input with '\r'-only newlines, like from macos classic. yes, content like this still exists
* add support to throw an error when an accumulated line is over a certain size; good to prevent bad/malicious inputs from causing OOMs

`text.lines` enhancements

---

core/shared/src/main/scala/fs2/internal/Scope.scala
core/shared/src/test/scala/fs2/StreamZipSuite.scala

In the fix for #2717, we discovered that sometimes after zipping, a closed scope is used for evaluation. We fixed #2717 by ensuring that manual interruption checks occur on the nearest open scope in the case the current scope has been closed already. We needed a similar check for effect evaluation, which checks interruption inside `interruptibleEval`.

Fix #2762 - eval after zip may cause interruption

---

core/shared/src/main/scala/fs2/text.scala
core/shared/src/test/scala/fs2/TextSuite.scala

Don't like the additional special cases here but I can't see an obviously better way to do it.

Handle trailing \r in `text.lines` consistently with other delimiters

---

benchmark/src/main/scala/fs2/benchmark/ChannelBenchmark.scala
core/shared/src/main/scala/fs2/concurrent/Channel.scala

`benchmark/ jmh:run -i 10 -wi 6 -f1 -t4 -gc true -jvmArgs "-XX:MaxRecursiveInlineLevel=3 -XX:MaxInlineSize=50 -Dcats.effect.tracing.mode=none" fs2.benchmark.ChannelBenchmark`
`channel-perf`
```
[info] Benchmark                              (size)   Mode  Cnt      Score     Error  Units
[info] ChannelBenchmark.sendPull                  64  thrpt   10  70315,735 ± 990,801  ops/s
[info] ChannelBenchmark.sendPull                1024  thrpt   10   8489,787 ± 220,705  ops/s
[info] ChannelBenchmark.sendPull               16384  thrpt   10    586,689 ±  14,841  ops/s
[info] ChannelBenchmark.sendPullPar8              64  thrpt   10  48603,532 ± 755,156  ops/s
[info] ChannelBenchmark.sendPullPar8            1024  thrpt   10  10497,909 ± 444,052  ops/s
[info] ChannelBenchmark.sendPullPar8 …
```

Channel perf

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamObserveSuite.scala

This is a minimal fix for #2757.
While this works, there are a few things that I'm unsure of.
- I'm not sure why we need both the `sinkChan` and `outChan` channels. A single channel seems to suffice.
- I'm not sure why we're using `++ Stream.exec(outChan.close.void)` to close the channel instead of `onFinalize`. Is this because we only want the channel to close on success?
I've created an alternative implementation in [a separate branch](https://github.com/typelevel/fs2/compare/main...zainab-ali:observe-reworked) that uses a single channel and finalizers, but this is a bit of a rehaul. Let me know if you'd prefer that PRed instead.

Minimal fix of observe termination logic

---

build.sbt

@diesalbla spotted memory leak tests were failing here: https://github.com/typelevel/fs2/pull/2763#issuecomment-1000571690
A bisect showed it was due to the CE3 upgrade. This PR disables tracing which fixes the leak tests.

Disable tracing in memory leak tests

---

core/shared/src/main/scala/fs2/Pull.scala

In the compilation loop, the BuildR simply represents a sort-of callback or continuation, to connect the result of an inner stream. We use them because directly passing the Uncons or the StepLeg runners currently causes memory leaks.
However, since the BuildR object itself has no state, we can just reuse a same object all through the compilation.

Pull Compilation Tweak: reuse BuildR object.

---

io/js/src/main/scala/fs2/io/file/FilesPlatform.scala
io/jvm/src/main/scala/fs2/io/file/FilesPlatform.scala
io/shared/src/main/scala/fs2/io/file/Files.scala

Not entirely sure if `Files` is the best place for these.
Maybe after https://github.com/typelevel/cats-effect/pull/2650 lands we can add a test that compares to env.

Add `userHome`, `currentWorkingDirectory` to `Files` API

---

README.md

Remove reference to scalaz-stream from readme

---

.github/workflows/ci.yml
build.sbt

This restores the microsite.
It vanished because currently the JVM and JS intermediate artifacts have the same name, so there is a race condition which overwrites the other. However, only the JVM artifacts contained the site. See:
- https://github.com/typelevel/sbt-typelevel/issues/74
- https://github.com/typelevel/sbt-typelevel/pull/98
As a temporary fix, now the site is also generated in the JS job, so regardless of which artifact overwrites the other there will always be a copy of the microsite provided to the gh-pages deploy step.

Fix microsite

---

core/shared/src/main/scala/fs2/fs2.scala

`Pure` can be confusing - hopefully this helps a little.

Expand scaladoc for `fs2.Pure`

---

core/shared/src/main/scala/fs2/Stream.scala

pauseWhen should emit elements as soon as it wakes up, instead of checking for the need to pause again.
The difference in behaviour came up when I was implementing this (very complex) combinator for a user, which alternates between two streams upon a timeout.
```scala
def switchRepeat[A](
every: FiniteDuration,
to: Stream[IO, A]
): Pipe[IO, A, A] = { in =>
Stream.eval(SignallingRef.of[IO, Boolean](true)).flatMap { paused =>
val pause = Pull.eval(paused.set(true))
val unpause = Pull.eval(paused.set(false))
def go(p: Pull.Timed[IO, A]): Pull[IO, A, Unit] =
p.timeout(every) >> p.uncons.flatMap {
case Some((Right(elems), next)) =>
pause >> Pull.output(elems) >> go(next)
case Some((Left(_), next)) =>
unpause >> go(next)
case None =>
Pull.done
}
val foreground = in.pull.timed(go).stream
val …
```

Do not withhold emission in `pauseWhen`

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/ParEvalMapSuite.scala

Fixes https://github.com/typelevel/fs2/issues/2825.

Catch thrown errors in `parEvalMap`, `parEvalMapUnordered`

---

.github/workflows/ci.yml
build.sbt
project/plugins.sbt
site/getstarted/install.md

Following up on https://github.com/typelevel/fs2/pull/2818#discussion_r801882521.
Uses a minor bit of hackery to override Laika, but saves a lot of boilerplate and gets you the latest fs2 version injected into the site for free.
A notable difference from the existing setup is that the site is now deployed in parallel to the snapshot publish (rather than afterwards) and thus does not wait for that to succeed.

Use sbt-typelevel-site plugin to build/publish microsite

---

core/shared/src/main/scala-2.13/fs2/CollectorPlatform.scala
core/shared/src/main/scala-3/fs2/CollectorPlatform.scala
core/shared/src/main/scala/fs2/Collector.scala
core/shared/src/test/scala-2.13/fs2/BitSetCollectorSuite.scala

AFAIK this is the best practice and allows types like `BitSet` to be properly used.

Fix Collector.supportsFactory

---

build.sbt
core/shared/src/main/scala/fs2/Pull.scala

- Modify `Bind` class to make the `step` into an abstract method.
- Modify the `BindBind` class to make the references to the middle and end Bind objects mutable. 
- Modify the `bindBindAux` method (that applies the continuation) to cut the ties with the two Bind objects. That is, set both pointers to null. For an intuition as to why this is correct, it helps to think of a `BindBind` as a node in a stack of continuations, applied to the terminal result of a pull. Once a `BindBind` is applied, it should be popped and not used again.
Cutting this ties allows us to remove the use of the `BuildR` intermediate representation, for the `Uncons` and `StepLeg` case interpreters, without this causing the memory leak tests to fail. 
The motivation for these changes are several. On one hand, the …

Pull - Cut ties with BindBind, no need for BuildR

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/test/scala/fs2/StreamTranslateSuite.scala

If there is an error, it should be handled with the continuation of the `Translate` node, like most nodes.

Pull - Translate compilation - Fix error case.

---

core/shared/src/main/scala/fs2/internal/Scope.scala

Modifies `isInterrupted` to join `map` and `flatMap` into single step. Since the `isInterrupted` is called often in the stream processing, one less F action in here may help performance a little bit.

Scope - Small tweak to isInterrupted

---

core/shared/src/main/scala/fs2/timeseries/TimeStamped.scala

See this Scastie, provided on Discord: https://scastie.scala-lang.org/mn98/oNhMT2wZR0O42S6lN0lUMQ/8
https://discord.com/channels/632277896739946517/632310980449402880/950382134110081084
When the tick resolution argument of `throttle` is 100 millis, the output occurs at the correct speed. When the tick resolution is changed to 10 millis, the outputs get progressively slower.

Fix slowdown in throttle due to improper use of stepLeg

---

build.sbt
core/shared/src/main/scala/fs2/text.scala

Although @vasilmkd's release flag idea doesn't work for the io module, there's no reason we shouldn't apply it for all the other modules.

Set `tlJdkRelease := 8` for all modules but `io`

---

core/shared/src/main/scala/fs2/Stream.scala

These seem to only be needed where there's nothing else to help infer a type.

Remove unneeded `F[x] >: Pure[x]` bounds in Stream

---

core/jvm/src/main/scala/fs2/compression/CompressionPlatform.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/concurrent/Topic.scala
core/shared/src/main/scala/fs2/fs2.scala
core/shared/src/test/scala/fs2/CompilationTest.scala
core/shared/src/test/scala/fs2/PullSuite.scala
core/shared/src/test/scala/fs2/StreamInterruptSuite.scala
core/shared/src/test/scala/fs2/StreamObserveSuite.scala
core/shared/src/test/scala/fs2/concurrent/BroadcastSuite.scala
io/js/src/main/scala/fs2/io/file/FilesPlatform.scala
io/js/src/main/scala/fs2/io/ioplatform.scala
io/js/src/main/scala/fs2/io/net/DatagramSocketPlatform.scala
io/js/src/main/scala/fs2/io/net/SocketPlatform.scala
io/js/src/test/scala/fs2/io/file/BaseFileSuite.scala
io/jvm/src/main/scala/fs2/io/file/DeprecatedFilesApi.scala
io/jvm/src/main/scala/fs2/io/file/file.scala
io/jvm/src/main/scala/fs2/io/ioplatform.scala
io/jvm/src/main/scala/fs2/io/net/DatagramSocketGroupPlatform.scala
io/jvm/src/main/scala/fs2/io/net/SocketPlatform.scala
io/jvm/src/main/scala/fs2/io/net/tls/DTLSSocket.scala
io/jvm/src/main/scala/fs2/io/net/tls/TLSSocketPlatform.scala
io/jvm/src/test/scala/fs2/io/file/BaseFileSuite.scala
io/shared/src/main/scala/fs2/io/file/Files.scala
io/shared/src/main/scala/fs2/io/io.scala
io/shared/src/main/scala/fs2/io/net/DatagramSocket.scala
io/shared/src/main/scala/fs2/io/net/Socket.scala

This PR deprecates the `INothing` type alias as it appears to no longer be necessary with modern compilers. Only a single use site is impacted by this deprecation (in CompilationTest.scala).

Deprecate INothing

---

.github/workflows/ci.yml
build.sbt

As previously mentioned, this adds a published unidocs artifact `fs2-docs`, like http4s and other projects are adopting.
https://www.javadoc.io/doc/org.http4s/http4s-docs_2.13/0.23.11/org/http4s/index.html
Still a bit annoying that you have to explicitly list the projects. Haven't figured out how to automate that yet. Feel free to pass if this over-complicates the build and we can consider again when it's easier.
After the undidocs are published in the next release, I'll PR an update to the site with the new API docs URL.

Add unidocs artifact

---

site/guide.md

Removed duplicate 'a single'.
Target the `main` branch if this PR is targeted for the 3.x series and the `series/2.5.x` branch if targeted for the 2.5.x series.

Tiny docs correction in guide.md

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamParJoinSuite.scala

PR fixes hang of the following stream:
```
case object TestException extends Throwable with NoStackTrace
type F[A] = EitherT[IO, Throwable, A]
Stream.range(1, 64).covary[F]
.map(i => Stream.eval[F, Unit](
if (i == 7) EitherT.leftT(TestException)
else EitherT.right(IO.unit)
))
.parJoin(4)
.map(_ => Stream.eval[F, Unit](EitherT.right(IO.unit)))
.parJoin(4)
.compile
.drain
```
**Problem description:**
For the given stream `lease.cancel` raises monad transformer error, so the following `available.release >> decrementRunning` chain is not invoked and therefore output stream is not closed. But this is only a part of the problem, even if we close the stream, it will swallow monad error and return successful result.
**Fix description:**
To fix the first part of the problem, I replaced `>>` monad …

Fix `Stream#parJoin` for short-circuiting monad transformers

---

core/shared/src/main/scala/fs2/Chunk.scala

Override the default implementation of `size` in `UnorderedFoldable` for `Chunk` so that it directly delegates to the `size` method, saving a traversal.

Add override for size in `Chunk` instance

---

site/getstarted/install.md

This is a common stumbling block :)

Show `scalaJSLinkerConfig` setting in fs2-io.js docs

---

core/shared/src/main/scala/fs2/Compiler.scala
core/shared/src/test/scala/fs2/StreamInterruptSuite.scala

This adopts the idea from https://github.com/typelevel/cats-effect/issues/2771, https://github.com/typelevel/cats-effect/issues/2772 to upgrade a sync compiler when at runtime the constraint is determined to be `Async`. Thoughts?

Upgrade sync compiler when runtime constraint is `Async`

---

core/shared/src/main/scala/fs2/concurrent/Channel.scala
core/shared/src/test/scala/fs2/concurrent/ChannelSuite.scala

H/t @davesmith00000 for reporting and @Daenyth for helping to diagnose it.
The issue was first identified in terms of a synchronous channel: while the channel is blocked awaiting a consumer producers are queued, but then dequeued in reverse-order when there is downstream consumption. This causes the elements to become reversed, effectively FILO.

Respect FIFO for bounded Channel

---

io/js/src/main/scala/fs2/io/NodeStream.scala
io/js/src/main/scala/fs2/io/ioplatform.scala
io/js/src/test/scala/fs2/io/IoPlatformSuite.scala

H/t @satabin for reporting in https://github.com/satabin/fs2-data/pull/335#issuecomment-1155058038.
Previously, exceptions encountered in `fs2.Stream` would also be propagated into the Node.js stream it was interopping with. In v3.2.8 this started crashing the Node.js process with:
```
node:events:505
throw er; // Unhandled 'error' event
^
Error: unexpected '1' before object key
at $c_Lfs2_io_internal_ThrowableOps$ThrowableOps.toJSError__sjs_js_Error (/home/runner/work/fs2-data/fs2-data/json/circe/.js/target/scala-2.13/fs2-data-json-circe-test-fastopt/main.js:11048:10)
at /home/runner/work/fs2-data/fs2-data/json/circe/.js/target/scala-2.13/fs2-data-json-circe-test-fastopt/main.js:11134:92
...
```
(Note: the `unexpected '1' before object key` is an expected error raised in the fs2-data …

Don't propagate errors into Node.js

---

io/jvm/src/test/scala/fs2/io/IoPlatformSuite.scala
io/shared/src/main/scala/fs2/io/io.scala

Fixes https://github.com/typelevel/fs2/issues/2931.
As I understand it, interruptibility [doesn't come for free](https://github.com/typelevel/cats-effect/blob/7cb291426cadb359c786b1d318a46bced55d4ba3/core/jvm/src/main/scala/cats/effect/IOFiberPlatform.scala#L27-L146). How do we feel about placing it in the hot path here? Maybe it should be configurable?

Use `interruptible` in `writeOutputStream`

---

core/shared/src/main/scala/fs2/Stream.scala

Fixes https://github.com/typelevel/fs2/issues/2903, which I found new sympathy for while working on https://github.com/typelevel/fs2/issues/2931.
This allows a third parameter to be passed to `Stream.fromIterator` indicating whether to use `Delay`, `Blocking`, `Interruptible`, or `InterruptibleMany`.

Make `Stream.fromIterator` sync type configurable

---

core/shared/src/main/scala-2.12/fs2/PartiallyAppliedFromBlockingIteratorCrossCompat.scala
core/shared/src/main/scala-2.13+/fs2/PartiallyAppliedFromBlockingIteratorCrossCompat.scala
core/shared/src/main/scala/fs2/Stream.scala

Fixes https://github.com/typelevel/fs2/issues/2939.
This was my fault due to changes in https://github.com/typelevel/fs2/pull/2933.
Inline comments below.

Fix bincompat of `PartiallyAppliedFromIterator` on Scala 2.12

---

build-site.md

The `sbt "microsite / mdoc"` command lands the compiled microsite in the `mdoc/target/mdoc` directory instead of `target/website`.

Update build-site.md guide

---

build.sbt
core/js/src/main/scala/fs2/compression/CompressionPlatform.scala
core/js/src/main/scala/fs2/compression/GunzipResult.scala
core/jvm/src/main/scala/fs2/compression/CompressionPlatform.scala
core/jvm/src/test/scala/fs2/JvmCompressionSuite.scala
core/shared/src/main/scala/fs2/compression/Compression.scala
core/shared/src/test/scala/fs2/CompressionSuite.scala
io/js/src/main/scala/fs2/io/compressionplatform.scala
io/js/src/main/scala/fs2/io/internal/facade/zlib.scala
io/js/src/test/scala/fs2/io/NodeJSCompressionSuite.scala
io/jvm/src/main/scala/fs2/io/compressionplatform.scala
io/shared/src/main/scala/fs2/io/compression.scala

Closes https://github.com/typelevel/fs2/pull/2771, with many apologies to @yurique for their heroic effort on that 🙏 
In https://github.com/typelevel/fs2/pull/2771 we attempted to cross-build the existing Gzip implementation on the JVM. Instead, this PR delegates directly to the Node.js Gzip implementation. This is better for performance and is much simpler to implement. However, we are unable to support the optional headers for filename, comment, and timestamp. Fortunately http4s does not require these in its Gzip middlewares.
There is an unfortunate amount of duplication of tests and scaladocs in this PR.

Node.js Gzip

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/test/scala/fs2/ChunkSuite.scala

When a `Chunk` is backed by `ByteBuffer` it is not necessary to copy the bytes to convert it to a `ByteVector`. This PR implements the conversion by creating a `ByteVector` "view" that directly wraps the chunk's underlying `ByteBuffer`.

Optimize `Chunk#toByteVector` when backed by a `ByteBuffer`

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala

Due to the way meteredStartImmediately is implemented the delay between the first and the second emitted element exhibits different behaviour than the delay beteen the Nth and (N+1)th element. This is noticible whenever processing of the first element takes significant time. The first delay behaves like in `fixedDelay` and the remaining delays behave like in `fixedRate`. 
In f87b1944e42a5c88d674e8494ccdf65d9ca4dd28 I reproduced the issue with a new test based on the existing "metered should not wait between events that last longer than the rate".
In 9286953c5701a6cc9c9cdc33934d22be2e491b16 I introduced `fixedRateStartImmediately` and then used it to implement `meteredStartImmediately`.
I introduced the startImmediatelly behaviour as a separete method `fixedRateStartImmediately` (like …

Fix `meteredStartImmediately` first delay timing

---

io/js/src/main/scala/fs2/io/net/tls/TLSContextPlatform.scala
io/js/src/main/scala/fs2/io/net/tls/TLSSocketPlatform.scala
io/js/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala
io/js/src/test/scala/fs2/io/net/tls/TLSSuite.scala

This is what I meant to fix before I got distracted by https://github.com/typelevel/fs2/security/advisories/GHSA-2cpx-6pqp-wf35.
The problem came up in the ember h2 client, which needs to know the negotiated application protocol. On the JVM side, writing a `Chunk.empty` to the socket kickstarts the handshaking and blocks (semantically, hopefully) until it completes. So the negotiated application protocol is available in the next operation.
```scala
_ <- Resource.eval(tlsSocket.write(Chunk.empty))
protocol <- Resource.eval(H2TLS.protocol(tlsSocket))
```
https://github.com/http4s/http4s/blob/7fcbd6d58b923a5cae7c66100845c6dd1a857498/ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala#L142-L143
Unfortunately this trick does not work for JS. So the `write` was completing …

Return client `TLSSocket` only after handshake is complete on Node.js

---

core/shared/src/main/scala-3/fs2/ChunkPlatform.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/test/scala/fs2/ChunkSuite.scala

It is now guaranteed to be copy-free.

Specialize every `Chunk`-to-`ByteVector` conversion

---

protocols/shared/src/main/scala/fs2/protocols/ip/IpHeader.scala
protocols/shared/src/main/scala/fs2/protocols/ip/Ipv4Header.scala
protocols/shared/src/main/scala/fs2/protocols/ip/Ipv6Header.scala
protocols/shared/src/main/scala/fs2/protocols/pcap/CaptureFile.scala

Realized we should add these when working on udp-replay: https://github.com/mpilquist/udp-replay

Unify ipv4 and ipv6 header parsing and provide shortcut for parsing udp datagrams from a pcap file

---

core/shared/src/main/scala/fs2/internal/InterruptContext.scala
core/shared/src/test/scala/fs2/StreamInterruptSuite.scala

Fix  hanging when combining `Stream.eval(F.canceled)` and `interruptWhen`.
I believe that the `.as(canceledError)` is safe as our `fa.attempt` was canceled which means that cancelation is unmasked in this scope and hence `F.canceled.as(canceledError) <-> F.canceled`. This matches the behaviour in `Scope#interruptibleEval` when there is no interrupt context and it binds `fa.attempt` directly.

Weird interaction between cancelation and interruptWhen

---

build.sbt
io/js/src/main/scala/fs2/io/internal/facade/events.scala
io/js/src/main/scala/fs2/io/net/tls/TLSContextPlatform.scala
io/js/src/main/scala/fs2/io/net/tls/TLSSocketPlatform.scala
io/js/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala

This is the bug I discovered while working on https://github.com/typelevel/fs2/pull/2958#issue-1321593368. Skunk also hit it in https://github.com/tpolecat/skunk/pull/696. This was a regression due to https://github.com/typelevel/fs2/pull/2957.
If an error occurred during TLS handshaking on Node.js it was hanging waiting on the `'secure'`/`'secureConnect'` event to indicate the handshake completed. This PR relocates the `'error'` listener such that it will short-circuit the await for a `'secure'`/`'secureConnect'` event if it emits.

Short-circuit JS TLS handshake listener if an error event is emitted

---

core/shared/src/main/scala/fs2/internal/Scope.scala
core/shared/src/test/scala/fs2/BracketSuite.scala

Possibly fixes https://github.com/typelevel/fs2/issues/2966?

Bracket finalizer should be uncancelable

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpawnSuite.scala
core/shared/src/test/scala/fs2/StreamSuite.scala

Context : https://discord.com/channels/632277896739946517/632310980449402880/1007228488555708476
This changes the implementation of `spawn` in order for the resulting stream to fail when the background stream fails, aligning it with the semantics of `concurrently`. This makes spawn behaviouraly equivalent to `Stream(()).concurrently(self)`, whilst still exposing a handle to the background fiber, allowing for its manual cancelation. 
If changing the existing behaviour of "spawn" is deemed risky, could another name be suggested ? (if the addition is considered valuable by the maintainers, that is)

Align the semantics of spawn with the ones of concurrently

---

io/js/src/main/scala/fs2/io/net/SocketGroupPlatform.scala
io/js/src/main/scala/fs2/io/net/unixsocket/UnixSocketsPlatform.scala
io/jvm/src/main/scala/fs2/io/net/SocketGroupPlatform.scala

Currently when opening an socket, other exception-throwing operations were attempted within the same `delay` block. If these operations threw an exception, the socket acquire would be deemed failed, and the resource finalizer which closes the socket would not run, thereby leaking the socket.
The acquire phase of the resource must end as soon as the socket is opened; this ensures that it will be closed even if there are subsequent errors.
H/t the native cross-build for discovering this one 😁

Prevent socket leaks due to post-open exceptions

---

core/shared/src/main/scala/fs2/text.scala

Clarify a potentially confusing aspect of the decoding API

Docs for utf8 decoding

---

core/shared/src/main/scala/fs2/Chunk.scala

Override and short-circuit `Chunk.flatten` method. This should help out `http4s` when parsing JSON bodies via circe.
Currently JSON is parsed via the follow method:
https://github.com/http4s/http4s/blob/fbcbcf3e23031a5ebba3c8f24b3486f0f5d956a8/circe/src/main/scala/org/http4s/circe/CirceInstances.scala#L55
Which calls
https://github.com/http4s/http4s/blob/fbcbcf3e23031a5ebba3c8f24b3486f0f5d956a8/core/shared/src/main/scala/org/http4s/EntityDecoder.scala#L208
The latter method calls `Chunk.flatten`.
From what I can tell (this one is for http4s people), most requests (depending on size) will contain one chunk, so the short-circuit in this PR should reduce allocations and reduce CPU usage quite a lot.
A brief jmh benchmark shows this obviously has a big impact, as now `flatten` in certain …

Override and short-circuit Chunk.flatten

---

.github/workflows/ci.yml
build.sbt

Gets us out of dependency hell with brew glibc (used by brew s2n-tls) being newer than the glibc ubuntu-20 is using.

Use ubuntu-22.04 for ci

---

core/shared/src/main/scala/fs2/text.scala
core/shared/src/test/scala/fs2/TextSuite.scala

Fixes the buffering demonstrated in this snippet:
```scala
//> using lib "co.fs2::fs2-core::3.3.0"
import fs2._
@main def main = Stream[Pure, Byte](49, 50, 51, 52).chunkLimit(1).unchunks
.through(text.utf8.decode).debugChunks().compile.drain
```
```
Chunk(1, 2, 3)
Chunk(4)
```
h/t @mn98 for the report.

Aggressively short-circuit `processByteOrderMark` to avoid unnecessary `utf8.decode` buffering

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

- Add a `unit` chunk, which is just a singleton that contains a unit. 
- Add an `outUnit` Pull, which is just an `Output` around that chunk. Use it in a few places within Pull. 
- Add an `unit` Stream, which merely emits one unit value and ends.
-

Extract Unit Chunks, Pull, Stream. 

---

io/js-jvm/src/main/scala/fs2/io/net/Network.scala
io/native/src/main/scala/fs2/io/net/Network.scala
io/shared/src/main/scala/fs2/io/file/Files.scala

This way I can implement `Network` and `Files` in the `fs2.io.uring` package. Future projects may want to implement them in e.g. `fs2.libuv`.

Make some unsealeds less private

---

io/native/src/main/scala/fs2/io/net/tls/TLSContextPlatform.scala

Cipher preferences aka "security policies" are described here:
https://github.com/aws/s2n-tls/blob/9b91aca9732e1ee32befee66b8897b6cceb04499/docs/USAGE-GUIDE.md#security-policies
The default "default" does not enable TLS 1.3. However, this was annoying in practice, and also the s2n documentation says that:
> Currently TLS 1.2 is our default version, but we recommend TLS 1.3 where possible. To use TLS 1.3 you need a security policy that supports TLS 1.3.
https://github.com/aws/s2n-tls/blob/9b91aca9732e1ee32befee66b8897b6cceb04499/docs/USAGE-GUIDE.md#supported-tls-versions
So this PR now sets the "default_tls13" cipher preference for the default system and insecure `TLSContext`s. The `S2nConfig` builder itself does not set any preference.

Use `default_tls13` for system s2n cipher prefs

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Stream.scala

When creating a constant stream, out of constant chunks, we do not need to allocate a list of 256 nodes with the same value. instead we can just write a chunk as a constant function.

Chunk - Introduce a Constant Chunk subclass.

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/test/scala/fs2/StreamSuite.scala

Fixes #3011 
Issue 3011 https://github.com/typelevel/fs2/issues/3011 showed an existing StackOverflow loop, caused by the short-cut optimisation of `transformWith` together with the recursion. This only happened when the stream included a `FlatMapOutput` such that 
- The chunk is too large, since the size of the stack is proportional to the number of elements in the chunk. 
- The "seeding" function was immediately returning an empty stream, that is, a `Succeeded(())`. 
The solution is to add an internal whirl-loop, which optimises this cyclic path away in tail-recursive way. We also add the reported case as a unit test.

Fix StackOverflow bug 3011.

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

We may like method calls, even extension methods, better than functions. Plus, we need fewer type arguments in the calls.

Pull: turn flatMapOutput into an extension method.

---

core/shared/src/main/scala/fs2/Stream.scala

Optimise evalMapFilter

---

benchmark/src/main/scala/fs2/benchmark/TextBenchmark.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/text.scala
core/shared/src/test/scala/fs2/TextSuite.scala

Avoids problems like multiple BOMs when encoding with a charset that adds them (UTF-16).
Opening as a draft as there's a problem with backwards compatibility, see inline comments.
Closes #3006

Use CharsetEncoder for encoding texts

---

core/shared/src/main/scala/fs2/Stream.scala

The number of quotes does not match, therefore the section is not rendered as intended.
That is how it looks right now:

`Stream#uncons` update Scala doc

---

core/shared/src/main/scala/fs2/concurrent/Signal.scala

So that the first element (i.e. the current state of the `Signal`) may be emitted before bracketing.

Minor refactor to `SignallingRef#discrete`

---

io/jvm-native/src/main/scala/fs2/io/net/SocketPlatform.scala

Instead of `ByteBuffer.allocateDirect`-backed chunks. The JDK says this about direct byte buffers.
> The buffers returned by this method typically have somewhat higher allocation and deallocation costs than non-direct buffers. The contents of direct buffers may reside outside of the normal garbage-collected heap, and so their impact upon the memory footprint of an application might not be obvious. It is therefore recommended that direct buffers be allocated primarily for large, long-lived buffers that are subject to the underlying system's native I/O operations. In general it is best to allocate direct buffers only when they yield a measurable gain in program performance.
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/ByteBuffer.html
I wouldn't say that the average …

Copy socket reads into `Array`-backed chunks

---

build.sbt

I could have sworn I did this in https://github.com/typelevel/fs2/pull/3000, but I guess I forgot. A minor bump for the Scala 3.2.0 bump.

Bump base version to 3.4

---

core/shared/src/test/scala/fs2/concurrent/ChannelSuite.scala

The `Channel` test suite at present doesn't actually cover all of its semantics. In reimplementing it, I also had to beef up the test suite to avoid regressions. These tests are cherry-picked here.

Cherry-picked additional tests from #2856

---

build.sbt
io/native/src/test/scala/fs2/io/net/tls/TLSSuite.scala

I suspect this is what has been causing the CI flakes. So disabling should confirm it, and also save us the headache until this is fixed upstream.

Disable embedded resources on Native

---

core/shared/src/main/scala/fs2/Stream.scala

existing:
- `hold` takes an initial value for the signal
- `holdOption` uses `None` as the initial value for the signal
this PR:
- `hold1` blocks until the stream emits its first value, then emits a signal with that initial value
Name (and API) subject to bikeshed of course.

Add `Stream#{hold1,hold1Resource}`

---

io/js/src/main/scala/fs2/io/file/FileHandlePlatform.scala
io/js/src/main/scala/fs2/io/file/FilesPlatform.scala
io/js/src/main/scala/fs2/io/internal/facade/fs.scala
io/shared/src/test/scala/fs2/io/file/FilesSuite.scala

Fixes https://github.com/typelevel/fs2/issues/2921.
Unfortunately not all Node.js APIs support `js.BigInt`, but where they do it offers better compatibility with the `Long`-based APIs exposed in FS2.

Prefer `js.BigInt` fs APIs on Node.js

---

core/shared/src/main/scala/fs2/concurrent/Signal.scala
core/shared/src/test/scala/fs2/concurrent/SignalSuite.scala

Based on https://github.com/typelevel/fs2/pull/3030.
A signalling extension of Cats Effect `MapRef`.

Add `SignallingMapRef`

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/ParEvalMapSuite.scala

Uses a `Channel.unbounded` for `parEvalMapUnbounded` instead of a `Channel.bounded(Int.MaxValue)`.
Also adds `parEvalMapUnorderedUnbounded`.

Specialize `parEvalMapUnbounded`

---

io/js/src/main/scala/fs2/io/file/FileHandlePlatform.scala
io/js/src/main/scala/fs2/io/internal/facade/fs.scala
io/shared/src/test/scala/fs2/io/file/FilesSuite.scala

Fixes a regression from https://github.com/typelevel/fs2/pull/3036.
Turns out I was calling the wrong function and it was silently ignoring the `js.BigInt` parameter. Sadly the correct function is much less ergonomic to use. Node.js APIs are the worst 😕

Fix Node.js `readRange` bug

---

site/concurrency-primitives.md

INothing obsolete since fs2 3.3
Leaving `import scala.language.higherKinds` as needed for Scala versions lower than 2.13.1

Docs/microsite: Added/cleaned imports in the Single Publisher / Mutiple Subscriber example

---

.github/workflows/ci.yml
build.sbt
core/js/src/main/scala/fs2/hash.scala
core/js/src/test/scala/fs2/HashSuitePlatform.scala
core/jvm/src/test/scala/fs2/HashSuitePlatform.scala
core/native/src/main/scala/fs2/hash.scala
core/native/src/test/scala/fs2/HashSuitePlatform.scala
core/shared/src/test/scala/fs2/HashSuite.scala

- On JS, Node.js only. This is the sole Node.js-only thing in core, but meh. Web Crypto doesn't support streaming hashing yet. Further reading:
- https://github.com/w3c/webcrypto/issues/73
- https://github.com/wintercg/proposal-webcrypto-streams
- On Native, requires OpenSSL.

Cross `hash` for JS and Native

---

site/api/index.html

So that https://fs2.io/api/ will redirect to the API unidocs.

Add redirect for API docs

---

io/native/src/main/scala/fs2/io/net/tls/S2nConnection.scala

A similar fix was recently applied to the s2n Tokio integration.
- https://github.com/aws/s2n-tls/pull/3700.

Guarantee blinding on s2n shutdown error

---

build.sbt

I added an optional openssl dep to `coreNative` for hashing in https://github.com/typelevel/fs2/pull/3070. Although the dependency is not needed if hashing is not used, the scodec and protocols modules' tests depend on the test scope of core, which does use hash, and thus openssl becomes a transitive dependency. So it must be configured for them as well.
h/t @TimWSpence

Fix native deps in build

---

core/shared/src/main/scala/fs2/concurrent/Topic.scala
core/shared/src/test/scala/fs2/concurrent/TopicSuite.scala

return empty stream if topic is closed

---

core/shared/src/main/scala/fs2/Stream.scala

`groupWithin` no longer uses a timed pull.

remove outdated scaladoc comment

---

core/shared/src/main/scala/fs2/Stream.scala

Updates the docs for the Stream `exists` method to correctly describe the current implementation.
fixes #3034

Update doc for Stream exists method

---

core/shared/src/main/scala/fs2/Stream.scala

Add `CompileOps.singletonOrError` to compile singleton streams while preserving the intent and raising errors if the stream is not a singleton (which indicates a bug – advantage over `lastOrError`).
Inspired by a Discord discussion: https://discord.com/channels/632277896739946517/632310980449402880/1046091945564459070

Add singletonOrError

---

build.sbt
io/jvm-native/src/main/scala/fs2/io/iojvmnative.scala
io/jvm/src/main/scala/fs2/io/ioplatform.scala
io/native/src/main/scala/fs2/io/ioplatform.scala
io/shared/src/main/scala/fs2/io/io.scala

See updated description in https://github.com/typelevel/fs2/pull/3093#issuecomment-1366256942.
---
This "fixes" the FS2 manifestation of https://github.com/typelevel/cats-effect/issues/3077 where canceling the `stdin` stream hangs, because you cannot interrupt a blocking read from stdin.
"Fixes" because this is a cantfix: we just leak the blocked thread. The docs are updated to recommend you only compile the `stdin` stream at most once in a program, to mitigate this.
Couldn't think how to test this without setting up lots of infrastructure like we do in Cats Effect to test `IOApp`.

Run `fs2.io.stdin` on dedicated single-threaded pool

---

build.sbt
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

- Pull - Add an uncons extension method for closed Pulls (unit)
- Stream - Avoid "newStream" use streamNoScope
- Avoid the ".pull" method, use the new ".uncons" method on Pull-Unit

Replace "ToPull" operations with "Pull.uncons"

---

core/shared/src/main/scala/fs2/concurrent/Signal.scala
core/shared/src/test/scala/fs2/concurrent/SignalSuite.scala

This refactoring of `SignallingMapRef` fixes a bug with the `lastUpdate` counter that caused "spurious" updates to be emitted at keys that had not actually been updated.
This could be observed as a sort of race condition, when a listener at one key was unable to resubscribe before there was an update at another key. For example:
1. a listener on key `k1` is notified of an update. it records the `lastUpdate`
2. key `k2` is updated, and `lastUpdate` is incremented
3. the listener on `k1` attempts to resubscribe and sees that `lastUpdate` does not match its records. So it assumes there was an update (there wasn't, at least not at `k1`) and emits a duplicate value. Woops.
To fix this, we need to have a separate `lastUpdate` counter for each key. But that will quickly become a memory leak. …

Fix last-update tracking in `SignallingMapRef`

---

build.sbt
reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamSubscription.scala
reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamUnicastPublisher.scala
reactive-streams/src/main/scala/fs2/interop/reactivestreams/package.scala
reactive-streams/src/test/scala/fs2/interop/reactivestreams/CancellationSpec.scala
reactive-streams/src/test/scala/fs2/interop/reactivestreams/StreamUnicastPublisherSpec.scala

Improves the current implementation of `interop.reactivestreams.StreamUnicastPublisher` to allow it to be subscribed by multiple `Publishers` and gracefully cancel active `Subscriptions` when the `Resource` is closed.
-----
**Roadmap**.
-----
Related to #3102

Fix interop.reactivestreams.StreamUnicastPublisher

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala
core/shared/src/test/scala/fs2/StreamMergeSuite.scala

An implementation of "merge-sort" merging for two streams of sorted data.
This might be useful in practice when combining streams from different underlying sources.
[Discord conversation](https://discord.com/channels/632277896739946517/632310980449402880/1063932797145849888)

Add .interleaveOrdered to combine sorted streams (i.e. "merge-sort")

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala

Adds a `limit` combinator to `Stream`, which emits the first n elements and raises an error if there are more elements.
I've implemented this a few times recently, and it seems to be sufficiently general to be worth implementing efficiently as a canoncial combinator. Example use case might be a middleware which enforces size limits on streams.
I'm not sure what the desired approach is to combinator generality - so it's completely fine if the consensus here is that it's not useful enough to warrant being included in the `Stream` API. Also hppy to rework the naming if desired, alternatives might be `limitOrError` or something like `maxSize`.
---
Target the `main` branch if this PR is targeted for the 3.x series and the `series/2.5.x` branch if targeted for the 2.5.x …

Add limit combinator to Stream

---

io/native/src/main/scala/fs2/io/net/tls/S2nConnection.scala
io/native/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala

Ember H2 in particular was tripping on it here:
https://github.com/http4s/http4s/blob/91adfbc3f998085b22f8b45354d8d56c3d14099e/ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala#L144
It uses an empty write as a hack to trigger handshaking on the JVM, which is not relevant to the Native implementation. But it's still a legit bug :)
H/t @bishabosha, thanks!

Correctly handle TLS empty writes in `S2nConnection`

---

io/shared/src/main/scala/fs2/io/file/Files.scala
io/shared/src/test/scala/fs2/io/file/FilesSuite.scala

This shows a problem with `Files[F].walk` where it does not walk the whole file tree if files are deleted during the process.  The added tests fails with:
```
==> X fs2.io.file.FilesSuite.walk - can delete files in a nested tree  0.029s munit.ComparisonFailException: fs2/io/shared/src/test/scala/fs2/io/file/FilesSuite.scala:537
536:        .foldMonoid
537:        .assertEquals(25)
538:    }
values are not the same
=> Obtained
5
=> Diff (- obtained, + expected)
-5
+25
```
Only 5 files out of 25 where deleted. I expected that the whole process deletes 25 files because `tempFilesHierarchy` creates 5 child directories with 5 files in each child directory.
If `Files[IO].deleteIfExists(path).as(1)` is replaced with `IO.pure(1)` the test passes.

Mask `getBasicFileAttributes` errors in `Files[F].walk`

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/concurrent/SignalSuite.scala

Fixes https://github.com/typelevel/fs2/issues/3081.

Fix `hold1`

---

io/js/src/main/scala/fs2/io/file/Flag.scala
io/js/src/main/scala/fs2/io/internal/facade/fs.scala

Thanks to @sherpal for reporting! Update: they confirmed the fix works ✅ 
Stack trace:
<details>
```
<ref *2> $c_Lorg_scalajs_linker_runtime_UndefinedBehaviorError [org.scalajs.linker.runtime.UndefinedBehaviorError]: java.lang.ClassCastException: undefined cannot be cast to java.lang.Double
at $throwClassCastException (file:///C:/Users/antoi/IdeaProjects/Ejoti/server/target/scala-3.2.0/server-fastopt/main.js:55:9)
at $uD (file:///C:/Users/antoi/IdeaProjects/Ejoti/server/target/scala-3.2.0/server-fastopt/main.js:532:73)
at $c_Lfs2_io_file_Flag$ (https://raw.githubusercontent.com/typelevel/fs2/v3.5.0/io/js/src/main/scala/fs2/io/file/Flag.scala:43:19)
at $m_Lfs2_io_file_Flag$ (https://raw.githubusercontent.com/typelevel/fs2/v3.5.0/io/js/src/main/scala/fs2/io/file/Flag.scala:31:8)
at …
```

Use `UndefOr` for Node.js file `Flag`s not supported on windows

---

core/shared/src/main/scala/fs2/concurrent/Signal.scala
core/shared/src/test/scala/fs2/concurrent/SignalSuite.scala

The motivation for this comes from Calico, where we want to get the current value of a `Signal` for immediate rendering, and also a handle to a `Stream` of discrete updates, that we can subscribe to _at some later point_ (typically after rendering) (or not at all), without missing any updates.
FWIW I did try the "hack" of `get` followed by `discrete.drop(1)`, and this ended up breaking in some situations.
I also tried inlining the default implementation here in Calico, but there is a noticeable performance difference (where by "noticeable", I mean visible UX latency in a webapp).
Suffice to say, the win comes from the fact that each `Signal` can override this with something more efficient (basically just a `.get`) than the default `uncons1` implementation.
Furthermore, `get` and …

Add `Signal#getAndDiscreteUpdates`

---

site/getstarted/install.md

The latest fs2 versions can't be used with Scala 3.0. Although a version matrix for Scala 3 would be more accurate, I feel we can simplify things a bit.

Highlight Scala 3.2 usage in docs

---

io/js/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala
io/jvm/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala

Seems that these are failing in CI now.

Don't test TLSv1, v1.1 on Node.js, fix JVM TLS error test

---

core/shared/src/main/scala/fs2/Chunk.scala

We had some unsuspended uses of `toByteBuffer` which I am fixing in d76bdea6cd9256314ef3df26014f3cedaeeeda72.

Optimize `Chunk#to{Byte,Char}Buffer`, add note about mutability

---

build.sbt
core/shared/src/main/scala/fs2/concurrent/Channel.scala
core/shared/src/main/scala/fs2/concurrent/Signal.scala
core/shared/src/main/scala/fs2/internal/ScopedResource.scala
core/shared/src/test/scala/fs2/StreamInterruptSuite.scala
io/jvm-native/src/main/scala/fs2/io/net/SocketGroupPlatform.scala
io/jvm-native/src/main/scala/fs2/io/net/SocketPlatform.scala
io/jvm/src/main/scala/fs2/io/net/tls/TLSEngine.scala
io/jvm/src/main/scala/fs2/io/net/tls/TLSSocketPlatform.scala
io/jvm/src/main/scala/fs2/io/net/unixsocket/UnixSocketsPlatform.scala
io/native/src/main/scala/fs2/io/net/tls/TLSSocketPlatform.scala

1. Fixes for new `async` cancellation semantics. Also plug some resource leaks.
2. Prefer performance-enhanced `Mutex` to `Semaphore(1)`
3. Prefer `flatModify` to `modify(...).flatten`, fixes at least a few cancellation-related bugs

Update to Cats Effect v3.5.0-RC2

---

build.sbt
io/js/src/main/scala/fs2/io/ioplatform.scala
io/jvm-native/src/main/scala/fs2/io/net/SocketGroupPlatform.scala

Canaries https://github.com/typelevel/cats-effect/pull/3205.

Fix `async_` usages for new uncancelable semantic

---

io/jvm/src/main/scala/fs2/io/net/unixsocket/JdkUnixSockets.scala
io/jvm/src/main/scala/fs2/io/net/unixsocket/JnrUnixSockets.scala
io/jvm/src/main/scala/fs2/io/net/unixsocket/UnixSocketsPlatform.scala

I'm working on supporting HTTP/2 over unix sockets in Ember and was experiencing a lot of strange issues e.g. non-deterministic behavior, reads returning empty chunks, hanging.
The bad news was that I was unable to replicate these issues as unit tests 🤔 this is where I started from, focused on just the empty read issue, before I gave up and went for the refactor.
The good news is that I published a snapshot and (spoiler alert) was surprised to discover that this refactor somehow fixed everything 😅 wasn't really expecting that.
This refactor mostly addresses these three issues:
1. Not switching the sockets to non-blocking mode. I suspect that this was what was causing the empty reads bug in Ember. Non-blocking mode is only useful if you are using a selector to poll for events on the …

Refactor JVM unixsockets

---

io/js/src/main/scala/fs2/io/file/FilesPlatform.scala
io/js/src/main/scala/fs2/io/internal/facade/os.scala
io/jvm-native/src/main/scala/fs2/io/file/FilesPlatform.scala
io/shared/src/main/scala/fs2/io/file/Files.scala
io/shared/src/test/scala/fs2/io/file/FilesSuite.scala

Hello!
That's my first contribution to fs2, so I hope everything is where it should be.
I added two helpers to `Files[F]` that mirror the ones already present for `readUtf8` and `readUtf8Lines`, shamelessly stealing the idea from [this](https://github.com/typelevel/toolkit/issues/15#issuecomment-1464156091) @armanbilge comment.
I haven't found any unit tests for `readUtf8` and `readUtf8Lines` but for their components, and since `writeUtf8` and `writeUtf8Lines` are built on the same ones, I haven't added any.
It may be worth adding these new combinators to fs2 2.5.x and adding an example like `Stream.emit("foo").through(Files[IO].writeUtf8Lines(Path(...)))` to the documentation.

Added writeUtf8 and writeUtf8Lines

---

io/js/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala
io/jvm/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala
io/native/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala

Receiving any HTTP response, regardless of status code, indicates that we've successfully established a TLS connection, right?

Relax status check for google TLS tests

---

build.sbt
core/jvm-native/src/main/scala/fs2/compression/CompressionPlatform.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala
io/js-jvm/src/main/scala/fs2/io/net/Network.scala
io/js/src/main/scala/fs2/io/compressionplatform.scala
io/js/src/main/scala/fs2/io/file/FilesPlatform.scala
io/js/src/main/scala/fs2/io/net/NetworkPlatform.scala
io/js/src/main/scala/fs2/io/net/unixsocket/UnixSocketsPlatform.scala
io/jvm-native/src/main/scala/fs2/io/compressionplatform.scala
io/jvm-native/src/main/scala/fs2/io/file/FileHandlePlatform.scala
io/jvm-native/src/main/scala/fs2/io/file/FilesPlatform.scala
io/jvm-native/src/main/scala/fs2/io/file/ReadCursorPlatform.scala
io/jvm-native/src/main/scala/fs2/io/file/Watcher.scala
io/jvm-native/src/main/scala/fs2/io/file/WriteCursorPlatform.scala
io/jvm-native/src/main/scala/fs2/io/file/file.scala
io/jvm/src/main/scala/fs2/io/net/NetworkPlatform.scala
io/jvm/src/main/scala/fs2/io/net/unixsocket/JdkUnixSockets.scala
io/jvm/src/main/scala/fs2/io/net/unixsocket/JnrUnixSockets.scala
io/jvm/src/main/scala/fs2/io/net/unixsocket/UnixSocketsPlatform.scala
io/native/src/main/scala/fs2/io/net/NetworkPlatform.scala
io/shared/src/main/scala/fs2/io/file/Files.scala
io/shared/src/main/scala/fs2/io/net/NetworkLowPriority.scala
site/faq.md

Discord thread: https://discord.com/channels/632277896739946517/839257183782436945/1087761519477014644
Continuing from https://github.com/Comcast/ip4s/pull/475.
**tl;dr**: The motivation for removing the implicit implementation for generic `F[_]` is to force tagless final libs to declare _all_ of their constraints (e.g. `Network`) instead of deriving them on-the-spot from e.g. `Async`. Meanwhile, this change will be completely transparent to code written in concrete `IO`.
This is source-breaking but binary-compatible.
Changes were made to:
- `Compression`
- `Network`
- `UnixSockets`
- `Files`, which impacted internal code

Implicit instances for `IO` only

---

core/shared/src/test/scala/fs2/ParEvalMapSuite.scala

According to the test spec the result may not be in the correct order, but the assertion check for exact equality. 
- adjusting `parEvalMapUnordered` test to reflect spec, by using assertion that does not check for ordering
- removing no longer used `run` helper method

fixing assertion in parEval test

---

core/jvm-native/src/main/scala/fs2/compression/CompressionPlatform.scala
io/js/src/main/scala/fs2/io/compressionplatform.scala
io/js/src/main/scala/fs2/io/net/NetworkPlatform.scala
io/js/src/main/scala/fs2/io/net/unixsocket/UnixSocketsPlatform.scala
io/jvm-native/src/main/scala/fs2/io/compressionplatform.scala
io/jvm/src/main/scala/fs2/io/net/NetworkPlatform.scala
io/jvm/src/main/scala/fs2/io/net/unixsocket/UnixSocketsPlatform.scala
io/native/src/main/scala/fs2/io/net/NetworkPlatform.scala
io/shared/src/main/scala/fs2/io/file/Files.scala
io/shared/src/main/scala/fs2/io/process/Processes.scala

Follow-up to https://github.com/typelevel/fs2/pull/3179, where we relax from implicits only for `IO` to implicits for any `LiftIO`. This makes instances available for transformers in `IO` e.g. `Kleisli[IO, ...]`.
I would have preferred to follow https://github.com/Comcast/ip4s/pull/478 and implicitly derive instances for transformers from an implicit instance of the underlying effect. This is more challenging in FS2, because any API which exposes a `Pipe` can no longer be trivially `mapK`ed / `translate`d with just an `F ~> G` function. Still I was determined enough to explore this in https://github.com/typelevel/fs2/commit/c894c5bb16e23e4343aa5fb9a45cf6055ed3a67b which demonstrates that with re-architecting it is possible to implement a `mapK`/`translate` for these APIs. But the work / …

Offer implicits for any `LiftIO`

---

core/shared/src/main/scala/fs2/Chunk.scala

If our Applicative F is actually an instance of `StackSafeMonad`, we can avoid the default implementation of traverse_, which is based on a `foldRight` method of Foldable and has to allocate a set of `Eval` objects. Instead, we can just loop on the monad itself.
_Note_ Given that in practice Streams are mostly used with IO-like datatypes which are stack-safe, this should have some impact.

Chunk - Add optimised traverse_ for StackSafeMonad.

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSuite.scala

It wants to fix #3187
It's my first time to PR typelevel! If there's something I need to improve or change, I'm willing to do that!

Fix unintended unchunking by adding override map

---

core/js/src/main/scala/fs2/ChunkRuntimePlatform.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/test/scala/fs2/ChunkSuite.scala

1. Specializes `Chunk#toArraySlice` for `ByteVector` and `{Byte,Char}Buffer` to avoid array copies.
2. Fix class cast exceptions in `Chunk.{Byte,Char}Buffer#toArray`.
3. Avoid converting buffers to read-only, since this prevents access to underlying array.
4. Use `toArraySlice` to implement `to{Byte,Char}Buffer`

Specialize `Chunk#toArraySlice`

---

site/guide.md

I believe gitter is deprecated now. And I use the discord link from readme.

Use Discord typelevel channel instead of gitter in Guide page

---

core/shared/src/main/scala/fs2/concurrent/Signal.scala
core/shared/src/test/scala/fs2/concurrent/SignalSuite.scala

Fixes a bug where `getAndDiscreteUpdates` for a `Signal` created via `Signal#ap` was not emitting updates until both of its upstream signals emitted at least one change.
The new implementation delegates to `getAndDiscreteUpdates` of the upstream signals, which both simplifies it and will be more performant for `Signal`s that override that method.
h/t @noelwelsh for reporting in https://github.com/creativescala/gooey/commit/34173c61257fb7f91c3d2fbbf62553f442d5f2d7

Fix `Signal#ap` bug in `getAndDiscreteUpdates`

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala

- Fixes #3169
- Adding missing tests around error/interruption propagation
- Adding stress/integrity test
increasing supply by `Int.MaxValue + chunkSize` on upstream `finalization` to prevent the supply semaphore from blocking when upstream is interrupted while downstream is waiting for the timeout to expire or to have enough elements
- the `stress test: all elements are processed` test is nothing but a copy of the benchmark with and integrity check at the end. While it may seem redundant (i.e. `should never lose any elements` should cover it), in reality it is possible to write an [implementation](https://github.com/typelevel/fs2/pull/3162) that passes that test but fails this one. (~on a side note, that explains the big performance gain of the implementation linked earlier, so~ having …

Fixing interruption behaviour

---

core/shared/src/main/scala/fs2/text.scala
core/shared/src/test/scala/fs2/TextSuite.scala

The methods in the `text` package operate on `String`s. This is the optimal choice for most of the use cases. In some scenarios, however, a stream of `Char`acters may be required (at least I needed it). Although the conversion is a one-liner, it is not apparent how to do it at first (at least it wasn't to me). I think these simple conversion methods may be of use to others and nicely fit to the purpose of `text` package.
I'm not fully sure if the proposed naming is correct - maybe `stringToChar` is a preferred one?
As a comment to the reviewer, both methods may be implemented at least one more way:
```Scala
def string2char[F[_]]: Pipe[F, String, Char] = _.map(s => Chunk.array(s.toCharArray)).flatMap(Stream.chunk)
def char2string[F[_]]: Pipe[F, Char, String] = _.chunks.map(c => new …
```

Add String to Char and Char to String conversion

---

io/jvm-native/src/main/scala/fs2/io/net/SocketPlatform.scala
io/jvm/src/test/scala/fs2/io/IoPlatformSuite.scala

Sometimes the socket is already closed by the time the read/write canceler is invoked, causing an annoying error log via Cats Effect's unhandled error reporter. So we suppress the error.
Closes https://github.com/disneystreaming/weaver-test/issues/668.

Suppress errors in socket read/write canceler

---

site/_coverpage.md
site/documentation.md
site/scodec.md

It's also helpful to run `sbt prePR`, which runs tests, generates docs, and performs various checks.

Fix skunk doc link in cover page

---

io/js/src/main/scala/fs2/io/net/tls/TLSSocketPlatform.scala
io/js/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala

Fix `TLSSocket` addresses on JS

---

io/js/src/main/scala/fs2/io/internal/facade/tls.scala
io/js/src/main/scala/fs2/io/net/tls/TLSContextPlatform.scala
io/js/src/main/scala/fs2/io/net/tls/TLSSocketPlatform.scala
io/js/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala

We had a test, but it wasn't working properly for server-side TLS sockets. So I fixed that.
In the end fussing with `'session'` events was more complicated and didn't seem to work for server sockets anyway. Even though the docs warn against it for TLS v1.3 `getSession()` seems to work fine 🤔 
> Note: `getSession()` works only for TLSv1.2 and below. For TLSv1.3, applications must use the `'session'` event
https://nodejs.org/api/tls.html#tlssocketgetsession
Well, let me double-check that before we merge 😅 
Another one h/t @etspaceman

Fix TLS session access on JS

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/Generators.scala
core/shared/src/test/scala/fs2/HashSuite.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala
core/shared/src/test/scala/fs2/StreamInterruptSuite.scala
io/js/src/test/scala/fs2/io/IoPlatformSuite.scala

To give some context, @djspiewak  and I were looking through `merge` and found the implementation difficult to understand, then tried to rewrite it to use new cats-effect primitives.
I'm not sure that the code I've settled on is actually any better than the old implementation, but think it's worth getting a second opinion on. 
The main differences are:
- The use of `SingallingRef` over two `Deferred`s for managing the upstream state.
- The use of `evalMap(guard.aquire)` instead of an explicit pull for pulling from upstream.

Refactor merge implementation

---

core/shared/src/main/scala/fs2/Stream.scala

The four parJoin variants, namely bounded/unbounded and ordered/unordered, delegate to `parEvalMapActionImpl` passing it a `initFork` function. These `initFork` action can be reduced to two cases, depending on whether the parJoin has to preserve order or not. Thus, we can replace the function argument with a boolean flag to `parEvalMapActionImpl`, and write the `initFork` cases inside the latter.

Stream - Refactor Parjoins

---

core/shared/src/main/scala/fs2/Stream.scala

Separate consumer and producer parts.

Stream - BroadcastThrough - refactor code

---

core/shared/src/main/scala/fs2/Stream.scala

Repo with the benchmark: https://github.com/kamilkloch/fs2-tests
Alternative implementation of `Stream.fromQueueUnterminated`, replacing
```scala
private def fromQueueNoneTerminatedSingletons_[F[_], A](
take: F[Option[A]],
tryTake: F[Option[Option[A]]],
limit: Int
): Stream[F, A] = {
def await: Stream[F, A] =
Stream.eval(take).flatMap {
case None => Stream.empty
case Some(c) =>
val builder = collection.mutable.Buffer.newBuilder[A]
builder += c
pump(1, builder)
}
def pump(
currSize: Int,
acc: collection.mutable.Builder[A, collection.mutable.Buffer[A]]
): Stream[F, A] =
if (currSize == limit) Stream.emits(acc.result()) ++ await
else
Stream.eval(tryTake).flatMap {
case None => Stream.emits(acc.result()) ++ await
case Some(Some(c)) =>
acc += c
pump(currSize + 1, acc)
case Some(None) => …
```

Add variant of `Stream.fromQueueUnterminated` for Monad.

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala

Close #3224.
Ran into this today. I'm not too familiar with the internal implementation of fs2 though so not sure if this is the most optimized way to do it.

Add `Stream.filterNot`

---

io/shared/src/main/scala/fs2/io/file/Files.scala

The fixed comment contradicts with the [comment](https://github.com/typelevel/fs2/compare/main...nikiforo:fix-comment?expand=1#diff-9ec1ae212cbd3462c65322379f67496c8c4274971e5f2e4fe3033c42a69e2cf0R175) above it.
Also, all other comments about methods with explicit `followLinks` attribute in `Files.scala` are used without negation.
Moreover, in sources `followLinks` means `stat`, which follows link.

fix comment about followLinks

---

.sbtopts
benchmark/src/main/scala/fs2/benchmark/ChunkBenchmark.scala
benchmark/src/main/scala/fs2/benchmark/ChunksBenchmark.scala
benchmark/src/main/scala/fs2/benchmark/LinesBenchmark.scala
benchmark/src/main/scala/fs2/benchmark/PullBenchmark.scala
build.sbt
core/shared/src/main/scala-2.12/fs2/ChunkPlatform.scala
core/shared/src/main/scala-2.13+/fs2/Chunk213And3Compat.scala
core/shared/src/main/scala-2.13/fs2/ChunkPlatform.scala
core/shared/src/main/scala-3/fs2/ChunkPlatform.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/text.scala
core/shared/src/main/scala/fs2/timeseries/TimeSeries.scala
core/shared/src/main/scala/fs2/timeseries/TimeStamped.scala
core/shared/src/test/scala-2.13/fs2/ChunkPlatformSuite.scala
core/shared/src/test/scala/fs2/ChunkGenerators.scala
core/shared/src/test/scala/fs2/ChunkQueueSuite.scala
core/shared/src/test/scala/fs2/ChunkSuite.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala
core/shared/src/test/scala/fs2/StreamPerformanceSuite.scala
protocols/shared/src/main/scala/fs2/protocols/mpeg/transport/psi/GroupedSections.scala

Fixes #3271
-----
----
As always, I look forward to your feedback. Especially related to naming, scaladoc, and tests.

Chunk improvements

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala
core/shared/src/test/scala/fs2/StreamSuite.scala

Fixes https://github.com/typelevel/fs2/issues/3276
Not sure if I put the test in the right place, let me know if you'd like to move it!

fix rechunkRandomly with large ending chunk

---

io/js/src/main/scala/fs2/io/IOException.scala
io/js/src/main/scala/fs2/io/internal/facade/AggregateError.scala
io/shared/src/test/scala/fs2/io/net/tcp/SocketSuite.scala

Node.js 20 appears to have started throwing [`AggregateError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError)s in some situations (similar to FS2's `CompositeFailure`) e.g. see https://github.com/typelevel/skunk/pull/935#issue-1833175626. This confounds the `js.Error => java.io.IOException` translation. So now we specially handle `AggregateError` as part of that translation.

Handle `AggregateError`s on Node.js

---

core/shared/src/main/scala/fs2/timeseries/TimeSeries.scala
protocols/shared/src/main/scala/fs2/protocols/pcap/CaptureFile.scala
scodec/shared/src/main/scala/fs2/interop/scodec/StreamDecoder.scala
scodec/shared/src/test/scala/fs2/interop/scodec/StreamCodecSuite.scala

- Fixes bug in `StreamDecoder.{isolate, once, tryOnce, many, tryMany}` where errors were dropped upon reaching end of input stream.
- Fixes an issue in `interpolateTicks` where large gaps in timestamps would unnecessarily allocate lots of memory.
- Improved `CaptureFile` stream decoding.
Originally spotted these issues by trying to use the stream decoder for `CaptureFile` and noticing we'd lose sync on record structure at chunk boundaries.

Fix various issues with PCAP decoding

---

benchmark/src/main/scala/fs2/benchmark/ChunkFlatten.scala
core/shared/src/main/scala/fs2/Chunk.scala

The current flatten performs one Chunk.Queue insertion per source chunk, which means it creates a new "Chunk.Queue" object and one "Queue" object for each one. Instead, we can avoid those objects and use a Queue- builder.

Chunk - Optimise Flatten implementation.

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Stream.scala

Tested locally and it seems to be a workaround for https://github.com/lampepfl/dotty/issues/18487.

Localize `@nowarn212` to method parameters

---

protocols/shared/src/main/scala/fs2/protocols/mpeg/PesPacketHeader.scala

With the fix, when the DTS is absent and only the PTS is available, the decoding of PTS is now working. The starting bits are '0010', conveying the presence of PTS information.

Fix for decoding a PES packet with a header, when the DTS (Decoding Timestamp) is unavailable.

---

build.sbt
core/shared/src/main/scala/fs2/concurrent/Channel.scala
core/shared/src/test/scala/fs2/concurrent/ChannelSuite.scala

This PR adds the requested functionality: https://github.com/typelevel/fs2/issues/3279
- Add `closeWithElement` in `Channel`  
- Add test case

Add `Channel#closeWithElement`

---

io/js/src/main/scala/fs2/io/NodeStream.scala
io/js/src/main/scala/fs2/io/ioplatform.scala
io/js/src/test/scala/fs2/io/IoPlatformSuite.scala

A Node.js stream can be `destroy`ed with or without an error.
- https://nodejs.org/api/stream.html#writabledestroyerror
- https://nodejs.org/api/stream.html#readabledestroyerror
Previously when converting an `fs2.Stream` to a Node.js stream, destruction-with-no-error was handled by raising a special `StreamDestroyedException`. Instead, we should handle it as ordinary interruption via `interruptWhen`.
h/t @kubukoz for reporting

Implement Node.js stream `destroy` w/ `interruptWhen`

---

build.sbt
io/jvm/src/main/scala/fs2/io/ioplatform.scala
io/jvm/src/test/scala/fs2/io/IoPlatformSuite.scala
io/shared/src/main/scala/fs2/io/io.scala

Current implementation of `fs2.io.readInputStream` allocates new array of `chunkSize` size for every invocation of `InputStream#read(..)`. The problem is that `read` spec does not require `InputStream` implementations to write provided buffer fully or until stream exhaustion.
This leads to situation where if `readInputStream` chunk size is big (megabytes) and underlying input stream innner 'chunks' are small (bytes or kilobytes), returned `Stream[F, Byte]` are very 'sparse' where in every chunk only small amount of allocated capacity is actually used.
It could be shown easily by combining `fs2.io.toInputStream` with `fs2.io.readInputStream`.
This PR fixes this by reusing leftovers of allocated `Array[Byte]` for consequent 'InputStream' reads until either buffer is fully written or stream …

Fix 'fs.io.readInputStreamGeneric' overallocation of underlying buffers

---

core/shared/src/main/scala/fs2/Chunk.scala

This enables copy-free conversions in even more situations, which was my motivation for adding `toByteBufferUnsafe` in the first place.

Use `toByteBufferUnsafe` in `toArraySlice`

---

core/shared/src/main/scala/fs2/interop/flow/StreamPublisher.scala
core/shared/src/main/scala/fs2/interop/flow/StreamSubscriber.scala
core/shared/src/main/scala/fs2/interop/flow/StreamSubscription.scala
core/shared/src/main/scala/fs2/interop/flow/package.scala
core/shared/src/main/scala/fs2/interop/flow/syntax.scala

Related to https://github.com/raquo/Airstream/pull/114
c.c @armanbilge

Add flow.unsafeToPublisher

---

core/shared/src/main/scala/fs2/interop/flow/StreamSubscription.scala

It is unlikely anyone was affected by the bug, since they would have needed to have a `Stream` with more than `Long.MaxValue` elements for it to manifest.
Still, it is better to do the right thing.
c.c. @armanbilge

Fix subte bug in the interop.flow/StreamSubscription

---

io/js/src/main/scala/fs2/io/file/Path.scala
io/js/src/main/scala/fs2/io/internal/facade/path.scala
io/shared/src/test/scala/fs2/io/file/PathSuite.scala

Drop trailing separators in `Path` creation only if it is not the only thing in the path.
Fixes #3353

FIX: Handle root path correctly

---

core/shared/src/main/scala/fs2/interop/flow/StreamPublisher.scala
core/shared/src/main/scala/fs2/interop/flow/StreamSubscription.scala
core/shared/src/test/scala/fs2/interop/flow/CancellationSpec.scala

Fixes #3359 ?
c.c. @armanbilge as always I couldn't resit and made some renames along the way, sorry 😅

Call Subscriber.onSubscribe(StreamSubscription) before retruning from StreamPublisher.subscribe(Subscriber)

---

benchmark/src/main/scala/fs2/benchmark/ChunkBenchmark.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/test/scala/fs2/ChunkSuite.scala

`fs2.Chunk#collect` evaluates pattern matchers and guards of a passed partial function twice because it calls `pf.isDefinedAt` and then `pf.apply`:
```scala
// ...
foreach(o => if (pf.isDefinedAt(o)) b += pf(o))
// ...
```
Scala collections use `pf.applyOrElse`/`pf.runWith` (depending on scala version) instead to avoid double evaluation. This PR implements the same approach in a `Chunk`.
It should be noted that this may change observable behavior for those who use a partial function with side-effecting matchers/guards. But hey, side-effecting matchers/guards is considered a bad practice anyway, and I doubt that there's an fs2 user relying on that double evaluation "feature."

Avoid double evaluation of pattern matchers in Chunk.collect

---

io/js/src/main/scala/fs2/io/net/SocketPlatform.scala

This looks like a hold-over from the auto-generated facade days, which was unable to properly encode that the Node.js `Socket` implements the `Writable` interface.

Tidy unnecessary cast in JS `Socket`

---

build.sbt
io/native/src/main/scala/fs2/io/net/tls/TLSContextPlatform.scala
io/native/src/main/scala/fs2/io/net/tls/TLSParameters.scala
io/native/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala

This matches the default behavior on JVM and Node.js, which is that if the server requests client authentication then the client will cooperate. s2n defaults to `none` which causes mTLS to always fail.
Major props to @yurique for painstakingly tracking down this issue while working on https://github.com/joan38/kubernetes-client/pull/239.

Default `client_auth_type = optional` for TLS clients on Native

---

io/shared/src/main/scala/fs2/io/file/Files.scala
io/shared/src/test/scala/fs2/io/file/FilesSuite.scala

`writeUtf8Lines` uses a `flatMap` to intersperse a line separator and hence destroys chunking. `intersperse` improves the performance by preserving chunks.

Preserve chunking of input to `writeUtf8Lines` with `intersperse`.

---

io/js/src/main/scala/fs2/io/internal/facade/events.scala
io/js/src/main/scala/fs2/io/ioplatform.scala
io/js/src/main/scala/fs2/io/net/tls/TLSContextPlatform.scala

Fixes errors reported in https://github.com/typelevel/fs2/pull/3336 and https://github.com/typelevel/fs2/pull/3338.
By introducing some custom concurrent data structures, we can completely avoid `Dispatcher`, the indirection and performance cost, and the `dispatcher already shutdown` errors that have been plaguing us.

Don't use `Dispatcher` for `suspendReadableAndRead` and TLS initialization on Node.js

---

.scalafmt.conf
build.sbt
core/jvm/src/test/scala/fs2/interop/flow/SubscriberSpec.scala
core/shared/src/main/scala-2.13/fs2/ChunkPlatform.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/interop/flow/StreamPublisher.scala
core/shared/src/test/scala/fs2/ChunkSuite.scala
core/shared/src/test/scala/fs2/Logger.scala
core/shared/src/test/scala/fs2/interop/flow/SubscriberStabilitySpec.scala
io/jvm-native/src/main/scala/fs2/io/DeprecatedWatcher.scala
io/jvm-native/src/main/scala/fs2/io/file/DeprecatedFilesApi.scala
io/jvm-native/src/main/scala/fs2/io/file/PermissionsPlatform.scala
io/jvm-native/src/main/scala/fs2/io/file/Watcher.scala
io/jvm-native/src/main/scala/fs2/io/file/file.scala
io/jvm/src/main/scala/fs2/io/net/tls/TLSEngine.scala
io/jvm/src/test/scala/fs2/io/IoPlatformSuite.scala
protocols/shared/src/main/scala/fs2/protocols/mpeg/transport/Demultiplexer.scala
protocols/shared/src/main/scala/fs2/protocols/mpeg/transport/psi/TableBuilder.scala
reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamUnicastPublisher.scala
reactive-streams/src/test/scala/fs2/interop/reactivestreams/SubscriberSpec.scala
reactive-streams/src/test/scala/fs2/interop/reactivestreams/SubscriberStabilitySpec.scala
scodec/shared/src/test/scala/fs2/interop/scodec/MpegExample.scala

- Scala 3 report warnings since 3.4 https://github.com/lampepfl/dotty/pull/18813
- Scala 2.12 and 2.13 support new syntax without `-Xsource:3` option https://github.com/scala/scala/pull/10005

enforce new wildcard syntax

---

io/jvm-native/src/main/scala/fs2/io/net/SocketPlatform.scala

It's also helpful to run `sbt prePR`, which runs tests, generates docs, and performs various checks.

Use  nondirect buffer instead of direct buffer

---

io/js/src/main/scala/fs2/io/ioplatform.scala
io/js/src/test/scala/fs2/io/IoPlatformSuite.scala

Following in the steps of https://github.com/typelevel/fs2/pull/3348, this PR replaces the `Dispatcher`/`Queue`/`Channel` used for `Duplex` interop with a custom concurrent data structure. Besides the performance benefits of removing indirection, this enables a semantics fix/enhancement: the FS2 upstream will not start until the Node.js downstream signals readiness. AFAIK it's not possible to implement this semantic with a `Queue` since you cannot receive an (async) signal for readiness, only a signal when an enqueue completes.

Refactor Node.js `Duplex` interop

---

core/shared/src/main/scala/fs2/Stream.scala

Motivation:
I think we can use the `ev` directly , there is no need to create another closure.

chore: Use ev directly in flatten.

---

benchmark/src/main/scala/fs2/benchmark/ConcurrentBenchmark.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/CompilationTest.scala
core/shared/src/test/scala/fs2/ListParJoinSuite.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala
core/shared/src/test/scala/fs2/StreamParJoinSuite.scala
core/shared/src/test/scala/fs2/StreamSuite.scala

`List[Stream]#parJoinUnbounded` is `7x` faster compared to `Stream[Stream]#parJoinUnbounded`:
```
[info] Benchmark                                  Mode  Cnt    Score    Error  Units
[info] ConcurrentBenchmark.listParJoinUnbounded  thrpt    5  489.179 ± 35.120  ops/s
[info] ConcurrentBenchmark.parJoinUnbounded      thrpt    5   66.381 ±  4.879  ops/s
```
```scala
@Benchmark
def parJoinUnbounded(): Int = {
val each = Stream
.range(0, 1000)
.map(i => Stream.eval(IO.pure(i)))
each.parJoinUnbounded.compile.last.unsafeRunSync().get
}
@Benchmark
def listParJoinUnbounded(): Int = {
val each = List
.range(0, 1000)
.map(i => Stream.eval(IO.pure(i)))
each.parJoinUnbounded.compile.last.unsafeRunSync().get
}
```

Add `List[Stream]#parJoinUnbounded`.

---

CONTRIBUTING.md
io/shared/src/main/scala/fs2/io/process/Process.scala

I fell into this trap last week. Essentially, I was running a program that looks like this:
```scala
//> using scala "3.3.0"
//> using lib "co.fs2::fs2-io:3.9.3"
import cats.effect._
import fs2._
object Main extends IOApp.Simple {
val run = fs2.io.process
.ProcessBuilder(
"git",
"show",
"46d8140:lightweight-dynamo.json" // just a large file that exists in the git repo
)
.spawn[IO]
.use { p =>
p.exitValue *> p.stdout.through(fs2.text.utf8.decode).compile.string
}
.flatMap(IO.println)
}
```
Unfortunately for me, when the file in question (`lightweight-dynamo.json` in this instance) was somewhat large, my program would hang. I tracked this down to: you must drain stdout if the process you starts is writing to it. Failure to do it can cause the process to block because it's write buffer is …

Update scaladoc for Process

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSuite.scala

The current `ensure` on `MonadError` is based on `flatMap`, so doesn't preserve chunks.
This PR:
- Implements a chunk-preserving `ensure` function.
- Overrides some default implementations on `MonadError` with counterparts defined on `Stream`.

Add chunk-preserving ensure function.

---

reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamSubscription.scala

fix for https://github.com/typelevel/fs2/issues/3384

Do not let handled errors get printed to the console

---

core/shared/src/main/scala/fs2/Stream.scala

When passing large chunk sizes to `Stream.fromBlockingIterator`, CPU is wasted calling `hasNext` on an empty iterable -- `chunkSize - i.size` times.
Noticed this when passing `Int.MaxValue` for chunk size and an operation took over 3 minutes longer than it should have.

Fix performance of Stream.from(Blocking)Iterator when using large chunk sizes

---

io/jvm-native/src/main/scala/fs2/io/file/FilesPlatform.scala
io/native/src/main/scala/fs2/io/file/AsyncFilesPlatform.scala
io/shared/src/main/scala/fs2/io/file/Files.scala
io/shared/src/main/scala/fs2/io/file/PathInfo.scala

This provides better performance than `Files[F].walk(path).evalMap(p => p -> Files[F].getBasicFileAttributes(p))` given that all implementations of `walk` use file attributes.
Some use cases:
Computing cumulative size of a tree:
```scala
Files[F].walkWithAttributes(path).map(_.attributes.size).compile.foldMonoid
```
Getting all directories in a tree:
```scala
Files[F].walkWithAttributes(path).filter(_.attributes.isDirectory)
```

Add `Files.walkWithAttributes`

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamConflateSuite.scala

Similar to `conflate`/`conflateWithSeed` from akka-streams.
This PR adds:
- `conflateChunks`
- `conflate`
- `conflate1`
- `conflateSemigroup`
- `conflateMap`
Recommended by @seigert on r/scala here: https://www.reddit.com/r/scala/comments/1ayqcx0/comment/krx6nr6/

Add conflate operations to Stream

---

io/shared/src/main/scala/fs2/io/file/Files.scala

Fix ignored parameters in deprecated Files.walk()

---

.github/workflows/ci.yml
build.sbt

Latest MacOS images no longer include SBT. See https://github.com/actions/setup-java/issues/627
h/t @BalmungSan

Fix macos gha runners

---

io/src/main/scala/fs2/io/udp/AsynchronousSocketGroup.scala

Current `Ordering.by[Timeout, Long](_.expiry)` in `AsynchronousSocketGroup` is built the way so `pendingTimeouts: PriorityQueue[Timeout]` returns not the closest timeout that can be expired, but the furthest one during `.headOption` calls in `selectorThread`. Which, when read/write is called frequently, causes the `selectorThread` at each iteration to check for a timeout that was just added and does not need to be removed from the queue, causing a memory leak due to the infinite growth of `pendingTimeouts`.
I have checked locally that when using `reverse`, `pendingTimeouts.headOption` returns a timeout with the closest `expiry` time. 
Unfortunately, I couldn't figure out a test for it

Fix Ordering of UDP pending timeouts

---

site/guide.md

The output on [the Guide/Concurrency page](https://fs2.io/#/guide?id=concurrency) currently shows
```
Stream(1,2,3).merge(Stream.eval(IO { Thread.sleep(200); 4 })).compile.toVector.unsafeRunSync()
// error: Could not find an implicit IORuntime.
// 
// Instead of calling unsafe methods directly, consider using cats.effect.IOApp, which
// runs your IO. If integrating with non-functional code or experimenting in a REPL / Worksheet,
// add the following import:
```
and the text `Oops, we need a cats.effect.ContextShift[IO] in implicit scope.`.
The text was [last updated August 2018](https://github.com/typelevel/fs2/commit/e05a62fab9beb1a417ae80de87ab88eeaa112f95#diff-bc466a168b95b1a628addcbeceb5d0208b95b605692e475b93c143d7658aa904R374), before cats-effect 3, which [changed …

Update Guide snippet error

---

core/shared/src/main/scala/fs2/Stream.scala

This removes the need to call `.unchunks` if outputting chunks, and also adds symmetry to `unfoldEval` and its chunk variant `unfoldChunkEval`.

Add `unfoldChunkLoop` and `unfoldChunkLoopEval`, more (downstream) efficient versions of `unfoldLoop` and `unfoldLoopEval`.

---

core/shared/src/main/scala/fs2/internal/Scope.scala
core/shared/src/test/scala/fs2/BracketSuite.scala

I minimized a bug I had to this.
```scala
IO.ref(0).flatMap { ref =>
val res = Stream.resource(Resource.make(ref.update(_ + 1))(_ => ref.update(_ - 1)))
(0 to 100000).toList.parTraverse_ { _ =>
val fa = res.evalMap(_ => IO.sleep(10.millis)).take(10).compile.drain
IO.race(fa, IO.sleep(90.millis))
} >> ref.get.map(assertEquals(_, 0))
}
```
The `Ref` will sometimes not contain 0. I tried the same test with the following fix and it does not occur anymore.
If cancellation of the stream occurs between `state.modify` and the subsequent `flatMap` then the scope's state is `Closed`, thus when the root scope is cancelled and traverses the scope tree, the node is now `Closed`, but the finalizers for the attached resources were never run.
I can't seem to come up with a good test for this.

Fix resource leak in `Scope`.

---

core/shared/src/main/scala/fs2/Stream.scala

See this scastie for reference: https://scastie.scala-lang.org/KKWe9upeRR6im3yZDfpDaQ

Fix typo in `exists` scaladoc

---

core/shared/src/main/scala/fs2/text.scala

The main idea is to avoid copying single characters, and instead copy string slices, that can use avx2 instructions.
The copy is still unavoidable unfortunately in JVM - AFAIK.
benchmarks running locally `-wi 3 -i 3 -f 1 -t 1`
Before:
```
LinesBenchmark.linesBenchmark                0            4  thrpt    3  122139.570 ± 236181.395  ops/s
LinesBenchmark.linesBenchmark                0           16  thrpt    3  134204.974 ±  76569.841  ops/s
LinesBenchmark.linesBenchmark                0           64  thrpt    3  133776.725 ± 137902.948  ops/s
LinesBenchmark.linesBenchmark                1            4  thrpt    3   44078.282 ±  46048.728  ops/s
LinesBenchmark.linesBenchmark                1           16  thrpt    3   95173.337 ±  31919.684  ops/s
LinesBenchmark.linesBenchmark …
```

Optimise text.lines for longer lines, larger chunks use-cases

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSuite.scala

While putting together a couple of simple Stream example, I was surprised that `repeatN(0)` fails with an error instead of completing with an empty Stream. I would have expected it to work as `repeat.take(0)` would do.
I'm opening this PR to get some feedback about this proposal. I'm happy to discuss possible consequences of this change.
Apart from avoiding surprises or confusion on the user side, I don't have any real use cases in mind where this would be necessary to have

Change repeatN to support n=0

---

io/shared/src/main/scala/fs2/io/file/Files.scala
io/shared/src/test/scala/fs2/io/file/FilesSuite.scala

Fixes #3488.
There was a problem with `writeUtf8Lines` executing `in.pull.uncons` and evaluating leading effects, but discarding the result and using `in`.
(Sorry if it is difficult to read due to the use of translation software.)

Fix `writeUtf8Lines` evaluates leading effects in the input stream twice

---

benchmark/src/main/scala/fs2/benchmark/FlowInteropBenchmark.scala
build.sbt
core/shared/src/main/scala/fs2/interop/flow/StreamSubscriber.scala
core/shared/src/main/scala/fs2/interop/flow/StreamSubscription.scala

Since the `reactive-streams` spec mentions that all calls must be done _"serially"_ these changes optimize the tight loop of multiple consequential `onNext` calls.
-----
| Benchmark | (fibers) | (iterations) | Mode | Cnt | Score | Error | Units |
| - | - | - | - | - | - | - | - |
| FlowInteropBenchmark.fastPublisher | 1000 |   1024 | thrpt | 20 | 25.938 | ± 0.306 | ops/s |
| FlowInteropBenchmark.fastPublisher | 1000 |   5120 | thrpt | 20 |  6.519 | ± 0.015 | ops/s |
| FlowInteropBenchmark.fastPublisher | 1000 |  10240 | thrpt | 20 |  3.201 | ± 0.168 | ops/s |
| FlowInteropBenchmark.fastPublisher | 1000 |  51200 | thrpt | 20 |  0.680 | ± 0.013 | ops/s |
| FlowInteropBenchmark.fastPublisher | 1000 | 512000 | thrpt | 20 |  0.062 | ± 0.001 | ops/s |
| Benchmark | (fibers) | (iterations) | …

Optmize `interop.flow.StreamSubscriber.onNext`

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala

It's also helpful to run `sbt prePR`, which runs tests, generates docs, and performs various checks.

Add evalFold combinator to Stream

---

reactive-streams/src/main/scala/fs2/interop/reactivestreams/package.scala

Add the note about chunks not being emitted until N elements are gathered when buffering.

Improve documentation

---

.github/workflows/ci.yml
build.sbt
io/jvm-native/src/main/scala/fs2/io/process/ProcessesPlatform.scala
io/jvm/src/main/scala/fs2/io/ioplatform.scala
io/native/src/main/scala/fs2/io/ioplatform.scala

Run `Process.waitFor` in virtual thread if possible to solve https://github.com/typelevel/fs2/issues/3182 
I am not sure if this is the correct approach but I wanted to share my progress to get fast feedback.

run `Process#waitFor` on virtual thread if available

---

flake.nix

Fix `flake.nix`. It wasn't working before.
After changes, I can open a nix shell as expected.

fix `flake.nix`

---

core/shared/src/main/scala/fs2/interop/flow/StreamSubscriber.scala

I think this fixes the flaky **flow** interop tests: #3541 #3542 
Related to #3449 
I think the main change is ensuring we reset the `StreamSubscriber` state BEFORE completing the callback with the `Chunk`.
But, I also made sure we reset the state in any place where we complete a callback, even with exceptions, just in case.
c.c. @armanbilge

Be more deffensive with the `StreamSubscriber` internal state

---

io/jvm-native/src/main/scala/fs2/io/file/FileHandlePlatform.scala
io/jvm-native/src/main/scala/fs2/io/net/SocketPlatform.scala
io/jvm/src/main/scala/fs2/io/net/SelectingSocket.scala
io/jvm/src/main/scala/fs2/io/net/unixsocket/UnixSocketsPlatform.scala
io/shared/src/main/scala/fs2/io/net/Socket.scala
io/shared/src/test/scala/fs2/io/net/tcp/SocketSuite.scala

Added efficient transfer of a file to the network for jvm platform using `transferTo` and `transferFrom` methods of filechannel.
part of #3171

Implement `Socket#sendFile`

---

site/ecosystem.md

Hi!
We have created a database client library with Scala's own connector to connect to MySQL.
https://github.com/takapi327/ldbc
Connectors are created using fs2.
It would be awesome to have it mentioned on the fs2 ecosystem page 🙂

Add ldbc to the ecosystem

---

core/shared/src/main/scala/fs2/Stream.scala

Just clarifying in the docs that using `chunkN` with `allowFewer=true` will only emit the smaller chunk when it is the last chunk in the stream *and* the stream is completed (`chunkN` builds on `unconsMin` which only returns a partial chunk once it hits the end of the stream)

clarify chunkN doc about allowFewer

---

io/jvm/src/main/scala/fs2/io/net/SelectingSocketGroup.scala
io/shared/src/test/scala/fs2/io/net/tcp/SocketSuite.scala

This backports https://github.com/typelevel/fs2/pull/3591 to the series/release/3.12 branch
It does not include subsequent updates made to fix deprecation warnings, but I am happy to port those too, although maybe those warnings only become warnings with other changes made later (I don't see them in my IDE and didn't notice them in the output from scalac either).

Backport 3591

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamMergeSuite.scala
core/shared/src/test/scala/fs2/TimedPullsSuite.scala

Stream merge does not block until scope is closed, but only until the chunk is read from the output channel.
Merge was waiting for the resulting chunk to be fully processed, this introduced a scope (resource) to the stream, which then if leased for further parallel processing would cause the merge to be waiting forever (until the parallel processing finished).
Here I am changing that we are only guarding the production of values from merge. Instead of guarding the whole processing of the chunk, we are only guarding the chunk up to the point where it is read from the output of the merge. 
This also fixes #3598. 
This is now aligned with documentation of merge where `Stream(this, that).parJoinUnbounded` == `this merge that`

Stream merge blocking downstream work.
