src/main/scala/scalaz/stream/ProcessInstances.scala
src/test/scala/scalaz/stream/Process1Spec.scala
src/test/scala/scalaz/stream/ProcessInstancesSpec.scala
src/test/scala/scalaz/stream/TestInstances.scala

This one adds `Choice[Process1]` and `Profunctor[Process1]` instances.

Add more Process instances

---

src/main/scala/scalaz/stream/io.scala
src/test/scala/scalaz/stream/ToInputStreamSpec.scala

Also, subsequent reads after close() is called will return -1

Fixes NPE in io.InputStream when the wrapped process throws an Exception

---

CONTRIBUTORS.md

Thanks @pchiusano for adding this file! I'll make a start and add my own contributions.

Update and rename CONTRIBUTORS.markdown to CONTRIBUTORS.md

---

CONTRIBUTORS.md

More contributors changes

---

src/main/scala/scalaz/stream/Process.scala
src/main/scala/scalaz/stream/async/package.scala
src/main/scala/scalaz/stream/channel.scala
src/main/scala/scalaz/stream/io.scala
src/main/scala/scalaz/stream/sink.scala
src/main/scala/scalaz/stream/writer.scala
src/test/scala/scalaz/stream/ProcessSpec.scala
src/test/scala/scalaz/stream/UnsafeChunkRSpec.scala

Refactors modules per discussion in #337 .

Refactor modules

---

src/main/scala/scalaz/stream/io.scala

Fix io.bufferedResource and io.resource to use await instead of flatMap

---

src/test/scala/scalaz/stream/examples/CreatingStreams.scala

Remove last reference to TransformingStreams.scala

---

src/main/scala/scalaz/stream/async/mutable/Queue.scala
src/main/scala/scalaz/stream/async/package.scala

This commit adds a circular buffer by slightly modifying the implementation of `async.Queue`.

Circular buffers

---

src/test/scala/scalaz/stream/AsyncSignalSpec.scala
src/test/scala/scalaz/stream/AsyncTopicSpec.scala
src/test/scala/scalaz/stream/CauseSpec.scala
src/test/scala/scalaz/stream/CompressSpec.scala
src/test/scala/scalaz/stream/ExchangeSpec.scala
src/test/scala/scalaz/stream/HashSpec.scala
src/test/scala/scalaz/stream/LinesSpec.scala
src/test/scala/scalaz/stream/MergeNSpec.scala
src/test/scala/scalaz/stream/NioFilesSpec.scala
src/test/scala/scalaz/stream/NioSpec.scala
src/test/scala/scalaz/stream/PrintSpec.scala
src/test/scala/scalaz/stream/Process1Spec.scala
src/test/scala/scalaz/stream/ProcessInstancesSpec.scala
src/test/scala/scalaz/stream/ProcessPerformanceSpec.scala
src/test/scala/scalaz/stream/ProcessSpec.scala
src/test/scala/scalaz/stream/QueueSpec.scala
src/test/scala/scalaz/stream/ResourceSafetySpec.scala
src/test/scala/scalaz/stream/TcpSpec.scala
src/test/scala/scalaz/stream/TeeSpec.scala
src/test/scala/scalaz/stream/TimeSpec.scala
src/test/scala/scalaz/stream/ToInputStreamSpec.scala
src/test/scala/scalaz/stream/UdpSpec.scala
src/test/scala/scalaz/stream/UnsafeChunkRSpec.scala
src/test/scala/scalaz/stream/Utf8DecodeSpec.scala
src/test/scala/scalaz/stream/WyeSpec.scala

object -> class in tests to prevent object init deadlocks

---

src/main/scala/scalaz/stream/nondeterminism/nondeterminism.scala
src/test/scala/scalaz/stream/MergeNSpec.scala

Credit to @edwinchoi for the diagnosis and the fix.  I just ported his code from `wye.apply` to `njoin`.

Corrected njoin to be resilient to multiple finalizer invocations

---

.travis.yml

Don't merge this yet.  I want to make sure it actually works…

Attempting to fix Travis's jgit woes

---

project/build.properties

realised I updated sbt on master-a PR should do so here too

update sbt version to 0.13.8

---

project/plugins.sbt

Updated to a newer version of sbt-git to (hopefully) address build issues

---

src/main/scala/scalaz/stream/Process.scala
src/test/scala/scalaz/stream/examples/CreatingStreams.scala

change Process#runLog to return s.c.i.Vector

---

src/main/scala/scalaz/stream/Process.scala

Through the strong power of typeclass incoherence!  Surprise, guys, but there's plenty of `Monoid`s in the sea…

Revised runLast to no longer consume linear memory

---

src/main/scala/scalaz/stream/Process.scala
src/main/scala/scalaz/stream/io.scala
src/test/scala/scalaz/stream/ProcessPerformanceSpec.scala
src/test/scala/scalaz/stream/ProcessSpec.scala

Bracket introduction

---

src/main/scala/fs2/Chunk.scala
src/main/scala/fs2/Process1.scala
src/main/scala/fs2/Process1Ops.scala
src/test/scala/fs2/Process1Spec.scala

This implements filtering by a predicate on data streams in FS2. It tries to retain chunkiness, and limits (somewhat) new object creation.
This is also a learning exercise (for me) on where/what should go in various places in the new design.
e.g. should this be available for pull instead? (I don't think so). Is it over the top in checking various Chunk sizes?

Implement process1.filter and syntax sugar.

---

src/main/scala/fs2/Chunk.scala

FS2: Add indexWhere to Chunk

---

src/main/scala/fs2/Chunk.scala

Operations on a IndexedSeq-Chunk should not upcast to Seq-Chunk.

Use indexedSeq instead of seq

---

src/main/scala/fs2/Chunk.scala
src/main/scala/fs2/Process1.scala
src/main/scala/fs2/Process1Ops.scala
src/test/scala/fs2/Process1Spec.scala

I took the liberty of adding `zipWithIndex` method to `Chunk` as well. If you feel there is better place to hold it, leave me a message. Thanks!

add `zipWithIndex` to `Process1`

---

src/main/scala/fs2/Process1.scala
src/main/scala/fs2/Process1Ops.scala

and also add their alias to `Process1Ops`

use `Pull.receive` to refactor some `process1` methods

---

src/main/scala/fs2/Process1.scala
src/main/scala/fs2/Process1Ops.scala
src/main/scala/fs2/pull1.scala
src/test/scala/fs2/Process1Spec.scala

This writes the output of the first input matching a predicate, to the output of the supplied Pull, then halts.

FS2: Implement process1.find

---

src/main/scala/fs2/Process1.scala
src/main/scala/fs2/Process1Ops.scala
src/test/scala/fs2/Process1Spec.scala

Implements process1.sum, which writes the sum of all input numeric values, or numeric (monoidal) zero if no input values are supplied.

FS2: Add process1.sum

---

src/main/scala/fs2/Process1.scala
src/main/scala/fs2/Process1Ops.scala
src/test/scala/fs2/Process1Spec.scala

Using Pull.find seemed like the most intuitive way to model collectFirst. Let me know if there is a better way.

adding collectFirst to Process1

---

src/main/scala/scalaz/stream/io.scala
src/test/scala/scalaz/stream/UnsafeChunkRSpec.scala

First PR here; a little scary.  Let me know what I screwed up :-)

read multiple times as needed in io.unsafeChunkR (fixes #498)

---

core/src/main/scala/fs2/async/AsyncExt.scala
core/src/main/scala/fs2/async/async.scala
core/src/main/scala/fs2/util/Task.scala
core/src/test/scala/fs2/async/QueueSpec.scala

Also some documentation and other cleanup.
@pchlupacek can you take a look at my test and see if you spot anything silly?

Added a simple queue test, which currently hangs

---

core/src/main/scala/fs2/util/Task.scala

This PR adds more convenience functions to `Task` to simplify integration at program boundaries.

Added convenience functions to Task for running a task fully asynchronously

---

core/src/main/scala/fs2/Async.scala

Usage is pretty much identical to what you are used to, but now it works for any `Async`:
```Scala
scala>   implicit val S = Strategy.fromExecutionContext(scala.concurrent.ExecutionContext.global)
S: fs2.Strategy = fs2.Strategy$$anon$1@467d308b
scala> val T = implicitly[Async[Task]]
T: fs2.Async[fs2.util.Task] = fs2.util.Instances$$anon$1@28345a08
// notice this is not calling `Task.async`, but the one we get for free for any `Async[F]`
scala> T.async[Int] { cb => Thread.sleep(1000); cb(Right(42)) }
res0: fs2.util.Task[Int] = fs2.util.Task@16948379
scala> res0.run
// after 1 second pause
res1: Int = 42
```
The signature is just slightly different from the existing `Task.async`, but it is used in the same way. You can see the implementation is pretty simple. It just creates a `Ref`, …

Implementation of  `async` for any `Async[F]`

---

core/src/test/scala/fs2/time/TimeSpec.scala

This test works after the landing of Semaphore & new Signal code.

Uncomment test which works after new Signal implementation.

---

.travis.yml
build.sbt

fix https://github.com/functional-streams-for-scala/fs2/issues/575

Scala 2.12.0-M4

---

docs/CreatingStreams.md
docs/guide.md
docs/src/CreatingStreams.md

Introduces the basics of Stream creation. Please give this a read and make sure I'm telling the truth everywhere 😄

Port over scalaz-streams creation guide.

---

core/src/test/scala/fs2/async/SignalSpec.scala

I was a little suspicious of Signal.discrete and wrote an additional test. This verifies that the last value is received by `discrete`, in the case where the producer makes a series of rapid updates and the consumer of discrete is consuming these updates more slowly. The consumer can miss some updates, but it should always receive the final update.
Looking more carefully at the implementation, I'm pretty confident in it's correctness, too. The implementation is kind of subtle though.

Added additional test of Signal.discrete

---

core/src/test/scala/fs2/ResourceSafetySpec.scala

This test exposes a bug where finalizers aren't always run. I believe that once this is fixed, then the new join implementation of #595 will be working completely.

Added test which shows finalizers not getting run

---

core/src/main/scala/fs2/internal/Resources.scala

The callbacks list is now checked to be the same length as the number of resources still being acquired. I don't think we were hitting this case but just wanted to rule it out.

Eliminating possibility of use of `zip` dropping finalizers

---

core/src/main/scala/fs2/StreamPipeOps.scala
core/src/main/scala/fs2/pipe.scala
core/src/test/scala/fs2/PipeSpec.scala

These are the last of the outstanding pipes. :tada:

Added dropLast, dropLastIf, and split pipes

---

docs/migration-guide.md

I added everything I could think of. Let's add to this as we think of things.

Migration guide

---

core/src/main/scala/fs2/StreamDerived.scala
core/src/main/scala/fs2/StreamOps.scala
core/src/main/scala/fs2/pipe.scala
core/src/main/scala/fs2/pipe2.scala
core/src/main/scala/fs2/util/Lub1.scala
core/src/test/scala/fs2/CompilationTest.scala
core/src/test/scala/fs2/CompressSpec.scala
core/src/test/scala/fs2/MemorySanityChecks.scala
core/src/test/scala/fs2/Pipe2Spec.scala
core/src/test/scala/fs2/PipeSpec.scala
core/src/test/scala/fs2/TextSpec.scala
docs/guide.md
docs/src/guide.md

Fixes #624. What do you think of this general approach? What other methods should get the `Lub1` treatment?

Introduced Lub1 witness and modified ++/append/evalMap/flatMap/onError/onComplete to use it in order to get better inference

---

core/src/main/scala/fs2/hash/hash.scala
core/src/test/scala/fs2/hash/HashSpec.scala

Ported the hash package from 0.8

---

build.sbt

Guess branch/tag based on version.
Currently it is hardcoded pointing to `master` which was deleted a while ago. Also I think it's better to point to the tag for released versions.

Fix broken link-to-source in scaladocs

---

core/src/main/scala/fs2/fs2.scala
core/src/main/scala/fs2/time/time.scala

fix comment

---

core/src/main/scala/fs2/async/channel.scala
core/src/test/scala/fs2/async/ChannelSpec.scala

Fixed bug in channel.observe(Async) where stream hangs if observing sink fails

---

io/src/main/scala/fs2/io/tcp/Socket.scala
io/src/main/scala/fs2/io/udp/AsynchronousSocketGroup.scala
io/src/main/scala/fs2/io/udp/Socket.scala
io/src/test/scala/fs2/io/udp/UdpSpec.scala

This makes the API consistent with TCP.

Added timeout support to udp read/write

---

core/src/main/scala/fs2/StreamCore.scala
core/src/test/scala/fs2/ResourceSafetySpec.scala

Delayed invocation of cleanup action until it is time to execute cleanup

---

.travis.yml
benchmark-macros/src/main/scala/fs2/macros.scala
benchmark/src/main/scala/fs2/benchmark/ConcurrentBenchmark.scala
benchmark/src/main/scala/fs2/benchmark/StreamBenchmark.scala
benchmark/src/main/scala/fs2/benchmark/TaskBenchmark.scala
benchmark/src/main/scala/fs2/benchmark/utils.scala
build.sbt
core/src/main/scala/fs2/StreamDerived.scala
project/plugins.sbt

Since we've decided to start using `fs2` I thought we could take a look at #399.
This is really a very, very initial commit to show that it's running on travis and generate some discussion as to what should be benchmarked.
It would also be cool to have some updated benchmarks on github using a webhook or some such.

Jmh benchmark

---

.gitignore
core/src/main/scala/fs2/text.scala
core/src/test/scala/fs2/TextSpec.scala

Fixes #660 /cc @martijnhoekstra

Fixed bug in text.lines that did not handle a CRLF that spanned chunks

---

core/src/main/scala/fs2/async/channel.scala
core/src/test/scala/fs2/ResourceSafetySpec.scala
core/src/test/scala/fs2/TestUtil.scala
core/src/test/scala/fs2/async/ChannelSpec.scala

...where finalizer which enqueued none to observation stream could be delayed in execution by something downstream.

Fixed hang in channel.diamond

---

core/src/main/scala/fs2/Scheduler.scala
core/src/main/scala/fs2/time/time.scala
io/src/main/scala/fs2/io/file/file.scala
io/src/main/scala/fs2/io/tcp/Socket.scala
io/src/main/scala/fs2/io/udp/Socket.scala

@pchlupacek Let me know if this addresses all of your comments on Async PR.

Changed various callback invocations to async start effect before running

---

io/src/main/scala/fs2/io/file/file.scala

Adds support for reading/writing InputStream and OutputStream values.
Also adds stdin/stdout helpers.
Closes #656

Add read/write support for {Input|Output}Stream, and stdin/stdout.

---

io/src/main/scala/fs2/io/file/file.scala

Handle the unusual edge case of encountering end-of-InputStream. :no_mouth:

io.file.readInputStream: Handle end of InputStream

---

core/jvm/src/main/scala/fs2/compress.scala
core/shared/src/main/scala/fs2/Handle.scala
core/shared/src/main/scala/fs2/async/mutable/Semaphore.scala
core/shared/src/main/scala/fs2/pipe.scala
core/shared/src/main/scala/fs2/pipe2.scala
core/shared/src/main/scala/fs2/util/Catenable.scala
docs/implementation-notes.markdown

This is consistent with stdlib, Cats, and Scalaz.

Rename nonempty to nonEmpty

---

core/shared/src/main/scala/fs2/internal/LinkedMap.scala

Removed unused method from LinkedMap

---

core/jvm/src/test/scala/fs2/async/QueueSpec.scala
core/shared/src/main/scala/fs2/async/async.scala
core/shared/src/main/scala/fs2/async/mutable/Queue.scala

Added fs2.async.circularBuffer

---

src/main/scala/scalaz/stream/nio/file.scala
src/test/scala/scalaz/stream/NioFilesSpec.scala

The `completionHandler` helper referred to the call-by-name src instead
of the acquired resource, resulting in a leak on buffer underfill.
Fixes http4s/http4s#673.

Fix chunkReadBuffer reopening channel on underfill

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/StreamCore.scala

This fixes #735. Review by @mpilquist. Thanks to @fiadliel for spotting.

fix for #735 along with tests

---

core/shared/src/main/scala/fs2/Task.scala

- Add combinator that allows you to fold up an `Attempt`.

Add the attemptFold combinator.

---

README.md

Covers the features of the latest 0.5 release

Update description of the streamz project

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/pipe2.scala

@mpilquist small addition to docs

Add to docs

---

core/jvm/src/test/scala/fs2/PipeSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/pipe.scala

I found a groupBy missing, so I made one.

groupBy convenience function

---

.travis.yml
build.sbt
project/plugins.sbt

Specifically, [Coursier](http://get-coursier.io) and [sbt-travisci](https://github.com/dwijnand/sbt-travisci).  Also I fixed the `.travis.yml` formatting, which was incorrect.

Random build improvements

---

core/jvm/src/test/scala/fs2/time/TimeSpec.scala
core/shared/src/main/scala/fs2/time/time.scala

Also fixes the tests for `time.duration` (which weren't really testing anything) and added tests for `time.sleep` (which didn't exist).
More controversially (I expect), this sneaks in a fundamental change to the `time.sleep` API.  Right now, and as long as I've been using scalaz-stream, `time.sleep` has had type `Stream[F, Nothing]`.  This is *almost* never what you want, and this gave rise to a common gotcha where beginners and experts alike would `flatMap` over `time.sleep`.  This in turn gave rise to a common (and annoying) pattern where you would have to remember to do `time.sleep(d) ++ emit(())` basically everywhere.
This changes `time.sleep` to emit `()` when it completes and adds a `sleep_` which has the old behavior.  I considered just adding a `sleepU` for preserving backwards …

Cheaper time.sleep

---

.travis.yml
README.md
benchmark/src/main/scala/fs2/benchmark/CatenableBenchmark.scala
benchmark/src/main/scala/fs2/benchmark/FreeBenchmark.scala
build.sbt
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/jvm/src/test/scala/fs2/TaskSpec.scala
core/jvm/src/test/scala/fs2/time/TimeSpec.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/StreamCore.scala
core/shared/src/main/scala/fs2/Task.scala
core/shared/src/main/scala/fs2/async/async.scala
core/shared/src/main/scala/fs2/async/mutable/Signal.scala
core/shared/src/main/scala/fs2/internal/LinkedMap.scala
core/shared/src/main/scala/fs2/internal/Resources.scala
core/shared/src/main/scala/fs2/time/time.scala
core/shared/src/main/scala/fs2/util/Catenable.scala
core/shared/src/main/scala/fs2/util/Free.scala
core/shared/src/test/scala/fs2/TextSpec.scala
docs/guide.md
docs/src/guide.md
io/src/main/scala/fs2/io/udp/Socket.scala
project/build.properties
project/plugins.sbt
sbt

Will merge this after Travis build.

Backport binary compatible fixes to 0.9

---

core/shared/src/main/scala/fs2/pipe.scala

Implementation of pipe.groupBy emits one element to the output stream per K on the input stream. If each chunk of the input stream contains more than one K, this can reduce chunkiness of the output. This alternate implementation can emit more than one K per chunk on the output stream, giving significantly better performance for my use case, at the cost of some additional complexity.
Unless I've missed something.

Preserve chunkiness in pipe.groupBy

---

CHANGELOG.md
core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/shared/src/main/scala/fs2/StreamCore.scala

Fixes #812. Review by @pchiusano. I'll merge to 1.0 after review.

Fixed memory leak in Stream#runFoldScope

---

README.md

I was just reading the README and saw this.

Removed a small typo

---

build.sbt

Not sure if necessary however I wanted to put in the PR since I saw this was running around. Referring to typelevel/scala#135
Not entirely sure if necessary but was easy enough to put out there if it is appropriate.

Updated for CrossVersion patch and scalaOrganization

---

build.sbt
core/jvm/src/test/scala/fs2/Pipe2Spec.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Handle.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/pipe2.scala

Added pipe2.pause and Stream#pause

---

core/shared/src/main/scala/fs2/Stream.scala

moving unNone under StreamOptionOps

---

README.md

In the current branch series/0.10 the fahrenheitToCelsius example is outdated. See if you're okay with the changes or have something different in mind.

Updating example in the README file

---

core/shared/src/main/scala/fs2/async/Ref.scala

h/t to @djspiewak for noticing and suggesting fix

Fixed bug in Ref#setSync where it was setting async 

---

core/jvm/src/test/scala/fs2/ResourceSafetySpec.scala
core/shared/src/main/scala/fs2/internal/Resources.scala

Now it actually returns newest tokens first.
Fixes #902

Fixed a bug in Resources#newSince

---

core/jvm/src/test/scala/fs2/SchedulerSpec.scala
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/jvm/src/test/scala/fs2/async/QueueSpec.scala
core/jvm/src/test/scala/fs2/async/SemaphoreSpec.scala
core/shared/src/main/scala/fs2/Scheduler.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/async/Ref.scala
core/shared/src/main/scala/fs2/async/mutable/Queue.scala
core/shared/src/main/scala/fs2/async/mutable/Semaphore.scala
core/shared/src/test/scala/fs2/async/RefSpec.scala
docs/migration-guide-0.10.md

Scheduler API cleanup and timeout support for various operations in async package

---

core/shared/src/main/scala/fs2/Segment.scala
core/shared/src/test/scala/fs2/SegmentSpec.scala

It allows to continue `Segment` based on the result.

Add Segment.flatMapResult

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Pipe.scala
core/shared/src/main/scala/fs2/Pipe2.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

Fixes #941 -- issue related to interleaving scopes from 2 or more streams.
Review by @pchiusano please

Fixed #941 - interleaved scopes when combining 2 or more streams

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

We added the Suspend node back when we were trying to implement viewL
caching in FreeC. If viewL caches, then a Free.suspend(f) may be
evaluated and cached. However, suspend on Stream/Pull/Algebra relies on
always-evaluate semantics.
Now that we don't cache in FreeC, there's no reason for the Stream
algebra to have its own Suspend constructor.

Removed the Suspend node from the Stream algebra

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

Added a few options for manually managing scopes

---

core/shared/src/main/scala/fs2/Scheduler.scala
core/shared/src/main/scala/fs2/Segment.scala
core/shared/src/test/scala/fs2/SegmentSpec.scala

Also changed the signature such that the `init` elements aren't drained.

Added tests and fixed 2 bugs in Segment#last

---

core/shared/src/main/scala/fs2/async/Change.scala
core/shared/src/main/scala/fs2/async/Ref.scala
core/shared/src/main/scala/fs2/async/RefOps.scala
core/shared/src/main/scala/fs2/async/SyncRef.scala
core/shared/src/main/scala/fs2/async/async.scala
core/shared/src/main/scala/fs2/async/mutable/Signal.scala
core/shared/src/main/scala/fs2/internal/Actor.scala
io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/test/scala/fs2/io/JavaInputOutputStreamSpec.scala

...a lightweight alternative to Ref backed by an AtomicReference.

Added fs2.async.SyncRef

---

core/jvm/src/main/scala/fs2/compress.scala

I believe this fixes #998 but I haven't tried it. If it's not too much trouble, would you mind giving it a shot @lukestephenson and letting us know if it fixes the leak you saw?

Fixed memory leaks in compress.inflate/delate

---

core/jvm/src/test/scala/fs2/PipeSpec.scala
core/shared/src/main/scala/fs2/Stream.scala

Renamed groupBy to groupAdjacentBy and changed its return type to provide a Segment instead of a Vector

---

build.sbt
core/shared/src/main/scala/fs2/async/async.scala
project/plugins.sbt

And transitively cats-1.0.0-RC2.

Upgrade to cats-effect-0.6

---

README.md

Links to Scaladoc for 0.10.0 milestones 8 and 10 placed in "latest version" section of README

0.10 docs link

---

build.sbt
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/test/scala/fs2/ChunkSpec.scala
core/shared/src/test/scala/fs2/Fs2Spec.scala
core/shared/src/test/scala/fs2/TestUtil.scala

Fixes map on the array specializations of chunk.
Introduces cats-laws to test for lawful instances.

Fix map on chunk specializations, test laws

---

build.sbt

* cats-effect-0.7
* kind-projector-0.9.5

Upgrade dependencies

---

build.sbt
core/jvm/src/test/scala/fs2/Pipe2Spec.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

@mpilquist there is the fix. 
I am still thinking of more proper way of interruption. I think there must be proper way to do it just in compile.

Added special handling of Uncons and CloseScope in case of interrupt

---

core/jvm/src/test/scala/fs2/ResourceSafetySpec.scala

Fixes #1052. Apparently asynchronous tests was too eager to compare that finalisers were called. The issue then manifested when system was slower or under higher load. 
Additionally, thanks to new `CompileScope` definition merged earlier, the resulting stream is not guaranteed to have all resources released when it terminates. As such, the test that required the cleanup to be called once the stream terminated was failing spuriously.

Added longer delay to `eventually` in Async Resource specs

---

README.md

Updated all the out-of-date links and version numbers in the README.

Update version info in readme

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

This fixes issue reported on gitter, related to zip/InterruptWhen. I have no ideas on how to write testcase for this. We could take that complex example and run it multiple times. But that seems sort of awful. 
Anyhow this essentially just removes the assertion from the interpreter. My theory is that due concnurrent nature and zipWith_ implementation, there was a chance that scope was closed twice, once by interrupted stream, and then when evaluation of `zipWith` finished. 
I consider this to be ok, hence we have guard that prevent double closing of the scope on `scope` level itself, and it seems unlikely you can construct stream without scope being created.
@mpilquist @AdamChlupacek @SystemFw comments please.

Do no throw exception when scope is not anymore in hierarchy.

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

Moved the running of the leg inside of algebra.

Fix for #1099

---

core/jvm/src/test/scala/fs2/async/RefSpec.scala
core/shared/src/main/scala/fs2/async/Ref.scala

Fixes the behavior of `access` to provide "only once" modification.
I spoke with @SystemFw a while ago about this (I think a month ago) but I forgot about it.

fix behavior in access

---

core/shared/src/main/scala/fs2/Stream.scala

This generalizes `.toList` and `.toVector` as `.to[C[_]]` where `C[_]` is anything with a CBF.

Generic to[C[_]] on Stream.ToEffect

---

LICENSE
build.sbt
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/main/scala/fs2/internal/FreeC.scala
core/shared/src/test/scala/fs2/FreeCSpec.scala
core/shared/src/test/scala/fs2/PullSpec.scala
project/build.properties

This isn't ready for merge yet. I'll add definitions for `bracketCase` for `Stream` and `Pull` along with laws checking.

Upgrade to cats-effect 1.0.0-RC

---

core/jvm/src/test/scala/fs2/ResourceSafetySpec.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

Propagate error if close of the root scope ended with failure.

---

core/jvm/src/test/scala/fs2/ResourceSafetySpec.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

This is just backporting @AdamChlupacek work on fixing #1130 to the 0.10 series
(cherry picked from commit cd9312d8f6da46800342ce225b5eaf94d26384b3)

Backport to 0.10: Propagate error if close of the root scope ended with failure.

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

Scala.js build fails due to https://github.com/typelevel/cats-effect/issues/233

Fix resource cleanup when a compiled stream is cancelled

---

docs/migration-guide-0.10.md

fix example

---

core/shared/src/main/scala/fs2/Stream.scala
io/src/main/scala/fs2/io/file/Watcher.scala
io/src/main/scala/fs2/io/file/file.scala
io/src/main/scala/fs2/io/tcp/Socket.scala
io/src/main/scala/fs2/io/tcp/tcp.scala
io/src/main/scala/fs2/io/udp/udp.scala
io/src/test/scala/fs2/io/tcp/SocketSpec.scala
io/src/test/scala/fs2/io/udp/UdpSpec.scala

Removed all singleton streams that existed solely for the purpose of bracketing with resources.

Added support for cats.effect.Resource

---

core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/jvm/src/test/scala/fs2/MergeJoinSpec.scala
core/jvm/src/test/scala/fs2/ResourceSafetySpec.scala
core/jvm/src/test/scala/fs2/StreamPerformanceSpec.scala
core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/async/mutable/Queue.scala
core/shared/src/main/scala/fs2/async/mutable/Signal.scala
core/shared/src/main/scala/fs2/async/mutable/Topic.scala
core/shared/src/test/scala/fs2/ErrorHandlingSpec.scala
io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/main/scala/fs2/io/tcp/Socket.scala
io/src/test/scala/fs2/io/file/WatcherSpec.scala

@mpilquist @pchlupacek I had some spare time so I thought I'd do this, let me know how it looks.

`bracket` always emits

---

core/shared/src/main/scala/fs2/Chunk.scala

Optimized Chunk.seq/Chunk.apply to avoid creation of Vectors

---

core/shared/src/main/scala/fs2/Stream.scala

Add performance disclaimer to observe1/observe

---

README.md
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/test/scala/fs2/ChunkSpec.scala
core/shared/src/test/scala/fs2/TestUtil.scala

Not particularly fond of this PR since the solution isn't particularly elegant and putting it out for comments.

Add other Chunk types backed by different native buffer types

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/test/scala/fs2/PullSpec.scala

backported from series/1.0 #1224

add Pull.fromEither

---

core/jvm/src/main/scala/fs2/compress.scala
core/jvm/src/test/scala/fs2/CompressSpec.scala
core/jvm/src/test/scala/fs2/MemorySanityChecks.scala
core/jvm/src/test/scala/fs2/PipeSpec.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/test/scala/fs2/ErrorHandlingSpec.scala
core/shared/src/test/scala/fs2/PullSpec.scala

This PR extends #1220 to `Pull`, based on [discussion with @mpilquist in Gitter](
https://gitter.im/functional-streams-for-scala/fs2?at=5b76387ce026575f0f844f3b).

constrain Pull.raiseError and add Pull.fromEither

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

Not sure why we've never done this before. `foldChunks` along with the change to `Algebra` which allows folding of a chunk at a time should result in *significantly* better performance for streams with large chunks.

Added toChunk to Stream and improved performance of toList/toVector/last/drain

---

io/src/main/scala/fs2/io/file/file.scala
io/src/main/scala/fs2/io/file/pulls.scala
io/src/test/scala/fs2/io/file/BaseFileSpec.scala
io/src/test/scala/fs2/io/file/FileSpec.scala
io/src/test/scala/fs2/io/file/WatcherSpec.scala

Fixes #1227
cc @rossabaker because I stole the code from him.

Add readRange function reading a range of bytes from a file

---

core/shared/src/main/scala/fs2/Stream.scala

Per discussion in Gitter, this is a common function so we might as well provide it directly

Added compile.lastOrError convenience function

---

core/shared/src/main/scala/fs2/Stream.scala

Better names for Stream.retry params

---

site/src/guide.md

Either the guide is slightly outdated or I am looking in the wrong place

Update bracket signature in guide

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

Due to being only an alias to `uncons`.

Remove ToPull#unconsChunk

---

core/shared/src/main/scala/fs2/Stream.scala

Small helpers, but quite useful with timed streams, I've wanted those for a quite a bit

Add zipRight and zipLeft

---

core/shared/src/main/scala/fs2/concurrent/Queue.scala

Opening this for discussion only at this point. This is one potential solution to #1273.
If we're open to something like this, then I think we might want to change `DequeueChunk1` such that calling `dequeueChunk1` on a `NoneTerminated` queue returns `F[Option[Chunk[A]]]` instead of a `F[Chunk[Option[A]]]`. Perhaps via something like:
```scala
trait DequeueChunk1[F[_], G[_], A] {
def dequeueChunk1(maxSize: Int): F[G[Chunk[A]]]
def tryDequeueChunk1(maxSize: Int): F[Option[G[Chunk[A]]]]
}
trait Queue[F[_], A]
extends Enqueue[F, A]
with Dequeue1[F, A]
with DequeueChunk1[F, Id, A]
with Dequeue[F, A] { self =>
}
trait NoneTerminatedQueue[F[_], A]
extends Enqueue[F, Option[A]]
with Dequeue1[F, Option[A]]
with DequeueChunk1[F, Option, A]
with Dequeue[F, A] { self =>
}
```

Added dequeueChunk1 to Queue

---

site/src/concurrency-primitives.md

Fix concurrency-primitives.md
- `SignallingRef` instead of `Signal`
- more relevant termination example with `SignallingRef`
- fix compilation issues (e.g `Stream.awakeEvery[F]`)

Fix concurrency-primitives.md

---

core/shared/src/main/scala/fs2/internal/Resource.scala

This PR suggests some changes to the code of the `Resource`, which I hope may improve it a bit:  
- Since Leases are built without parameters, and they only used the immutable value `state: Ref[F]` (immutable reference to Ref object), we can just have a single Lease object for all those using it.
- We extract a function `State.isFinished` to indicate when the state  allows running the `finalizer`.
- We extract a simple variable for the `F.pure(Right(()))` expression.
- Makes the resource `state` into a private val.

Resource: small code improvements.

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/concurrent/Queue.scala

The original performance test from #1296 now takes ~1-2s for me.

Fixed #1296 - linear time Queue#dequeue1 when should be constant

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

Part of https://github.com/functional-streams-for-scala/fs2/pull/1349. 
We make some changes in the internals of the `Stream` implementation, so as to try to decouple some of the several pieces of it, and help make the code more readable. 
- We add some comments to describe the `Algebra` GADT. 
- We make the `O` parameter of the `Algebra` GADT covariant. This allows us to define the sub-trait `AlgEffect` as Algebra operations with `O=INothing`, in other words, operations that are not concerned with output. As a consequence, for those operations we can remove the middle type parameter.

Remove Middle type Parameter in AlgEffect 

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

Since the `Step` case class is fully private to the Algebra, one of its type parameters can be made into "INothing". The extra type parameter is still used in the method `step`, which lifts to `FreeC[Algebra[F, O, ?, ]`, and it is needed to set the specific instance of `Algebra` for the stream being created.

Remove third Type Parameter from the Step Class

---

core/shared/src/main/scala/fs2/internal/FreeC.scala

The `monadInstance` value, in the `Result` object, which was not implicit, was only used at one place, and for the `map` method (through `flatMap`), explicitly. That being the case, we can drop that unused code and add a function `Result.map` function, directly on the companion object.

Remove MonadInstance object

---

README.md

Fixed as found in maven.
@SystemFw asked me if i could fix it.
edit: sorry wrong copy-paste name

fix readme for correct library versions in example

---

core/shared/src/main/scala/fs2/Stream.scala

Trivial optimisation for Pull.last

---

core/shared/src/main/scala/fs2/Stream.scala

- Merge the first `flatMap` with the `evalMap`, to save some inner stream allocations. 
- Extend and clarify the API documentation.

Small tweaks to Stream.debounce

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/ChunkSpec.scala

(I think the formatting changes were a result of `scalafmt` running during the build.)

add FunctorFilter instances for Stream and Chunk

---

core/shared/src/main/scala/fs2/Chunk.scala

Add Chunk.toNel

---

core/jvm/src/test/scala/fs2/StreamSpec.scala
core/shared/src/main/scala/fs2/Stream.scala

Proposal for https://github.com/functional-streams-for-scala/fs2/issues/1176

Add `Stream#rechunkRandomly`

---

core/jvm/src/test/scala/fs2/ResourceCompilationSpec.scala
core/shared/src/main/scala/fs2/Stream.scala
io/src/main/scala/fs2/io/io.scala

~~This should fix all interesting cases for fs2, although it will still be possible to build pathological cases until I fix Resource in cats-effect~~
EDIT: actually this fixes the bug for good

Make Resource compilation cancelable

---

core/shared/src/main/scala/fs2/internal/CompileScope.scala

Several small lift-ups to the `CompileScope` internals: 
- Remove method `unregisterResource` which is unused.
- In `unregisterChild`, do not copy if the child to be unregistered was not there.
- Merge method `findAncestor` into `findSelfOrAncestor`, since one was a special case of the other. 
- Privatise some methods.

CompileScope.State: Small cleanup and optimisation

---

core/shared/src/main/scala/fs2/internal/CompileScope.scala

We reorganise the operations of the `open` method of the `CompileScope` class.
We change `createCompileScope` from being an `Option` of the `InterruptContext` to directly building the new scope. This hides the `newScopeId` in this F-value.
This operation saves the allocations of a `Some` and a Tuple2 objects, although now the `CompileScope` is now built regardless of path. Not a big loss, since this is likely the frequent case.
_Note to reviewers:_ most line changes are due to whitespace, indentation, and braces.
_Note:_ I have looked for a `modifyM` method, which could allow us to avoid allocations until the scope is known to be open. Reading in `cats-effect`, I just found [this issue](https://github.com/typelevel/cats-effect/issues/451), which mentions it tangentially.

CompileScope.open: rearrange operations

---

.travis.yml
build.sbt

Tested with `cats-effect-2.0.0-M4` from sonatype repo.
Should work once it has synced to maven central.

Scala 2.13

---

core/shared/src/main/scala/fs2/Stream.scala

I'm not sure if those are typo, but I didn't understand their meaning. At least one of them is typo

possibly typo fixed

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/test/scala/fs2/ChunkSpec.scala

Change Chunk scanLeft behaviour to match standard collections

---

io/src/main/scala/fs2/io/tcp/SocketGroup.scala
io/src/main/scala/fs2/io/tcp/SocketOptionMapping.scala
io/src/main/scala/fs2/io/tcp/tcp.scala

Addresses
https://github.com/functional-streams-for-scala/fs2/issues/1546

Additional socket options

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

The `compileLoop` method has a system of nested executions, which correspond to the Step algebra operations, in which an inner stream is executed with a different CompileScope.
This was implemented with an inner ADT, `R` with three cases: 1) the compilation on a certain Scope is _done_, 2) the compilation is stopped with some output values, and the rest of the stream; or 3) the compilation was interrupted. This ADT is only used as a way of messaging from one part of the method to another: objects created in one part are deconstructed in another part. This meant that several objects would be allocated without need.
This commit replaces the use of that ADT by a trait called `CompileCont` whose methods correspond to the three cases of that ADT. The `CompileCont` acts as a continuation: it …

Algebra: replace the R ADT with a CompileCont trait

---

core/shared/src/main/scala/fs2/internal/FreeC.scala

The method `Result.recoverWith` is only used once, in the `bracketCase` method. Therefore, we can unfold it to remove some code length. 
- Unfolding means that the `PartialFunction` object that is passed needs not be allocated.
- Since all we do is to create the `CompositeFailure`, we do not need to check for any `NonFatal` exception.

Unfold-expand recoverWith

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

Fixes #1625. Reverts changes in commit 36b1279cda415ebe8bb3faa33cb9aa3e6c6697d9.
This commit changed the Compilation Loop was modified in a recent PR to use a continuation and a stack of continuations. However, this introduced a memory leak that could be seen running a simple program, as described in #1625.

Solves memory Leak

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala
core/shared/src/test/scala/fs2/EffectTestSupport.scala
io/src/main/scala/fs2/io/io.scala
io/src/test/scala/fs2/io/IoSpec.scala

Fixed deadlock race condition in readOutputStream

---

README.md

I would like a library of mine to be added to the list of projects which use fs2 library.

Add canoe to the list of projects

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

In the same vein as `bracketWeak`, `bracketCaseWeak`, etc.

Add Stream.resourceWeak

---

core/shared/src/test/scala/fs2/ChunkSpec.scala

Fixed intermittent test failures with Chunk[Double] and Chunk[Float] instances

---

io/src/main/scala/fs2/io/io.scala

I changed from "a stream that will emits a single..." to "a stream that will emit a single..."

Small typo in comment

---

core/shared/src/main/scala/fs2/internal/FreeC.scala

Before the changes to make FreeC covariant on F, we needed to use the Result as a separate ADT. Now, Result is fully integrated with the FreeC ADT, so we can type-safely pass it around.
- We remove the Result.unapply method.
- We simplify matches to the check on Result.
These changes are similar to those in https://github.com/functional-streams-for-scala/fs2/pull/1482, but now we do not need `asInstanceOf` casts, since `Result` is inside `FreeC`.

Simplify matching on Result.

---

.travis.yml

Scalafmt should not vary with the Scala version.

Only test formatting in one build.

---

core/shared/src/main/scala/fs2/Pull.scala

It seems that the implementation of the Sync type-class for Pull does
not require anything extra on the F or O, so it has same parameters as
the Monad instance, but same code. Chance to DRY it up.
This change should keep backwards-, but may break forwards-compatibility.

Unify instances of Sync and Monad for Pull.

---

io/src/main/scala-2.12/fs2/io/CollectionCompat.scala
io/src/main/scala-2.13/fs2/io/CollectionCompat.scala
io/src/main/scala/fs2/io/tls/TLSContext.scala
io/src/test/scala/fs2/io/tls/TLSDebugExample.scala
io/src/test/scala/fs2/io/tls/TLSSocketSpec.scala
io/src/test/scala/fs2/io/udp/UdpSpec.scala

Also fixed a couple compiler warnings

Changed some TLSContext constructors to handle exceptions

---

io/src/main/scala/fs2/io/tls/TLSParameters.scala

This is useful in other TLS applications built on fs2.

Make toSSLParameters public

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamLawsSpec.scala
core/shared/src/test/scala/fs2/StreamSpec.scala

cats.Align instance for Stream

---

build.sbt
reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamSubscriber.scala
reactive-streams/src/main/scala/fs2/interop/reactivestreams/package.scala

Support for preemption-safe stream subscription

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/Stream.scala

Use Chunk.Queue everywhere

---

README.md

add mysql-binlog-stream project

fix fs2-aws url

---

README.md
site/docs/ecosystem.md

This library is a work in progress, initiated to learn mo some fs2, cats effect and purely functional programming in Scala. I open this PR because @gvolpe kindly suggested it to me on Gitter. But I must face the fact that this code is not mature and may not be maintained that much…

Updated readme and ecosystem with fs2-mqtt reference

---

.github/workflows/publish-site.yml
shell.nix

Alright, this should fix it. I don't know why the $JAVA_HOME variable is set to the Zulu VM when I am specifically installing `openjdk11` but well...

Fix automated publishing of microsite

---

core/shared/src/main/scala/fs2/Stream.scala

Update s.as[O2] documentation.

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

The Interrupted class is explicitly expected, at some point, to have a `Token` that identifies the Scope from which the interruption came. No much point in having that type parameter if this is not truly generic.

FreeC.Result.Interrupted: remove unused type parameter.

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

The `FreeC` compile logic was split in two top-level methods: `compileLoop` deals with iterating the evaluation (compilation) until a chunk of output is produced; whereas `compile` implements the outer loop, which aggregates each chunk of outputs into the accumulated result.
This commit unifies these methods, by making both the outer and inner loops into private methods of a `compile` method. This reduces code length, and has the small benefit of "inlining" the generation of an F value at the end of the inner loop, with the `flatMap` performed on it in the outer loop.

FreeC: merge compile and compileLoop methods.

---

core/shared/src/main/scala/fs2/internal/Algebra.scala

We make that parameter covariant and remove it from the two classes
without output.

FreeC - Small change: make inner R ADT covariant.

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/internal/Algebra.scala

We move the main logic of `Stream.flatMap` to the `FreeC` object, with the name `flatMapOutput`.
This lets us encapsulate `transformWith` and `interruptBoundary`.

Stream / FreeC: move the Stream-flatmap logic to FreeC.

---

core/shared/src/main/scala/fs2/Stream.scala

I found the existing documentation very confusing - as did someone else https://gitter.im/functional-streams-for-scala/fs2?at=5dd6afa31bf5192e667c4129

Add some clarity to the documentation on pauseWhen

---

core/shared/src/main/scala/fs2/Stream.scala

Flip the description of pauseWhen

---

core/shared/src/main/scala/fs2/Stream.scala

Emit initial state in evalScan early

---

core/shared/src/main/scala/fs2/Stream.scala

When reading the source code of the stream methods, one notices that codes is deeply nested and inlined. In some cases, some lines are nested 22 levels. This is often discouraged.
This commit does some changes to reduce this nesting:
- Replace chains of flatMaps with for comprehensions.
- For the cases where we use `Stream.eval(fstream).flatten`, extract the fstream in a separate variable.

Stream - Formatting and reorganise large methods.

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Scope.scala

A combinator to simplify #1982

Add Pull.extendScopeTo combinator

---

core/shared/src/main/scala/fs2/Stream.scala

- Extract functions to signal an interruption, and for make a Stream
watch (interrupt when) the interruption has been risen.
- Extract `pumpFromQueue` stream, from the shared queue.
- Extract `doneAndClose` action, to indicate that either side has
ended, and if the other one has too, close the queue with None.
- In the `go` recursive function, remove the `queue` parameter.
- Replace some chains of `flatMap` with for comprehension.

Stream.merge: small refactorings for readability.

---

core/jvm/src/it/scala/fs2/MemoryLeakSpec.scala
core/shared/src/main/scala-2.12/fs2/CollectorPlatform.scala
core/shared/src/test/scala/fs2/StreamSuite.scala

Improve fairness issues discovered in CE3 work

---

core/shared/src/main/scala/fs2/text.scala
core/shared/src/test/scala/fs2/TextSuite.scala

Fix intermittent test failures in TextSuite

---

core/jvm/src/main/scala/fs2/compression.scala

1. Fix buffer size limits - to allow higher than 128 *bytes*
2. Use a preallocated buffer so we don't allocate it on every new chunk

fix compression: buffer usage

---

build.sbt
io/src/main/scala/fs2/io/tls/TLSContext.scala
io/src/main/scala/fs2/io/tls/TLSEngine.scala
io/src/main/scala/fs2/io/tls/TLSParameters.scala
io/src/main/scala/fs2/io/tls/TLSSocket.scala

Adds SSL Application Protocol Support, both accessing the protocol and Setting it in the selector.

SSL: Add Application Protocol Selection and Access

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/concurrent/Queue.scala

- Remove redundancy/duplication
- Use combinators where appropriate
- Reduce nesting in flatMap chain

Readability (+ future performance) improvements

---

README.md

Adding HiFi to list of adopters

Update README.md -- Adding hi.fi to list of companies

---

core/shared/src/main/scala/fs2/internal/CompileScope.scala
core/shared/src/test/scala/fs2/StreamSuite.scala

- Be explicit about the closed state
- Use type class syntax

Cleanup compile scope

---

site/docs/ecosystem.md

Adding a link to my prox library as discussed with @SystemFw

Add prox to the ecosystem page

---

core/shared/src/main/scala/fs2/Pull.scala

Other branches nest it... may be relevant or perhaps not.

Delay unrolling until after checking interruption

---

build.sbt
io/src/main/scala/fs2/io/JavaInputOutputStream.scala
io/src/main/scala/fs2/io/tcp/SocketGroup.scala
io/src/main/scala/fs2/io/tls/TLSEngine.scala
io/src/main/scala/fs2/io/tls/TLSSocket.scala
io/src/test/scala/fs2/io/tcp/SocketSuite.scala
reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamSubscriber.scala
reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamSubscription.scala
reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamUnicastPublisher.scala
reactive-streams/src/main/scala/fs2/interop/reactivestreams/package.scala
reactive-streams/src/test/scala/fs2/interop/reactivestreams/CancellationSpec.scala
reactive-streams/src/test/scala/fs2/interop/reactivestreams/UnsafeTestNGSuite.scala

One TCP test is failing, perhaps related to changes to `Semaphore`

Upgrade to latest CE3 release

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/internal/CompileScope.scala

In the compile loop, the case for the `Step` class, includes some logic to shifting from the current scope to another scope, by id. Since the compileLoop is already large (and we may add more things to it) it may be convenient to move some logic to the `CompileScope` class.

Pull - split compile-shift out of the Compile loop.

---

core/shared/src/main/scala/fs2/Pull.scala

- Introduces a new `MapOutput` subclass of `Pull`, to represent mapping the outputs with a funciton F.
- Current interpretation still relies on expanding into a new Pull-object. 
- When building that new tree, we can avoid the extra `suspend` because we are unrolling.

Introduce MapOutput constructor. 

---

core/shared/src/main/scala/fs2/Pull.scala

Currently, the compileLoop is a large match statements, with one case for each constructors of Pull, and in each case we have the full body. This creates a small confusion of parameter names, and type names. It also causes trouble due to the GADT handling in Scala.
Rather than doing that, we can create a few inner methods. Each method can declare any type parameters of its own, or fix those that should be determined by the type of constructor (as a good GADT would).
_Note_ although the local methods for `Translate` and `MapOutput` are coded in, I had difficulty _tweaking_ the type parameters in the main `match` to avoid compiler mistakes and compiler errors, so that code is still there.

Pull - CompileLoop: reorganise into local methods.

---

core/shared/src/main/scala/fs2/Pull.scala

In the compile loop, we use an ADT called R to indicate when the evaluation has stopped, at any point, and propagate it up the call-chain for it to be handled. We introduce a trait `RunR` to evaluate any value of that ADT into an end result. 
Using 3 methods instead of the match directly would prevent some GADT - pattern matching errors that have been bothering us.
_Note_ A possible future change would be to propagate the `RunR` in the recursive call, so that the creation of those `R` objects are replaced by calls to the algebra method. We tried this once, but it caused a memory leak... next time may be different.

Introduce a runR trait

---

core/shared/src/main/scala/fs2/Pull.scala

- We make class View into a subclass of a function, from a result to the rest of the pull.
- We add a type alias, for that function, and onner methods of compile Loop only need the function part, not view.

Pull - Make view a subclass of Function

---

core/shared/src/main/scala/fs2/Pull.scala

The OpenScope pull constructor, to change the evaluation into a new resource scope, was only used at one place, followed by a `Pull.flatMap` into a continuation, to run an inner stream in the opened scope.
We replace the `OpenScope` class with an `InScope` class, which includes the inner stream. Most of the semantics is now moved to the `goInScope` method, of evaluation.

Pull - Replace OpenScope with InScope

---

core/shared/src/main/scala/fs2/Pull.scala

The unroll-loop `viewL` creates subclasses of View (which are often
ephemeral) or Bind. Rather than keeping these nested in the code,
we can extract them out to new private classes...

Pull: Create Named subclasses for Bind, and Views.

---

core/shared/src/main/scala/fs2/Pull.scala

- Instead of creating Bind at top, we pass down to the `goView` method
which can take care of it.
- Add variance to the MapOutput class.
- Replace mout case with call to goMapOutput.

MapOutput: small cleanup to handling.

---

core/shared/src/main/scala/fs2/Pull.scala

The `R` trait, with the subclasses `Done`, `Out`, and `Interrupted`, was only used to carry information from some points of the compilation to other levels with smaller nesting. They were short-lived objects, which only serve a procedural function. 
Instead of passing the message up, the idea is to thread the interpreter
- WE add in the `go` method of the compile loop another parameter, of type `Run`which is the "interpreter" on which this call of `go` is to be paused. As we go deeper (as in `Step` or `Translate`) into the loop, we nest instances of `Run`
- We remove the `R` trait of short-lived objects. We replace the "runner" that was creating them with a runner that generates a callback-like closure, one that would invoke another `Run`. 
- Since at some points of the interpretation we …

Pass end-runners through the compile loop.

---

core/shared/src/main/scala/fs2/Pull.scala

- We remove the FlatMap-specific subclasses of `View`, so that now the `viewL` loop handles a FlatMapOut just as a normal `Action`.
- Introduce class FlatMapRunR, a subclass of Run, derived from `StepRunR` class, but taylored to FlatMap operations. In particular, this class performs the inner-pull expansion within the `out` method, which saves the wrapping in `Result`.
- Compiling/interpreting a `FlatMapOut` instruction no longer requires creating a Step, or a Result, or an Option.

 Pull: move FlatMapOutput logic to specialised Run

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/internal/Scope.scala

We add to Scope the following methods:
- A method to ask if this is the Root Scope.
- A method to get the depth (distance to the root scope)
- A method to search either a descendent or ancestor scope.
Pull: rewrite `goCloseScope` method to reduce code nesting:
- Split from `closeAndGo` the logic to get the Result
- Use cases with guards for the choices.
- Inline top-level parts of `closeAndGo` method.

Pull - Scope: rewrites

---

io/src/main/scala/fs2/io/Network.scala
io/src/main/scala/fs2/io/tcp/SocketGroup.scala
io/src/main/scala/fs2/io/tls/TLSContext.scala
io/src/main/scala/fs2/io/udp/SocketGroup.scala
io/src/test/scala/fs2/io/tcp/SocketSuite.scala
io/src/test/scala/fs2/io/tls/DTLSSocketSuite.scala
io/src/test/scala/fs2/io/tls/TLSDebugExample.scala
io/src/test/scala/fs2/io/tls/TLSSocketSuite.scala
io/src/test/scala/fs2/io/tls/TLSSuite.scala
io/src/test/scala/fs2/io/udp/UdpSuite.scala
site/docs/concurrency-primitives.md
site/docs/documentation.md
site/docs/guide.md
site/docs/io.md

@kubukoz @SystemFw This is the start of what it would take to make `Network` a more typical capability trait. Note the fairly significant API changes. Thoughts? /cc @tpolecat

Initial sketch of making Network a full algebra

---

core/shared/src/main/scala/fs2/Pull.scala

The output of uncons is just Nothing.

Pull uncons: remove unneeded type param.

---

site/docs/guide.md

Tries to improve the [previous solution](https://github.com/typelevel/fs2/pull/1876) for #1245.
The previous solution might be confusing since it touches on [the `Stream.map` quirk](https://github.com/typelevel/fs2/blob/main/core/shared/src/main/scala/fs2/Stream.scala#L140) of operating on an entire chunk at a time. It also has that `i => i / (i % 2)` calculation that distracts from the point that that example is trying to make.
IMHO, this solution better illustrates what is pointed out by #1245. But of course, I might be wrong. :)

Simplify error handling docs (#1245)

---

CONTRIBUTING.md
build-site.md

* Remove deprecated instructions
* Fix `docsify` command

Small improvements of docs on how to build new site

---

README.md

readMe microsite links fixed

---

core/shared/src/main/scala/fs2/Stream.scala

One thing to notice, is that there are two appearances of "closing the output Queue" but none of "closing the sink queue". This is still as it was, but I am not certain as to whether we should also close the `sink` queue.

Stream - Observe: rewrite

---

core/shared/src/main/scala/fs2/Pull.scala

remove some type annotations/castings that are not needed.
This adds some more warnings but still compiles.
_Note_ built on top of #2256

Cleanup some type casts

---

core/shared/src/main/scala/fs2/Stream.scala

Remove the `getScope` method from the Stream api, which was private,
and unfold its only use replacing it with Pull-level operators.

Stream - remove getScope method.

---

core/shared/src/main/scala/fs2/Pull.scala

The `Succeeded`, `Fail`, and `Interrupted` are just as relevant Pull constructors as the rest. They are also just as bound to the `Pull` class and object as the rest. No sense in keeping a `Result` object and internal accesses.

Pull: remove nested `Result` object

---

core/shared/src/main/scala/fs2/Pull.scala

The name of `Result` is a bit overloaded. Using `Terminal` better indicates that it is an end-of-pull.
Built on top of #2270

Rename `Result` to `Terminal`

---

core/shared/src/main/scala/fs2/Stream.scala

These `newOut` chunks were not always used, which is unneeded allocation. Can easily be removed.

Stream - Microoptimisation: do not preallocate unused chunk.

---

core/shared/src/main/scala/fs2/Pull.scala

- The `boundToScope` function had  the effect of weaving an error, from the inner pull, into the terminal result of the CloseScope. However, that weaving can also be done in the `goCloseScope` method, without the need to use the `transformWith` function.
- The way of closing scope after  the `inScope` operation only depends on how the inner streams ends, not the other parameters of the `goInScope` method, so we can extract it.
- We simplify text of the `sys.error`, since it is clear by how the `CloseScope` is constructed that the case cannot arise.

Pull: CloseScope and InScope

---

core/shared/src/main/scala/fs2/Stream.scala

Use for comprehensions to reduce nesting/inlining.

Stream - Switchmap - Rewrite.

---

core/shared/src/main/scala/fs2/Stream.scala

Currently, the `intersperse` method modifies the Chunk structure of
the receiver stream, by extracting the first element into a separate
chunk. We modify the `intersperse` method to avoid  that.

Stream - Intersperse: keep chunks.

---

core/shared/src/main/scala/fs2/Pull.scala

The Pull methods `.scope` and `.streamNoScope` are currently implemented with the type-bounds evidence pattern and the
`asInstanceOf`. It may be better to define them as extension methods in an implicit class which, unlike the Pull class,
call be specialised to pulls where the result type is Unit.
This did not seem to require any special imports anywhere. It may be that, as implicits, they are attached to the `Pull` type everywhere.

Pull: turn `.stream` and `.streamNoScope` into extension methods.

---

build.sbt
core/shared/src/main/scala/fs2/Compiler.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/internal/Scope.scala
core/shared/src/test/scala/fs2/Fs2Suite.scala
io/src/test/scala/fs2/io/IoSuite.scala

Also fixes the problem with resource leaks in uncancelable

Update to CE RC3

---

benchmark/src/main/scala/fs2/benchmark/GroupWithinBenchmark.scala

FYI it runs OOM on `main`.
On `v2.5.3` it's alright.

Add groupWithin benchmark

---

core/shared/src/main/scala/fs2/internal/InterruptContext.scala

Fixes #1471
Not sure if this is necessary or not so I figured I'd open a PR and then we decide either to merge or we close #1471 as won't fix.

Check for scope interruption before effect evaluation

---

io/src/main/scala/fs2/io/io.scala

Use a sliced chunk instead of slicing an array

---

io/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala

JDK 11.0.11, the latest update release of JDK 11, _disabled_ TLSv1 and TLSv1.1. Even though `SSLContext.getInstance` returns a valid `SSLContext` because these protocols are still supported, trying to establish a socket connection fails with an exception. This PR adds another check that the protocol being tested is not disabled.
Alternatively, we can _enable_ these protocols for the execution of the tests. Let me know if this is a preferred solution and I will change the code.
Here's the output from testing on 11.0.11.
```
fs2.io.net.tls.TLSSocketSuite:
3190
==> X fs2.io.net.tls.TLSSocketSuite.TLSSocket - google - TLSv1 - client writes before reading  0.111s javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
3191
at …
```

TLS test suite errors on JDK 11.0.11

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/test/scala/fs2/PullSuite.scala

I don't have a strong opinion whether this function should exist in FS2. Thus, I submit this to hear different views/opinions.
Personally I wrote it for error handling, but I think that my case can be implemented with https://github.com/cb372/cats-retry.

loopEither - a more generic method of loop

---

core/shared/src/main/scala/fs2/Pull.scala

Resolves #2394. 
We fix a memory leak that was introduced in a previous Pull Request https://github.com/typelevel/fs2/pull/2196
Note that some of the changes in that PR had already been reverted to fix another memory leak.
@svalaskevicius With this changes, I was able to run the `Hello` program from #2395 for more than 20 seconds. Could you take a look to see if it fixes the problem you found?

Fix 2394 - Memory Leak.

---

core/jvm/src/it/scala/fs2/MemoryLeakSpec.scala

MemeoryLeakSpec case as described in #2408

broadcastThrough memory leak case

---

core/shared/src/main/scala/fs2/Pull.scala

Partially reverts yet another few changes from
https://github.com/typelevel/fs2/commit/e25a6e1c59ec77b4c60e97731d1b152aec1c068b
Fixes (one) test case introduced in #2408

Fix memory leak in continuous topic.

---

io/src/main/scala/fs2/io/net/SocketGroup.scala
io/src/test/scala/fs2/io/net/tcp/SocketSuite.scala

fix socket option  for tcp server

---

core/shared/src/main/scala/fs2/Pull.scala

- Use a "DelegateBind" class where it fits ok.
- Rename one var.

Some small touches

---

io/src/test/scala/fs2/io/IoSuite.scala

Trying to match the semantics of the test in #2446.

Shutdown the single threaded runtime in the readOutputStream test

---

core/shared/src/main/scala/fs2/Stream.scala

Shorter, no mutual recursion, and perhaps slightly more efficient.
Unless I am missing something, the `mapOutput` should suffice?

ZipWithAll: replace use of Uncons/Flatmap with MapOutput

---

core/shared/src/main/scala/fs2/internal/Scope.scala

Given that last operation was a `map`, this should not cause problems...

Syntax Sugar: Scope: use for comprehension.

---

core/shared/src/main/scala/fs2/Chunk.scala

Useful with `s.chunks.foldMonoid` for instance

Monoid for Chunk

---

project/plugins.sbt

Bump sbt-sonatype to 3.9.7

---

io/js/src/main/scala/fs2/io/net/SocketPlatform.scala
io/shared/src/test/scala/fs2/io/net/tcp/SocketSuite.scala

Fixes a mistake where the port info was missing, causing socket address parsing to fail. Also adds a sanity test.
cc @ChristopherDavenport with the bomb squad for an extra set of eyes 😉

Fix address methods for Node.js socket

---

core/shared/src/main/scala/fs2/Pull.scala

We can just passs the `Interrupted` object, since that is the
most common way this method is called.

Pull - Runner interrupted method, small simplification.

---

core/shared/src/main/scala/fs2/Pull.scala

The methods `viewL` and `interruptBoundary` are only ever used
inside the compile loop, for evaluating a stream.

Pull - encapsulate auxiliary Compile methods

---

io/js/src/main/scala/fs2/io/NodeStream.scala
io/js/src/main/scala/fs2/io/file/PosixFiles.scala
io/js/src/main/scala/fs2/io/internal/SuspendedStream.scala
io/js/src/main/scala/fs2/io/ioplatform.scala
io/js/src/main/scala/fs2/io/net/DatagramSocketGroupPlatform.scala
io/js/src/main/scala/fs2/io/net/SocketGroupPlatform.scala
io/js/src/main/scala/fs2/io/net/SocketPlatform.scala
io/js/src/main/scala/fs2/io/net/tls/TLSContextPlatform.scala
io/js/src/main/scala/fs2/io/net/tls/TLSSocketPlatform.scala
io/js/src/test/scala/fs2/io/IoPlatformSuite.scala

Builds on #2496 to dramatically simplify the Node.js (TLS) socket implementations. (Feel free to close #2496 and review the changes all together here.)

Overhaul Node.js socket implementations

---

io/js/src/main/scala/fs2/io/file2/FilesPlatform.scala
io/js/src/main/scala/fs2/io/file2/Path.scala

Only the PathSuite is failing, do you mind having a look? It seems that there is something extra to be done at path construction time.

file2 JS bug fixes/cleanup

---

core/shared/src/main/scala/fs2/Pull.scala

In previous PR we got variance the other way around. This way we can avoid a couple of `asInstanceOf` calls.

Pull: contP variable small adjustment.

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/main/scala/fs2/text.scala

Fix deprecation versions

---

core/shared/src/main/scala/fs2/Pull.scala

In the Scala 2.13.6 compiler, due to some compiler bug, when matching against a `ViewL` (which is either a terminal or an action), if the case for the action goes after the cases for terminals, the compiler thinks it is unreachable and issues a warning. To sidestep this problem, we reorder cases to put terminals at the bottom.

Scala 2.13: avoid compiler warnings.

---

io/js/src/main/scala/fs2/io/file/FilesPlatform.scala
io/jvm/src/main/scala/fs2/io/file/FilesPlatform.scala
io/shared/src/main/scala/fs2/io/file/Files.scala

Came up while working on https://github.com/http4s/http4s/pull/5226.

Implement Files#realPath

---

reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamSubscriber.scala
reactive-streams/src/main/scala/fs2/interop/reactivestreams/package.scala

Use AtomicReference instead of Ref

---

site/getstarted/install.md
site/guide.md

Hello,
Saw a couple of small things on the site and thought I'll PR an amendment.
One question - I believe I saw that `fs2-io` is only compatible with node, is that correct? I could add that as a comment in there as well

Amended a couple of things on the site

---

core/shared/src/main/scala/fs2/internal/Scope.scala

See https://github.com/typelevel/fs2/issues/2371 for a discussion of the underlying issue.

Improve Scope#interruptWhen error

---

protocols/shared/src/main/scala/fs2/protocols/ip/Ipv4Header.scala
protocols/shared/src/main/scala/fs2/protocols/ip/tcp/TcpFlags.scala
protocols/shared/src/main/scala/fs2/protocols/ip/tcp/TcpHeader.scala
protocols/shared/src/main/scala/fs2/protocols/ip/udp/DatagramHeader.scala
protocols/shared/src/main/scala/fs2/protocols/mpeg/PesStreamId.scala
protocols/shared/src/test/scala/fs2/protocols/ip/Ipv4HeaderTest.scala

Target the `main` branch if this PR is targeted for the 3.x series and the `series/2.5.x` branch if targeted for the 2.5.x series.
If the CI build fails due to Scalafmt, run `sbt fmt` and push the changes (generally a good idea to run this prior to opening the PR).

Fix ipv4 codec

---

core/shared/src/test/scala/fs2/ParEvalMapSuite.scala

parEvalMap* - fix test "cancels unneeded"

---

.github/workflows/ci.yml
build.sbt

Rm Jabba index

---

core/shared/src/main/scala/fs2/Stream.scala

Based on conversations with @zainab-ali and motivated after reading the `observe` method, in #2778 and #2765.

Observe - Expand API Docs

---

core/jvm/src/main/scala/fs2/compression/CompressionPlatform.scala
core/jvm/src/test/scala/fs2/JvmCompressionSuite.scala
core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/test/scala/fs2/BracketSuite.scala
core/shared/src/test/scala/fs2/CompressionSuite.scala

Fix #2785 - fix problematic usage of Stream.bracket in gunzip and add Pull.evalMap and Pull.lease

---

build.sbt

https://repo1.maven.org/maven2/org/scalatestplus/testng-6-7_3/

remove unnecessary `CrossVersion.for3Use2_13`

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamSuite.scala

Add `Stream.fromAutoCloseable` and `Stream.fromAutoCloseableWeak`

AutoCloseable support

---

core/js/src/main/scala/fs2/ChunkRuntimePlatform.scala
core/js/src/test/scala/fs2/ChunkRuntimePlatformSuite.scala

`Chunk` <-> JS `Uint8Array` conversion should respect offset/length

---

core/shared/src/main/scala/fs2/Pull.scala

Revert "Pull - Cut ties with BindBind, no need for BuildR"

---

io/js/src/main/scala/fs2/io/file/Path.scala
io/shared/src/test/scala/fs2/io/file/PathSuite.scala

It was losing the first name in the list.

Fix JS `Path#names` bug

---

core/shared/src/main/scala/fs2/Pull.scala

It's debatable whether this is a good idea given the inconsistency it introduces, but it does increase clarity on where `Pure` is actually needed and make a step towards eventually being able to remove it.

Change `Pure` to `Nothing` in Pull

---

reactive-streams/src/main/scala/fs2/interop/reactivestreams/package.scala

correcting small issue in the documentation string

Fix small typo in documentation

---

core/jvm/src/main/scala/fs2/compression/CompressionPlatform.scala
core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/test/scala/fs2/ChunkSuite.scala

fixed unnecessary array copy in Chunk

---

site/adopters.md

Adding On Air Entertainment to list of adopters
Target the `main` branch if this PR is targeted for the 3.x series and the `series/2.5.x` branch if targeted for the 2.5.x series.

Add On Air Entertainment to adopters

---

build.sbt
io/js/src/main/scala/fs2/io/net/tls/TLSContextPlatform.scala
io/js/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala
io/jvm/src/main/scala/fs2/io/net/tls/TLSContextPlatform.scala
io/shared/src/main/scala/fs2/io/net/tls/TLSContext.scala

... but still chasing down one more bug I found while testing this change.

Implement insecure `TLSContext` for Node.js

---

core/shared/src/main/scala/fs2/timeseries/TimeSeries.scala
core/shared/src/main/scala/fs2/timeseries/TimeStamped.scala

Add ability to have a monotonic time series (fixes #2960)

---

io/js/src/main/scala/fs2/io/ioplatform.scala
io/js/src/test/scala/fs2/io/IoPlatformSuite.scala

Fixes an issue discovered in:
- https://github.com/http4s/http4s/pull/6652
This issue newly surfaced in 3.2.13 because of the fix making finalizers non-cancelable:
- https://github.com/typelevel/fs2/pull/2968

Fix hanging in `writeWritable` on unacked 'end'

---

.github/workflows/ci.yml
build.sbt

... because GHA just pulled the rug out from under our feet 😡 
- https://github.com/actions/runner-images/issues/6283

Invoke brew via full path

---

core/shared/src/main/scala/fs2/Chunk.scala

The `traverse_` one in particular, for singleton chunks (which are generated by fs2 operations) may be useful to optimise. Chunk `flatMap` may be less relevant, but still handy.

Chunk: short-cut flatMap and traverse_ for singletons

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

- Pull: introduce an `unconsFlatMap` combinator, that expands each chunk of a pull into a new pull. 
- Stream: we use the new unconsFlatMap combinator for a few operations, instead of `repeatPull`.

Pull - UnconsFlatMap

---

core/shared/src/main/scala/fs2/Stream.scala

In the implementation of `evalMap`, we expand the `Stream.eval` and the `Stream.flatMap` methods to directly work on Pull. This saves creating one ephemeral `Stream` object (it is a non-AnyVal wrapper) for each element in the output stream.
Maybe this kind of optimisation is already done by the JVM itself, but it is not too long to do on the code.

EvalMap - Quick Optimisation.

---

core/shared/src/main/scala/fs2/Stream.scala

Optimize `unchunks`

---

core/shared/src/main/scala/fs2/Chunk.scala
core/shared/src/main/scala/fs2/text.scala

Following up on https://github.com/typelevel/fs2/pull/3008#discussion_r991435145.

Use `ByteVector` for BOMs

---

core/shared/src/main/scala/fs2/Pull.scala
core/shared/src/main/scala/fs2/Stream.scala

Much like we did yesterday in #3016 for `flatMapOutput`.

Pull - turn "unconsFlatMap" into an extension method.

---

core/shared/src/main/scala/fs2/Stream.scala

I don't _think_ this makes a semantic difference, and it's obviously a matter of taste, but I think this implementation is cleaner.

Simplify `holdResource`

---

core/shared/src/main/scala/fs2/concurrent/Signal.scala
core/shared/src/test/scala/fs2/concurrent/SignalSuite.scala

Signalling counterpart to Cats Effect `Ref.lens`.

Add `SignallingRef.lens`

---

core/jvm-native/src/test/scala/fs2/compression/JvmNativeCompressionSuite.scala

Cross platform `CompressionSuite` for Native

---

io/js/src/main/scala/fs2/io/file/FilesPlatform.scala
io/js/src/main/scala/fs2/io/internal/facade/fs.scala
io/jvm-native/src/main/scala/fs2/io/file/FilesPlatform.scala
io/shared/src/main/scala/fs2/io/file/Files.scala
io/shared/src/test/scala/fs2/io/file/FilesSuite.scala

A bit of a rare use case compared to symlinks - but it was straightforward enough to implement on jvm and js

Add Files.createLink for hard links

---

io/jvm-native/src/main/scala/fs2/io/file/Path.scala
io/jvm/src/test/scala/fs2/io/file/JvmFilesSuite.scala
site/io.md

Simplify creating `Path` in custom `FileSystem`

---

core/jvm-native/src/test/scala/fs2/compression/JvmNativeCompressionSuite.scala

Saw this timeout a couple times. Let's see if this helps, or maybe it's a legit issue 🤔

Increase timeout for Native compression suite

---

core/shared/src/main/scala/fs2/Stream.scala

- Avoid the call to the "chunks" function, just Pull from underlying.
- Instead of using an `Option[Int]`, we can just use an Int with a special negative value to indicate that it is low.
- No need to wrap the (impure) computing of nextSize inside a pull.

rechunkRandomlyWithSeed - Microoptimise implementation.

---

core/shared/src/main/scala/fs2/concurrent/Signal.scala
core/shared/src/test/scala/fs2/concurrent/SignalSuite.scala

So that you can derive a signal that only emits updates on changes to the value, as determined by `Eq`. The default behavior is to emit an update for _every_ `set(...)`.
This is easily implemented via `.discrete.changes`. `.get` and `.continuous` don't need to be changed, since they are based on the current value.
Note: this also illustrates why a `changesBy` API would not make sense for `Signal`. Since in those cases the value may have changed, because `changesBy` is not a "canonical" equality. So then `.discrete` and `.get` would be observably inconsistent.

Add `Signal#changes`

---

core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala
core/shared/src/test/scala/fs2/concurrent/TopicSuite.scala

https://github.com/typelevel/fs2/issues/3071
https://github.com/typelevel/fs2/issues/3133

Mark flaky tests

---

core/shared/src/main/scala/fs2/internal/Scope.scala

Tweak `Scope#close` for a bit better performance

---

core/shared/src/main/scala/fs2/concurrent/Signal.scala

Missed this tiny optimization in my original PR.

Microptimize `Signal#getAndDiscreteUpdates`

---

.github/workflows/ci.yml
build.sbt
core/jvm-native/src/test/scala/fs2/compression/JvmNativeCompressionSuite.scala
core/shared/src/test/scala/fs2/StreamZipSuite.scala
io/jvm/src/test/scala/fs2/io/file/WatcherSuite.scala

Add macOS to CI matrix

---

core/shared/src/test/scala/fs2/BracketSuite.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala
core/shared/src/test/scala/fs2/StreamParJoinSuite.scala
core/shared/src/test/scala/fs2/timeseries/TimeStampedSuite.scala
scodec/shared/src/test/scala/fs2/interop/scodec/SpaceLeakTest.scala

Tempted to just increase it globally on `Fs2Suite` 🤔

Increase timeouts

---

io/js/src/main/scala/fs2/io/ioplatform.scala

Not sure why this was a `Pull`.

Replace recursive `Pull` with `foreach` in `writeWritable`

---

reactive-streams/src/main/scala/fs2/interop/reactivestreams/package.scala

It's also helpful to run `sbt prePR`, which runs tests, generates docs, and performs various checks.

comment typo fix

---

.cirrus.yml
benchmark/src/main/scala/fs2/benchmark/ChunkFlatten.scala
core/shared/src/main/scala-2.12/fs2/ChunkPlatform.scala
core/shared/src/main/scala-2.13+/fs2/Chunk213And3Compat.scala
core/shared/src/main/scala/fs2/Chunk.scala

- Fix deprecated usages in benchmarks
- Fix deprecated since version
- Run macOS Cirrus CI in single job

Fix deprecations and tweak Cirrus CI

---

io/js/src/main/scala/fs2/io/file/FilesPlatform.scala
io/shared/src/test/scala/fs2/io/file/FilesSuite.scala

h/t @TonioGela in https://github.com/typelevel/toolkit/pull/105

Fix temporary file name generation on Node.js

---

core/shared/src/main/scala/fs2/Stream.scala

Add resul type to Stream#`withFilter`

---

site/adopters.md

FS2 underpins numerous of our SaaS services.

Input Objects GmbH adopter

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala

Hello, 
Here is a modest contribution to add a keepAlive on streams, very useful when handling TCP connections with proxies that have timeouts.

feat: add keepAlive method in Stream.

---

core/shared/src/main/scala/fs2/Chunk.scala

Motivation:
Add a collectWhile method to chunk

feat: Add Chunk#collectWhile.

---

io/js-jvm/src/test/scala/fs2/io/net/udp/UdpSuite.scala

Should help with #3376, though note #3406 could still cause failures

Add retries to UdpSuite

---

core/shared/src/main/scala/fs2/Stream.scala
core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala

Fix #3415 - fromIterator looping infinitely

---

project/plugins.sbt

Attempt to get CI working on series/2.5.x

Update to Scala.js 1.16.0 on series/2.5.x

---

core/shared/src/main/scala/fs2/Stream.scala

See: https://discord.com/channels/632277896739946517/632310980449402880/1294207595284009012

Fix docs for Stream.exec function

---

scalafix/project/build.properties
scalafix/project/plugins.sbt
scalafix/rules/src/main/scala/fix/v1.scala
scalafix/tests/src/test/scala/fix/RuleSuite.scala

Updates versions in the scalafix project to fix bitrot.

Scalafix updates
